// export by github.com/goplus/gossa/cmd/qexp

package syscall

import (
	q "syscall"

	"go/constant"
	"reflect"

	"github.com/goplus/gossa"
)

func init() {
	gossa.RegisterPackage(&gossa.Package{
		Name: "syscall",
		Path: "syscall",
		Deps: map[string]string{
			"errors":                          "errors",
			"internal/oserror":                "oserror",
			"internal/race":                   "race",
			"internal/syscall/windows/sysdll": "sysdll",
			"internal/unsafeheader":           "unsafeheader",
			"runtime":                         "runtime",
			"sync":                            "sync",
			"sync/atomic":                     "atomic",
			"unicode/utf16":                   "utf16",
			"unsafe":                          "unsafe",
		},
		Interfaces: map[string]reflect.Type{
			"Conn":     reflect.TypeOf((*q.Conn)(nil)).Elem(),
			"RawConn":  reflect.TypeOf((*q.RawConn)(nil)).Elem(),
			"Sockaddr": reflect.TypeOf((*q.Sockaddr)(nil)).Elem(),
		},
		NamedTypes: map[string]gossa.NamedType{
			"AddrinfoW":                   {reflect.TypeOf((*q.AddrinfoW)(nil)).Elem(), "", ""},
			"ByHandleFileInformation":     {reflect.TypeOf((*q.ByHandleFileInformation)(nil)).Elem(), "", ""},
			"CertChainContext":            {reflect.TypeOf((*q.CertChainContext)(nil)).Elem(), "", ""},
			"CertChainElement":            {reflect.TypeOf((*q.CertChainElement)(nil)).Elem(), "", ""},
			"CertChainPara":               {reflect.TypeOf((*q.CertChainPara)(nil)).Elem(), "", ""},
			"CertChainPolicyPara":         {reflect.TypeOf((*q.CertChainPolicyPara)(nil)).Elem(), "", ""},
			"CertChainPolicyStatus":       {reflect.TypeOf((*q.CertChainPolicyStatus)(nil)).Elem(), "", ""},
			"CertContext":                 {reflect.TypeOf((*q.CertContext)(nil)).Elem(), "", ""},
			"CertEnhKeyUsage":             {reflect.TypeOf((*q.CertEnhKeyUsage)(nil)).Elem(), "", ""},
			"CertInfo":                    {reflect.TypeOf((*q.CertInfo)(nil)).Elem(), "", ""},
			"CertRevocationCrlInfo":       {reflect.TypeOf((*q.CertRevocationCrlInfo)(nil)).Elem(), "", ""},
			"CertRevocationInfo":          {reflect.TypeOf((*q.CertRevocationInfo)(nil)).Elem(), "", ""},
			"CertSimpleChain":             {reflect.TypeOf((*q.CertSimpleChain)(nil)).Elem(), "", ""},
			"CertTrustListInfo":           {reflect.TypeOf((*q.CertTrustListInfo)(nil)).Elem(), "", ""},
			"CertTrustStatus":             {reflect.TypeOf((*q.CertTrustStatus)(nil)).Elem(), "", ""},
			"CertUsageMatch":              {reflect.TypeOf((*q.CertUsageMatch)(nil)).Elem(), "", ""},
			"DLL":                         {reflect.TypeOf((*q.DLL)(nil)).Elem(), "", "FindProc,MustFindProc,Release"},
			"DLLError":                    {reflect.TypeOf((*q.DLLError)(nil)).Elem(), "", "Error,Unwrap"},
			"DNSMXData":                   {reflect.TypeOf((*q.DNSMXData)(nil)).Elem(), "", ""},
			"DNSPTRData":                  {reflect.TypeOf((*q.DNSPTRData)(nil)).Elem(), "", ""},
			"DNSRecord":                   {reflect.TypeOf((*q.DNSRecord)(nil)).Elem(), "", ""},
			"DNSSRVData":                  {reflect.TypeOf((*q.DNSSRVData)(nil)).Elem(), "", ""},
			"DNSTXTData":                  {reflect.TypeOf((*q.DNSTXTData)(nil)).Elem(), "", ""},
			"Errno":                       {reflect.TypeOf((*q.Errno)(nil)).Elem(), "Error,Is,Temporary,Timeout", ""},
			"FileNotifyInformation":       {reflect.TypeOf((*q.FileNotifyInformation)(nil)).Elem(), "", ""},
			"Filetime":                    {reflect.TypeOf((*q.Filetime)(nil)).Elem(), "", "Nanoseconds"},
			"GUID":                        {reflect.TypeOf((*q.GUID)(nil)).Elem(), "", ""},
			"Handle":                      {reflect.TypeOf((*q.Handle)(nil)).Elem(), "", ""},
			"Hostent":                     {reflect.TypeOf((*q.Hostent)(nil)).Elem(), "", ""},
			"IPMreq":                      {reflect.TypeOf((*q.IPMreq)(nil)).Elem(), "", ""},
			"IPv6Mreq":                    {reflect.TypeOf((*q.IPv6Mreq)(nil)).Elem(), "", ""},
			"InterfaceInfo":               {reflect.TypeOf((*q.InterfaceInfo)(nil)).Elem(), "", ""},
			"IpAdapterInfo":               {reflect.TypeOf((*q.IpAdapterInfo)(nil)).Elem(), "", ""},
			"IpAddrString":                {reflect.TypeOf((*q.IpAddrString)(nil)).Elem(), "", ""},
			"IpAddressString":             {reflect.TypeOf((*q.IpAddressString)(nil)).Elem(), "", ""},
			"IpMaskString":                {reflect.TypeOf((*q.IpMaskString)(nil)).Elem(), "", ""},
			"LazyDLL":                     {reflect.TypeOf((*q.LazyDLL)(nil)).Elem(), "", "Handle,Load,NewProc,mustLoad"},
			"LazyProc":                    {reflect.TypeOf((*q.LazyProc)(nil)).Elem(), "", "Addr,Call,Find,mustFind"},
			"Linger":                      {reflect.TypeOf((*q.Linger)(nil)).Elem(), "", ""},
			"MibIfRow":                    {reflect.TypeOf((*q.MibIfRow)(nil)).Elem(), "", ""},
			"Overlapped":                  {reflect.TypeOf((*q.Overlapped)(nil)).Elem(), "", ""},
			"Pointer":                     {reflect.TypeOf((*q.Pointer)(nil)).Elem(), "", ""},
			"Proc":                        {reflect.TypeOf((*q.Proc)(nil)).Elem(), "", "Addr,Call"},
			"ProcAttr":                    {reflect.TypeOf((*q.ProcAttr)(nil)).Elem(), "", ""},
			"ProcessEntry32":              {reflect.TypeOf((*q.ProcessEntry32)(nil)).Elem(), "", ""},
			"ProcessInformation":          {reflect.TypeOf((*q.ProcessInformation)(nil)).Elem(), "", ""},
			"Protoent":                    {reflect.TypeOf((*q.Protoent)(nil)).Elem(), "", ""},
			"RawSockaddr":                 {reflect.TypeOf((*q.RawSockaddr)(nil)).Elem(), "", ""},
			"RawSockaddrAny":              {reflect.TypeOf((*q.RawSockaddrAny)(nil)).Elem(), "", "Sockaddr"},
			"RawSockaddrInet4":            {reflect.TypeOf((*q.RawSockaddrInet4)(nil)).Elem(), "", ""},
			"RawSockaddrInet6":            {reflect.TypeOf((*q.RawSockaddrInet6)(nil)).Elem(), "", ""},
			"RawSockaddrUnix":             {reflect.TypeOf((*q.RawSockaddrUnix)(nil)).Elem(), "", ""},
			"Rusage":                      {reflect.TypeOf((*q.Rusage)(nil)).Elem(), "", ""},
			"SID":                         {reflect.TypeOf((*q.SID)(nil)).Elem(), "", "Copy,Len,LookupAccount,String"},
			"SIDAndAttributes":            {reflect.TypeOf((*q.SIDAndAttributes)(nil)).Elem(), "", ""},
			"SSLExtraCertChainPolicyPara": {reflect.TypeOf((*q.SSLExtraCertChainPolicyPara)(nil)).Elem(), "", ""},
			"SecurityAttributes":          {reflect.TypeOf((*q.SecurityAttributes)(nil)).Elem(), "", ""},
			"Servent":                     {reflect.TypeOf((*q.Servent)(nil)).Elem(), "", ""},
			"Signal":                      {reflect.TypeOf((*q.Signal)(nil)).Elem(), "Signal,String", ""},
			"SockaddrGen":                 {reflect.TypeOf((*q.SockaddrGen)(nil)).Elem(), "", ""},
			"SockaddrInet4":               {reflect.TypeOf((*q.SockaddrInet4)(nil)).Elem(), "", "sockaddr"},
			"SockaddrInet6":               {reflect.TypeOf((*q.SockaddrInet6)(nil)).Elem(), "", "sockaddr"},
			"SockaddrUnix":                {reflect.TypeOf((*q.SockaddrUnix)(nil)).Elem(), "", "sockaddr"},
			"StartupInfo":                 {reflect.TypeOf((*q.StartupInfo)(nil)).Elem(), "", ""},
			"SysProcAttr":                 {reflect.TypeOf((*q.SysProcAttr)(nil)).Elem(), "", ""},
			"Systemtime":                  {reflect.TypeOf((*q.Systemtime)(nil)).Elem(), "", ""},
			"TCPKeepalive":                {reflect.TypeOf((*q.TCPKeepalive)(nil)).Elem(), "", ""},
			"Timespec":                    {reflect.TypeOf((*q.Timespec)(nil)).Elem(), "", "Nano,Unix"},
			"Timeval":                     {reflect.TypeOf((*q.Timeval)(nil)).Elem(), "", "Nano,Nanoseconds,Unix"},
			"Timezoneinformation":         {reflect.TypeOf((*q.Timezoneinformation)(nil)).Elem(), "", ""},
			"Token":                       {reflect.TypeOf((*q.Token)(nil)).Elem(), "Close,GetTokenPrimaryGroup,GetTokenUser,GetUserProfileDirectory,getInfo", ""},
			"Tokenprimarygroup":           {reflect.TypeOf((*q.Tokenprimarygroup)(nil)).Elem(), "", ""},
			"Tokenuser":                   {reflect.TypeOf((*q.Tokenuser)(nil)).Elem(), "", ""},
			"TransmitFileBuffers":         {reflect.TypeOf((*q.TransmitFileBuffers)(nil)).Elem(), "", ""},
			"UserInfo10":                  {reflect.TypeOf((*q.UserInfo10)(nil)).Elem(), "", ""},
			"WSABuf":                      {reflect.TypeOf((*q.WSABuf)(nil)).Elem(), "", ""},
			"WSAData":                     {reflect.TypeOf((*q.WSAData)(nil)).Elem(), "", ""},
			"WSAProtocolChain":            {reflect.TypeOf((*q.WSAProtocolChain)(nil)).Elem(), "", ""},
			"WSAProtocolInfo":             {reflect.TypeOf((*q.WSAProtocolInfo)(nil)).Elem(), "", ""},
			"WaitStatus":                  {reflect.TypeOf((*q.WaitStatus)(nil)).Elem(), "Continued,CoreDump,ExitStatus,Exited,Signal,Signaled,StopSignal,Stopped,TrapCause", ""},
			"Win32FileAttributeData":      {reflect.TypeOf((*q.Win32FileAttributeData)(nil)).Elem(), "", ""},
			"Win32finddata":               {reflect.TypeOf((*q.Win32finddata)(nil)).Elem(), "", ""},
		},
		AliasTypes: map[string]reflect.Type{},
		Vars: map[string]reflect.Value{
			"ForkLock":                reflect.ValueOf(&q.ForkLock),
			"OID_PKIX_KP_SERVER_AUTH": reflect.ValueOf(&q.OID_PKIX_KP_SERVER_AUTH),
			"OID_SERVER_GATED_CRYPTO": reflect.ValueOf(&q.OID_SERVER_GATED_CRYPTO),
			"OID_SGC_NETSCAPE":        reflect.ValueOf(&q.OID_SGC_NETSCAPE),
			"SocketDisableIPv6":       reflect.ValueOf(&q.SocketDisableIPv6),
			"Stderr":                  reflect.ValueOf(&q.Stderr),
			"Stdin":                   reflect.ValueOf(&q.Stdin),
			"Stdout":                  reflect.ValueOf(&q.Stdout),
			"WSAID_CONNECTEX":         reflect.ValueOf(&q.WSAID_CONNECTEX),
		},
		Funcs: map[string]reflect.Value{
			"Accept":                                 reflect.ValueOf(q.Accept),
			"AcceptEx":                               reflect.ValueOf(q.AcceptEx),
			"Bind":                                   reflect.ValueOf(q.Bind),
			"BytePtrFromString":                      reflect.ValueOf(q.BytePtrFromString),
			"ByteSliceFromString":                    reflect.ValueOf(q.ByteSliceFromString),
			"CancelIo":                               reflect.ValueOf(q.CancelIo),
			"CancelIoEx":                             reflect.ValueOf(q.CancelIoEx),
			"CertAddCertificateContextToStore":       reflect.ValueOf(q.CertAddCertificateContextToStore),
			"CertCloseStore":                         reflect.ValueOf(q.CertCloseStore),
			"CertCreateCertificateContext":           reflect.ValueOf(q.CertCreateCertificateContext),
			"CertEnumCertificatesInStore":            reflect.ValueOf(q.CertEnumCertificatesInStore),
			"CertFreeCertificateChain":               reflect.ValueOf(q.CertFreeCertificateChain),
			"CertFreeCertificateContext":             reflect.ValueOf(q.CertFreeCertificateContext),
			"CertGetCertificateChain":                reflect.ValueOf(q.CertGetCertificateChain),
			"CertOpenStore":                          reflect.ValueOf(q.CertOpenStore),
			"CertOpenSystemStore":                    reflect.ValueOf(q.CertOpenSystemStore),
			"CertVerifyCertificateChainPolicy":       reflect.ValueOf(q.CertVerifyCertificateChainPolicy),
			"Chdir":                                  reflect.ValueOf(q.Chdir),
			"Chmod":                                  reflect.ValueOf(q.Chmod),
			"Chown":                                  reflect.ValueOf(q.Chown),
			"Clearenv":                               reflect.ValueOf(q.Clearenv),
			"Close":                                  reflect.ValueOf(q.Close),
			"CloseHandle":                            reflect.ValueOf(q.CloseHandle),
			"CloseOnExec":                            reflect.ValueOf(q.CloseOnExec),
			"Closesocket":                            reflect.ValueOf(q.Closesocket),
			"CommandLineToArgv":                      reflect.ValueOf(q.CommandLineToArgv),
			"ComputerName":                           reflect.ValueOf(q.ComputerName),
			"Connect":                                reflect.ValueOf(q.Connect),
			"ConnectEx":                              reflect.ValueOf(q.ConnectEx),
			"ConvertSidToStringSid":                  reflect.ValueOf(q.ConvertSidToStringSid),
			"ConvertStringSidToSid":                  reflect.ValueOf(q.ConvertStringSidToSid),
			"CopySid":                                reflect.ValueOf(q.CopySid),
			"CreateDirectory":                        reflect.ValueOf(q.CreateDirectory),
			"CreateFile":                             reflect.ValueOf(q.CreateFile),
			"CreateFileMapping":                      reflect.ValueOf(q.CreateFileMapping),
			"CreateHardLink":                         reflect.ValueOf(q.CreateHardLink),
			"CreateIoCompletionPort":                 reflect.ValueOf(q.CreateIoCompletionPort),
			"CreatePipe":                             reflect.ValueOf(q.CreatePipe),
			"CreateProcess":                          reflect.ValueOf(q.CreateProcess),
			"CreateProcessAsUser":                    reflect.ValueOf(q.CreateProcessAsUser),
			"CreateSymbolicLink":                     reflect.ValueOf(q.CreateSymbolicLink),
			"CreateToolhelp32Snapshot":               reflect.ValueOf(q.CreateToolhelp32Snapshot),
			"CryptAcquireContext":                    reflect.ValueOf(q.CryptAcquireContext),
			"CryptGenRandom":                         reflect.ValueOf(q.CryptGenRandom),
			"CryptReleaseContext":                    reflect.ValueOf(q.CryptReleaseContext),
			"DeleteFile":                             reflect.ValueOf(q.DeleteFile),
			"DeviceIoControl":                        reflect.ValueOf(q.DeviceIoControl),
			"DnsNameCompare":                         reflect.ValueOf(q.DnsNameCompare),
			"DnsQuery":                               reflect.ValueOf(q.DnsQuery),
			"DnsRecordListFree":                      reflect.ValueOf(q.DnsRecordListFree),
			"DuplicateHandle":                        reflect.ValueOf(q.DuplicateHandle),
			"Environ":                                reflect.ValueOf(q.Environ),
			"EscapeArg":                              reflect.ValueOf(q.EscapeArg),
			"Exec":                                   reflect.ValueOf(q.Exec),
			"Exit":                                   reflect.ValueOf(q.Exit),
			"ExitProcess":                            reflect.ValueOf(q.ExitProcess),
			"Fchdir":                                 reflect.ValueOf(q.Fchdir),
			"Fchmod":                                 reflect.ValueOf(q.Fchmod),
			"Fchown":                                 reflect.ValueOf(q.Fchown),
			"FindClose":                              reflect.ValueOf(q.FindClose),
			"FindFirstFile":                          reflect.ValueOf(q.FindFirstFile),
			"FindNextFile":                           reflect.ValueOf(q.FindNextFile),
			"FlushFileBuffers":                       reflect.ValueOf(q.FlushFileBuffers),
			"FlushViewOfFile":                        reflect.ValueOf(q.FlushViewOfFile),
			"FormatMessage":                          reflect.ValueOf(q.FormatMessage),
			"FreeAddrInfoW":                          reflect.ValueOf(q.FreeAddrInfoW),
			"FreeEnvironmentStrings":                 reflect.ValueOf(q.FreeEnvironmentStrings),
			"FreeLibrary":                            reflect.ValueOf(q.FreeLibrary),
			"Fsync":                                  reflect.ValueOf(q.Fsync),
			"Ftruncate":                              reflect.ValueOf(q.Ftruncate),
			"FullPath":                               reflect.ValueOf(q.FullPath),
			"GetAcceptExSockaddrs":                   reflect.ValueOf(q.GetAcceptExSockaddrs),
			"GetAdaptersInfo":                        reflect.ValueOf(q.GetAdaptersInfo),
			"GetAddrInfoW":                           reflect.ValueOf(q.GetAddrInfoW),
			"GetCommandLine":                         reflect.ValueOf(q.GetCommandLine),
			"GetComputerName":                        reflect.ValueOf(q.GetComputerName),
			"GetConsoleMode":                         reflect.ValueOf(q.GetConsoleMode),
			"GetCurrentDirectory":                    reflect.ValueOf(q.GetCurrentDirectory),
			"GetCurrentProcess":                      reflect.ValueOf(q.GetCurrentProcess),
			"GetEnvironmentStrings":                  reflect.ValueOf(q.GetEnvironmentStrings),
			"GetEnvironmentVariable":                 reflect.ValueOf(q.GetEnvironmentVariable),
			"GetExitCodeProcess":                     reflect.ValueOf(q.GetExitCodeProcess),
			"GetFileAttributes":                      reflect.ValueOf(q.GetFileAttributes),
			"GetFileAttributesEx":                    reflect.ValueOf(q.GetFileAttributesEx),
			"GetFileInformationByHandle":             reflect.ValueOf(q.GetFileInformationByHandle),
			"GetFileType":                            reflect.ValueOf(q.GetFileType),
			"GetFullPathName":                        reflect.ValueOf(q.GetFullPathName),
			"GetHostByName":                          reflect.ValueOf(q.GetHostByName),
			"GetIfEntry":                             reflect.ValueOf(q.GetIfEntry),
			"GetLastError":                           reflect.ValueOf(q.GetLastError),
			"GetLengthSid":                           reflect.ValueOf(q.GetLengthSid),
			"GetLongPathName":                        reflect.ValueOf(q.GetLongPathName),
			"GetProcAddress":                         reflect.ValueOf(q.GetProcAddress),
			"GetProcessTimes":                        reflect.ValueOf(q.GetProcessTimes),
			"GetProtoByName":                         reflect.ValueOf(q.GetProtoByName),
			"GetQueuedCompletionStatus":              reflect.ValueOf(q.GetQueuedCompletionStatus),
			"GetServByName":                          reflect.ValueOf(q.GetServByName),
			"GetShortPathName":                       reflect.ValueOf(q.GetShortPathName),
			"GetStartupInfo":                         reflect.ValueOf(q.GetStartupInfo),
			"GetStdHandle":                           reflect.ValueOf(q.GetStdHandle),
			"GetSystemTimeAsFileTime":                reflect.ValueOf(q.GetSystemTimeAsFileTime),
			"GetTempPath":                            reflect.ValueOf(q.GetTempPath),
			"GetTimeZoneInformation":                 reflect.ValueOf(q.GetTimeZoneInformation),
			"GetTokenInformation":                    reflect.ValueOf(q.GetTokenInformation),
			"GetUserNameEx":                          reflect.ValueOf(q.GetUserNameEx),
			"GetUserProfileDirectory":                reflect.ValueOf(q.GetUserProfileDirectory),
			"GetVersion":                             reflect.ValueOf(q.GetVersion),
			"Getegid":                                reflect.ValueOf(q.Getegid),
			"Getenv":                                 reflect.ValueOf(q.Getenv),
			"Geteuid":                                reflect.ValueOf(q.Geteuid),
			"Getgid":                                 reflect.ValueOf(q.Getgid),
			"Getgroups":                              reflect.ValueOf(q.Getgroups),
			"Getpagesize":                            reflect.ValueOf(q.Getpagesize),
			"Getpeername":                            reflect.ValueOf(q.Getpeername),
			"Getpid":                                 reflect.ValueOf(q.Getpid),
			"Getppid":                                reflect.ValueOf(q.Getppid),
			"Getsockname":                            reflect.ValueOf(q.Getsockname),
			"Getsockopt":                             reflect.ValueOf(q.Getsockopt),
			"GetsockoptInt":                          reflect.ValueOf(q.GetsockoptInt),
			"Gettimeofday":                           reflect.ValueOf(q.Gettimeofday),
			"Getuid":                                 reflect.ValueOf(q.Getuid),
			"Getwd":                                  reflect.ValueOf(q.Getwd),
			"Lchown":                                 reflect.ValueOf(q.Lchown),
			"Link":                                   reflect.ValueOf(q.Link),
			"Listen":                                 reflect.ValueOf(q.Listen),
			"LoadCancelIoEx":                         reflect.ValueOf(q.LoadCancelIoEx),
			"LoadConnectEx":                          reflect.ValueOf(q.LoadConnectEx),
			"LoadCreateSymbolicLink":                 reflect.ValueOf(q.LoadCreateSymbolicLink),
			"LoadDLL":                                reflect.ValueOf(q.LoadDLL),
			"LoadGetAddrInfo":                        reflect.ValueOf(q.LoadGetAddrInfo),
			"LoadLibrary":                            reflect.ValueOf(q.LoadLibrary),
			"LoadSetFileCompletionNotificationModes": reflect.ValueOf(q.LoadSetFileCompletionNotificationModes),
			"LocalFree":                              reflect.ValueOf(q.LocalFree),
			"LookupAccountName":                      reflect.ValueOf(q.LookupAccountName),
			"LookupAccountSid":                       reflect.ValueOf(q.LookupAccountSid),
			"LookupSID":                              reflect.ValueOf(q.LookupSID),
			"MapViewOfFile":                          reflect.ValueOf(q.MapViewOfFile),
			"Mkdir":                                  reflect.ValueOf(q.Mkdir),
			"MoveFile":                               reflect.ValueOf(q.MoveFile),
			"MustLoadDLL":                            reflect.ValueOf(q.MustLoadDLL),
			"NetApiBufferFree":                       reflect.ValueOf(q.NetApiBufferFree),
			"NetGetJoinInformation":                  reflect.ValueOf(q.NetGetJoinInformation),
			"NetUserGetInfo":                         reflect.ValueOf(q.NetUserGetInfo),
			"NewCallback":                            reflect.ValueOf(q.NewCallback),
			"NewCallbackCDecl":                       reflect.ValueOf(q.NewCallbackCDecl),
			"NewLazyDLL":                             reflect.ValueOf(q.NewLazyDLL),
			"NsecToFiletime":                         reflect.ValueOf(q.NsecToFiletime),
			"NsecToTimespec":                         reflect.ValueOf(q.NsecToTimespec),
			"NsecToTimeval":                          reflect.ValueOf(q.NsecToTimeval),
			"Ntohs":                                  reflect.ValueOf(q.Ntohs),
			"Open":                                   reflect.ValueOf(q.Open),
			"OpenCurrentProcessToken":                reflect.ValueOf(q.OpenCurrentProcessToken),
			"OpenProcess":                            reflect.ValueOf(q.OpenProcess),
			"OpenProcessToken":                       reflect.ValueOf(q.OpenProcessToken),
			"Pipe":                                   reflect.ValueOf(q.Pipe),
			"PostQueuedCompletionStatus":             reflect.ValueOf(q.PostQueuedCompletionStatus),
			"Process32First":                         reflect.ValueOf(q.Process32First),
			"Process32Next":                          reflect.ValueOf(q.Process32Next),
			"Read":                                   reflect.ValueOf(q.Read),
			"ReadConsole":                            reflect.ValueOf(q.ReadConsole),
			"ReadDirectoryChanges":                   reflect.ValueOf(q.ReadDirectoryChanges),
			"ReadFile":                               reflect.ValueOf(q.ReadFile),
			"Readlink":                               reflect.ValueOf(q.Readlink),
			"Recvfrom":                               reflect.ValueOf(q.Recvfrom),
			"RegCloseKey":                            reflect.ValueOf(q.RegCloseKey),
			"RegEnumKeyEx":                           reflect.ValueOf(q.RegEnumKeyEx),
			"RegOpenKeyEx":                           reflect.ValueOf(q.RegOpenKeyEx),
			"RegQueryInfoKey":                        reflect.ValueOf(q.RegQueryInfoKey),
			"RegQueryValueEx":                        reflect.ValueOf(q.RegQueryValueEx),
			"RemoveDirectory":                        reflect.ValueOf(q.RemoveDirectory),
			"Rename":                                 reflect.ValueOf(q.Rename),
			"Rmdir":                                  reflect.ValueOf(q.Rmdir),
			"Seek":                                   reflect.ValueOf(q.Seek),
			"Sendto":                                 reflect.ValueOf(q.Sendto),
			"SetCurrentDirectory":                    reflect.ValueOf(q.SetCurrentDirectory),
			"SetEndOfFile":                           reflect.ValueOf(q.SetEndOfFile),
			"SetEnvironmentVariable":                 reflect.ValueOf(q.SetEnvironmentVariable),
			"SetFileAttributes":                      reflect.ValueOf(q.SetFileAttributes),
			"SetFileCompletionNotificationModes":     reflect.ValueOf(q.SetFileCompletionNotificationModes),
			"SetFilePointer":                         reflect.ValueOf(q.SetFilePointer),
			"SetFileTime":                            reflect.ValueOf(q.SetFileTime),
			"SetHandleInformation":                   reflect.ValueOf(q.SetHandleInformation),
			"SetNonblock":                            reflect.ValueOf(q.SetNonblock),
			"Setenv":                                 reflect.ValueOf(q.Setenv),
			"Setsockopt":                             reflect.ValueOf(q.Setsockopt),
			"SetsockoptIPMreq":                       reflect.ValueOf(q.SetsockoptIPMreq),
			"SetsockoptIPv6Mreq":                     reflect.ValueOf(q.SetsockoptIPv6Mreq),
			"SetsockoptInet4Addr":                    reflect.ValueOf(q.SetsockoptInet4Addr),
			"SetsockoptInt":                          reflect.ValueOf(q.SetsockoptInt),
			"SetsockoptLinger":                       reflect.ValueOf(q.SetsockoptLinger),
			"SetsockoptTimeval":                      reflect.ValueOf(q.SetsockoptTimeval),
			"Shutdown":                               reflect.ValueOf(q.Shutdown),
			"Socket":                                 reflect.ValueOf(q.Socket),
			"StartProcess":                           reflect.ValueOf(q.StartProcess),
			"StringBytePtr":                          reflect.ValueOf(q.StringBytePtr),
			"StringByteSlice":                        reflect.ValueOf(q.StringByteSlice),
			"StringToSid":                            reflect.ValueOf(q.StringToSid),
			"StringToUTF16":                          reflect.ValueOf(q.StringToUTF16),
			"StringToUTF16Ptr":                       reflect.ValueOf(q.StringToUTF16Ptr),
			"Symlink":                                reflect.ValueOf(q.Symlink),
			"Syscall":                                reflect.ValueOf(q.Syscall),
			"Syscall12":                              reflect.ValueOf(q.Syscall12),
			"Syscall15":                              reflect.ValueOf(q.Syscall15),
			"Syscall18":                              reflect.ValueOf(q.Syscall18),
			"Syscall6":                               reflect.ValueOf(q.Syscall6),
			"Syscall9":                               reflect.ValueOf(q.Syscall9),
			"TerminateProcess":                       reflect.ValueOf(q.TerminateProcess),
			"TimespecToNsec":                         reflect.ValueOf(q.TimespecToNsec),
			"TranslateAccountName":                   reflect.ValueOf(q.TranslateAccountName),
			"TranslateName":                          reflect.ValueOf(q.TranslateName),
			"TransmitFile":                           reflect.ValueOf(q.TransmitFile),
			"UTF16FromString":                        reflect.ValueOf(q.UTF16FromString),
			"UTF16PtrFromString":                     reflect.ValueOf(q.UTF16PtrFromString),
			"UTF16ToString":                          reflect.ValueOf(q.UTF16ToString),
			"Unlink":                                 reflect.ValueOf(q.Unlink),
			"UnmapViewOfFile":                        reflect.ValueOf(q.UnmapViewOfFile),
			"Unsetenv":                               reflect.ValueOf(q.Unsetenv),
			"Utimes":                                 reflect.ValueOf(q.Utimes),
			"UtimesNano":                             reflect.ValueOf(q.UtimesNano),
			"VirtualLock":                            reflect.ValueOf(q.VirtualLock),
			"VirtualUnlock":                          reflect.ValueOf(q.VirtualUnlock),
			"WSACleanup":                             reflect.ValueOf(q.WSACleanup),
			"WSAEnumProtocols":                       reflect.ValueOf(q.WSAEnumProtocols),
			"WSAIoctl":                               reflect.ValueOf(q.WSAIoctl),
			"WSARecv":                                reflect.ValueOf(q.WSARecv),
			"WSARecvFrom":                            reflect.ValueOf(q.WSARecvFrom),
			"WSASend":                                reflect.ValueOf(q.WSASend),
			"WSASendTo":                              reflect.ValueOf(q.WSASendTo),
			"WSASendto":                              reflect.ValueOf(q.WSASendto),
			"WSAStartup":                             reflect.ValueOf(q.WSAStartup),
			"WaitForSingleObject":                    reflect.ValueOf(q.WaitForSingleObject),
			"Write":                                  reflect.ValueOf(q.Write),
			"WriteConsole":                           reflect.ValueOf(q.WriteConsole),
			"WriteFile":                              reflect.ValueOf(q.WriteFile),
		},
		TypedConsts: map[string]gossa.TypedConst{
			"E2BIG":                     {reflect.TypeOf(q.E2BIG), constant.MakeInt64(536870912)},
			"EACCES":                    {reflect.TypeOf(q.EACCES), constant.MakeInt64(536870913)},
			"EADDRINUSE":                {reflect.TypeOf(q.EADDRINUSE), constant.MakeInt64(536870914)},
			"EADDRNOTAVAIL":             {reflect.TypeOf(q.EADDRNOTAVAIL), constant.MakeInt64(536870915)},
			"EADV":                      {reflect.TypeOf(q.EADV), constant.MakeInt64(536870916)},
			"EAFNOSUPPORT":              {reflect.TypeOf(q.EAFNOSUPPORT), constant.MakeInt64(536870917)},
			"EAGAIN":                    {reflect.TypeOf(q.EAGAIN), constant.MakeInt64(536870918)},
			"EALREADY":                  {reflect.TypeOf(q.EALREADY), constant.MakeInt64(536870919)},
			"EBADE":                     {reflect.TypeOf(q.EBADE), constant.MakeInt64(536870920)},
			"EBADF":                     {reflect.TypeOf(q.EBADF), constant.MakeInt64(536870921)},
			"EBADFD":                    {reflect.TypeOf(q.EBADFD), constant.MakeInt64(536870922)},
			"EBADMSG":                   {reflect.TypeOf(q.EBADMSG), constant.MakeInt64(536870923)},
			"EBADR":                     {reflect.TypeOf(q.EBADR), constant.MakeInt64(536870924)},
			"EBADRQC":                   {reflect.TypeOf(q.EBADRQC), constant.MakeInt64(536870925)},
			"EBADSLT":                   {reflect.TypeOf(q.EBADSLT), constant.MakeInt64(536870926)},
			"EBFONT":                    {reflect.TypeOf(q.EBFONT), constant.MakeInt64(536870927)},
			"EBUSY":                     {reflect.TypeOf(q.EBUSY), constant.MakeInt64(536870928)},
			"ECANCELED":                 {reflect.TypeOf(q.ECANCELED), constant.MakeInt64(536870929)},
			"ECHILD":                    {reflect.TypeOf(q.ECHILD), constant.MakeInt64(536870930)},
			"ECHRNG":                    {reflect.TypeOf(q.ECHRNG), constant.MakeInt64(536870931)},
			"ECOMM":                     {reflect.TypeOf(q.ECOMM), constant.MakeInt64(536870932)},
			"ECONNABORTED":              {reflect.TypeOf(q.ECONNABORTED), constant.MakeInt64(536870933)},
			"ECONNREFUSED":              {reflect.TypeOf(q.ECONNREFUSED), constant.MakeInt64(536870934)},
			"ECONNRESET":                {reflect.TypeOf(q.ECONNRESET), constant.MakeInt64(536870935)},
			"EDEADLK":                   {reflect.TypeOf(q.EDEADLK), constant.MakeInt64(536870936)},
			"EDEADLOCK":                 {reflect.TypeOf(q.EDEADLOCK), constant.MakeInt64(536870937)},
			"EDESTADDRREQ":              {reflect.TypeOf(q.EDESTADDRREQ), constant.MakeInt64(536870938)},
			"EDOM":                      {reflect.TypeOf(q.EDOM), constant.MakeInt64(536870939)},
			"EDOTDOT":                   {reflect.TypeOf(q.EDOTDOT), constant.MakeInt64(536870940)},
			"EDQUOT":                    {reflect.TypeOf(q.EDQUOT), constant.MakeInt64(536870941)},
			"EEXIST":                    {reflect.TypeOf(q.EEXIST), constant.MakeInt64(536870942)},
			"EFAULT":                    {reflect.TypeOf(q.EFAULT), constant.MakeInt64(536870943)},
			"EFBIG":                     {reflect.TypeOf(q.EFBIG), constant.MakeInt64(536870944)},
			"EHOSTDOWN":                 {reflect.TypeOf(q.EHOSTDOWN), constant.MakeInt64(536870945)},
			"EHOSTUNREACH":              {reflect.TypeOf(q.EHOSTUNREACH), constant.MakeInt64(536870946)},
			"EIDRM":                     {reflect.TypeOf(q.EIDRM), constant.MakeInt64(536870947)},
			"EILSEQ":                    {reflect.TypeOf(q.EILSEQ), constant.MakeInt64(536870948)},
			"EINPROGRESS":               {reflect.TypeOf(q.EINPROGRESS), constant.MakeInt64(536870949)},
			"EINTR":                     {reflect.TypeOf(q.EINTR), constant.MakeInt64(536870950)},
			"EINVAL":                    {reflect.TypeOf(q.EINVAL), constant.MakeInt64(536870951)},
			"EIO":                       {reflect.TypeOf(q.EIO), constant.MakeInt64(536870952)},
			"EISCONN":                   {reflect.TypeOf(q.EISCONN), constant.MakeInt64(536870953)},
			"EISDIR":                    {reflect.TypeOf(q.EISDIR), constant.MakeInt64(536870954)},
			"EISNAM":                    {reflect.TypeOf(q.EISNAM), constant.MakeInt64(536870955)},
			"EKEYEXPIRED":               {reflect.TypeOf(q.EKEYEXPIRED), constant.MakeInt64(536870956)},
			"EKEYREJECTED":              {reflect.TypeOf(q.EKEYREJECTED), constant.MakeInt64(536870957)},
			"EKEYREVOKED":               {reflect.TypeOf(q.EKEYREVOKED), constant.MakeInt64(536870958)},
			"EL2HLT":                    {reflect.TypeOf(q.EL2HLT), constant.MakeInt64(536870959)},
			"EL2NSYNC":                  {reflect.TypeOf(q.EL2NSYNC), constant.MakeInt64(536870960)},
			"EL3HLT":                    {reflect.TypeOf(q.EL3HLT), constant.MakeInt64(536870961)},
			"EL3RST":                    {reflect.TypeOf(q.EL3RST), constant.MakeInt64(536870962)},
			"ELIBACC":                   {reflect.TypeOf(q.ELIBACC), constant.MakeInt64(536870963)},
			"ELIBBAD":                   {reflect.TypeOf(q.ELIBBAD), constant.MakeInt64(536870964)},
			"ELIBEXEC":                  {reflect.TypeOf(q.ELIBEXEC), constant.MakeInt64(536870965)},
			"ELIBMAX":                   {reflect.TypeOf(q.ELIBMAX), constant.MakeInt64(536870966)},
			"ELIBSCN":                   {reflect.TypeOf(q.ELIBSCN), constant.MakeInt64(536870967)},
			"ELNRNG":                    {reflect.TypeOf(q.ELNRNG), constant.MakeInt64(536870968)},
			"ELOOP":                     {reflect.TypeOf(q.ELOOP), constant.MakeInt64(536870969)},
			"EMEDIUMTYPE":               {reflect.TypeOf(q.EMEDIUMTYPE), constant.MakeInt64(536870970)},
			"EMFILE":                    {reflect.TypeOf(q.EMFILE), constant.MakeInt64(536870971)},
			"EMLINK":                    {reflect.TypeOf(q.EMLINK), constant.MakeInt64(536870972)},
			"EMSGSIZE":                  {reflect.TypeOf(q.EMSGSIZE), constant.MakeInt64(536870973)},
			"EMULTIHOP":                 {reflect.TypeOf(q.EMULTIHOP), constant.MakeInt64(536870974)},
			"ENAMETOOLONG":              {reflect.TypeOf(q.ENAMETOOLONG), constant.MakeInt64(536870975)},
			"ENAVAIL":                   {reflect.TypeOf(q.ENAVAIL), constant.MakeInt64(536870976)},
			"ENETDOWN":                  {reflect.TypeOf(q.ENETDOWN), constant.MakeInt64(536870977)},
			"ENETRESET":                 {reflect.TypeOf(q.ENETRESET), constant.MakeInt64(536870978)},
			"ENETUNREACH":               {reflect.TypeOf(q.ENETUNREACH), constant.MakeInt64(536870979)},
			"ENFILE":                    {reflect.TypeOf(q.ENFILE), constant.MakeInt64(536870980)},
			"ENOANO":                    {reflect.TypeOf(q.ENOANO), constant.MakeInt64(536870981)},
			"ENOBUFS":                   {reflect.TypeOf(q.ENOBUFS), constant.MakeInt64(536870982)},
			"ENOCSI":                    {reflect.TypeOf(q.ENOCSI), constant.MakeInt64(536870983)},
			"ENODATA":                   {reflect.TypeOf(q.ENODATA), constant.MakeInt64(536870984)},
			"ENODEV":                    {reflect.TypeOf(q.ENODEV), constant.MakeInt64(536870985)},
			"ENOENT":                    {reflect.TypeOf(q.ENOENT), constant.MakeInt64(2)},
			"ENOEXEC":                   {reflect.TypeOf(q.ENOEXEC), constant.MakeInt64(536870986)},
			"ENOKEY":                    {reflect.TypeOf(q.ENOKEY), constant.MakeInt64(536870987)},
			"ENOLCK":                    {reflect.TypeOf(q.ENOLCK), constant.MakeInt64(536870988)},
			"ENOLINK":                   {reflect.TypeOf(q.ENOLINK), constant.MakeInt64(536870989)},
			"ENOMEDIUM":                 {reflect.TypeOf(q.ENOMEDIUM), constant.MakeInt64(536870990)},
			"ENOMEM":                    {reflect.TypeOf(q.ENOMEM), constant.MakeInt64(536870991)},
			"ENOMSG":                    {reflect.TypeOf(q.ENOMSG), constant.MakeInt64(536870992)},
			"ENONET":                    {reflect.TypeOf(q.ENONET), constant.MakeInt64(536870993)},
			"ENOPKG":                    {reflect.TypeOf(q.ENOPKG), constant.MakeInt64(536870994)},
			"ENOPROTOOPT":               {reflect.TypeOf(q.ENOPROTOOPT), constant.MakeInt64(536870995)},
			"ENOSPC":                    {reflect.TypeOf(q.ENOSPC), constant.MakeInt64(536870996)},
			"ENOSR":                     {reflect.TypeOf(q.ENOSR), constant.MakeInt64(536870997)},
			"ENOSTR":                    {reflect.TypeOf(q.ENOSTR), constant.MakeInt64(536870998)},
			"ENOSYS":                    {reflect.TypeOf(q.ENOSYS), constant.MakeInt64(536870999)},
			"ENOTBLK":                   {reflect.TypeOf(q.ENOTBLK), constant.MakeInt64(536871000)},
			"ENOTCONN":                  {reflect.TypeOf(q.ENOTCONN), constant.MakeInt64(536871001)},
			"ENOTDIR":                   {reflect.TypeOf(q.ENOTDIR), constant.MakeInt64(3)},
			"ENOTEMPTY":                 {reflect.TypeOf(q.ENOTEMPTY), constant.MakeInt64(536871002)},
			"ENOTNAM":                   {reflect.TypeOf(q.ENOTNAM), constant.MakeInt64(536871003)},
			"ENOTRECOVERABLE":           {reflect.TypeOf(q.ENOTRECOVERABLE), constant.MakeInt64(536871004)},
			"ENOTSOCK":                  {reflect.TypeOf(q.ENOTSOCK), constant.MakeInt64(536871005)},
			"ENOTSUP":                   {reflect.TypeOf(q.ENOTSUP), constant.MakeInt64(536871006)},
			"ENOTTY":                    {reflect.TypeOf(q.ENOTTY), constant.MakeInt64(536871007)},
			"ENOTUNIQ":                  {reflect.TypeOf(q.ENOTUNIQ), constant.MakeInt64(536871008)},
			"ENXIO":                     {reflect.TypeOf(q.ENXIO), constant.MakeInt64(536871009)},
			"EOPNOTSUPP":                {reflect.TypeOf(q.EOPNOTSUPP), constant.MakeInt64(536871010)},
			"EOVERFLOW":                 {reflect.TypeOf(q.EOVERFLOW), constant.MakeInt64(536871011)},
			"EOWNERDEAD":                {reflect.TypeOf(q.EOWNERDEAD), constant.MakeInt64(536871012)},
			"EPERM":                     {reflect.TypeOf(q.EPERM), constant.MakeInt64(536871013)},
			"EPFNOSUPPORT":              {reflect.TypeOf(q.EPFNOSUPPORT), constant.MakeInt64(536871014)},
			"EPIPE":                     {reflect.TypeOf(q.EPIPE), constant.MakeInt64(536871015)},
			"EPROTO":                    {reflect.TypeOf(q.EPROTO), constant.MakeInt64(536871016)},
			"EPROTONOSUPPORT":           {reflect.TypeOf(q.EPROTONOSUPPORT), constant.MakeInt64(536871017)},
			"EPROTOTYPE":                {reflect.TypeOf(q.EPROTOTYPE), constant.MakeInt64(536871018)},
			"ERANGE":                    {reflect.TypeOf(q.ERANGE), constant.MakeInt64(536871019)},
			"EREMCHG":                   {reflect.TypeOf(q.EREMCHG), constant.MakeInt64(536871020)},
			"EREMOTE":                   {reflect.TypeOf(q.EREMOTE), constant.MakeInt64(536871021)},
			"EREMOTEIO":                 {reflect.TypeOf(q.EREMOTEIO), constant.MakeInt64(536871022)},
			"ERESTART":                  {reflect.TypeOf(q.ERESTART), constant.MakeInt64(536871023)},
			"EROFS":                     {reflect.TypeOf(q.EROFS), constant.MakeInt64(536871024)},
			"ERROR_ACCESS_DENIED":       {reflect.TypeOf(q.ERROR_ACCESS_DENIED), constant.MakeInt64(5)},
			"ERROR_ALREADY_EXISTS":      {reflect.TypeOf(q.ERROR_ALREADY_EXISTS), constant.MakeInt64(183)},
			"ERROR_BROKEN_PIPE":         {reflect.TypeOf(q.ERROR_BROKEN_PIPE), constant.MakeInt64(109)},
			"ERROR_BUFFER_OVERFLOW":     {reflect.TypeOf(q.ERROR_BUFFER_OVERFLOW), constant.MakeInt64(111)},
			"ERROR_DIR_NOT_EMPTY":       {reflect.TypeOf(q.ERROR_DIR_NOT_EMPTY), constant.MakeInt64(145)},
			"ERROR_ENVVAR_NOT_FOUND":    {reflect.TypeOf(q.ERROR_ENVVAR_NOT_FOUND), constant.MakeInt64(203)},
			"ERROR_FILE_EXISTS":         {reflect.TypeOf(q.ERROR_FILE_EXISTS), constant.MakeInt64(80)},
			"ERROR_FILE_NOT_FOUND":      {reflect.TypeOf(q.ERROR_FILE_NOT_FOUND), constant.MakeInt64(2)},
			"ERROR_HANDLE_EOF":          {reflect.TypeOf(q.ERROR_HANDLE_EOF), constant.MakeInt64(38)},
			"ERROR_INSUFFICIENT_BUFFER": {reflect.TypeOf(q.ERROR_INSUFFICIENT_BUFFER), constant.MakeInt64(122)},
			"ERROR_IO_PENDING":          {reflect.TypeOf(q.ERROR_IO_PENDING), constant.MakeInt64(997)},
			"ERROR_MOD_NOT_FOUND":       {reflect.TypeOf(q.ERROR_MOD_NOT_FOUND), constant.MakeInt64(126)},
			"ERROR_MORE_DATA":           {reflect.TypeOf(q.ERROR_MORE_DATA), constant.MakeInt64(234)},
			"ERROR_NETNAME_DELETED":     {reflect.TypeOf(q.ERROR_NETNAME_DELETED), constant.MakeInt64(64)},
			"ERROR_NOT_FOUND":           {reflect.TypeOf(q.ERROR_NOT_FOUND), constant.MakeInt64(1168)},
			"ERROR_NO_MORE_FILES":       {reflect.TypeOf(q.ERROR_NO_MORE_FILES), constant.MakeInt64(18)},
			"ERROR_OPERATION_ABORTED":   {reflect.TypeOf(q.ERROR_OPERATION_ABORTED), constant.MakeInt64(995)},
			"ERROR_PATH_NOT_FOUND":      {reflect.TypeOf(q.ERROR_PATH_NOT_FOUND), constant.MakeInt64(3)},
			"ERROR_PRIVILEGE_NOT_HELD":  {reflect.TypeOf(q.ERROR_PRIVILEGE_NOT_HELD), constant.MakeInt64(1314)},
			"ERROR_PROC_NOT_FOUND":      {reflect.TypeOf(q.ERROR_PROC_NOT_FOUND), constant.MakeInt64(127)},
			"ESHUTDOWN":                 {reflect.TypeOf(q.ESHUTDOWN), constant.MakeInt64(536871025)},
			"ESOCKTNOSUPPORT":           {reflect.TypeOf(q.ESOCKTNOSUPPORT), constant.MakeInt64(536871026)},
			"ESPIPE":                    {reflect.TypeOf(q.ESPIPE), constant.MakeInt64(536871027)},
			"ESRCH":                     {reflect.TypeOf(q.ESRCH), constant.MakeInt64(536871028)},
			"ESRMNT":                    {reflect.TypeOf(q.ESRMNT), constant.MakeInt64(536871029)},
			"ESTALE":                    {reflect.TypeOf(q.ESTALE), constant.MakeInt64(536871030)},
			"ESTRPIPE":                  {reflect.TypeOf(q.ESTRPIPE), constant.MakeInt64(536871031)},
			"ETIME":                     {reflect.TypeOf(q.ETIME), constant.MakeInt64(536871032)},
			"ETIMEDOUT":                 {reflect.TypeOf(q.ETIMEDOUT), constant.MakeInt64(536871033)},
			"ETOOMANYREFS":              {reflect.TypeOf(q.ETOOMANYREFS), constant.MakeInt64(536871034)},
			"ETXTBSY":                   {reflect.TypeOf(q.ETXTBSY), constant.MakeInt64(536871035)},
			"EUCLEAN":                   {reflect.TypeOf(q.EUCLEAN), constant.MakeInt64(536871036)},
			"EUNATCH":                   {reflect.TypeOf(q.EUNATCH), constant.MakeInt64(536871037)},
			"EUSERS":                    {reflect.TypeOf(q.EUSERS), constant.MakeInt64(536871038)},
			"EWINDOWS":                  {reflect.TypeOf(q.EWINDOWS), constant.MakeInt64(536871042)},
			"EWOULDBLOCK":               {reflect.TypeOf(q.EWOULDBLOCK), constant.MakeInt64(536871039)},
			"EXDEV":                     {reflect.TypeOf(q.EXDEV), constant.MakeInt64(536871040)},
			"EXFULL":                    {reflect.TypeOf(q.EXFULL), constant.MakeInt64(536871041)},
			"InvalidHandle":             {reflect.TypeOf(q.InvalidHandle), constant.MakeUint64(18446744073709551615)},
			"SIGABRT":                   {reflect.TypeOf(q.SIGABRT), constant.MakeInt64(6)},
			"SIGALRM":                   {reflect.TypeOf(q.SIGALRM), constant.MakeInt64(14)},
			"SIGBUS":                    {reflect.TypeOf(q.SIGBUS), constant.MakeInt64(7)},
			"SIGFPE":                    {reflect.TypeOf(q.SIGFPE), constant.MakeInt64(8)},
			"SIGHUP":                    {reflect.TypeOf(q.SIGHUP), constant.MakeInt64(1)},
			"SIGILL":                    {reflect.TypeOf(q.SIGILL), constant.MakeInt64(4)},
			"SIGINT":                    {reflect.TypeOf(q.SIGINT), constant.MakeInt64(2)},
			"SIGKILL":                   {reflect.TypeOf(q.SIGKILL), constant.MakeInt64(9)},
			"SIGPIPE":                   {reflect.TypeOf(q.SIGPIPE), constant.MakeInt64(13)},
			"SIGQUIT":                   {reflect.TypeOf(q.SIGQUIT), constant.MakeInt64(3)},
			"SIGSEGV":                   {reflect.TypeOf(q.SIGSEGV), constant.MakeInt64(11)},
			"SIGTERM":                   {reflect.TypeOf(q.SIGTERM), constant.MakeInt64(15)},
			"SIGTRAP":                   {reflect.TypeOf(q.SIGTRAP), constant.MakeInt64(5)},
			"WSAEACCES":                 {reflect.TypeOf(q.WSAEACCES), constant.MakeInt64(10013)},
			"WSAECONNABORTED":           {reflect.TypeOf(q.WSAECONNABORTED), constant.MakeInt64(10053)},
			"WSAECONNRESET":             {reflect.TypeOf(q.WSAECONNRESET), constant.MakeInt64(10054)},
		},
		UntypedConsts: map[string]gossa.UntypedConst{
			"AF_INET":                             {"untyped int", constant.MakeInt64(2)},
			"AF_INET6":                            {"untyped int", constant.MakeInt64(23)},
			"AF_NETBIOS":                          {"untyped int", constant.MakeInt64(17)},
			"AF_UNIX":                             {"untyped int", constant.MakeInt64(1)},
			"AF_UNSPEC":                           {"untyped int", constant.MakeInt64(0)},
			"AI_CANONNAME":                        {"untyped int", constant.MakeInt64(2)},
			"AI_NUMERICHOST":                      {"untyped int", constant.MakeInt64(4)},
			"AI_PASSIVE":                          {"untyped int", constant.MakeInt64(1)},
			"APPLICATION_ERROR":                   {"untyped int", constant.MakeInt64(536870912)},
			"AUTHTYPE_CLIENT":                     {"untyped int", constant.MakeInt64(1)},
			"AUTHTYPE_SERVER":                     {"untyped int", constant.MakeInt64(2)},
			"BASE_PROTOCOL":                       {"untyped int", constant.MakeInt64(1)},
			"CERT_CHAIN_POLICY_AUTHENTICODE":      {"untyped int", constant.MakeInt64(2)},
			"CERT_CHAIN_POLICY_AUTHENTICODE_TS":   {"untyped int", constant.MakeInt64(3)},
			"CERT_CHAIN_POLICY_BASE":              {"untyped int", constant.MakeInt64(1)},
			"CERT_CHAIN_POLICY_BASIC_CONSTRAINTS": {"untyped int", constant.MakeInt64(5)},
			"CERT_CHAIN_POLICY_EV":                {"untyped int", constant.MakeInt64(8)},
			"CERT_CHAIN_POLICY_MICROSOFT_ROOT":    {"untyped int", constant.MakeInt64(7)},
			"CERT_CHAIN_POLICY_NT_AUTH":           {"untyped int", constant.MakeInt64(6)},
			"CERT_CHAIN_POLICY_SSL":               {"untyped int", constant.MakeInt64(4)},
			"CERT_E_CN_NO_MATCH":                  {"untyped int", constant.MakeInt64(2148204815)},
			"CERT_E_EXPIRED":                      {"untyped int", constant.MakeInt64(2148204801)},
			"CERT_E_PURPOSE":                      {"untyped int", constant.MakeInt64(2148204806)},
			"CERT_E_ROLE":                         {"untyped int", constant.MakeInt64(2148204803)},
			"CERT_E_UNTRUSTEDROOT":                {"untyped int", constant.MakeInt64(2148204809)},
			"CERT_STORE_ADD_ALWAYS":               {"untyped int", constant.MakeInt64(4)},
			"CERT_STORE_DEFER_CLOSE_UNTIL_LAST_FREE_FLAG":  {"untyped int", constant.MakeInt64(4)},
			"CERT_STORE_PROV_MEMORY":                       {"untyped int", constant.MakeInt64(2)},
			"CERT_TRUST_HAS_EXCLUDED_NAME_CONSTRAINT":      {"untyped int", constant.MakeInt64(32768)},
			"CERT_TRUST_HAS_NOT_DEFINED_NAME_CONSTRAINT":   {"untyped int", constant.MakeInt64(8192)},
			"CERT_TRUST_HAS_NOT_PERMITTED_NAME_CONSTRAINT": {"untyped int", constant.MakeInt64(16384)},
			"CERT_TRUST_HAS_NOT_SUPPORTED_CRITICAL_EXT":    {"untyped int", constant.MakeInt64(134217728)},
			"CERT_TRUST_HAS_NOT_SUPPORTED_NAME_CONSTRAINT": {"untyped int", constant.MakeInt64(4096)},
			"CERT_TRUST_INVALID_BASIC_CONSTRAINTS":         {"untyped int", constant.MakeInt64(1024)},
			"CERT_TRUST_INVALID_EXTENSION":                 {"untyped int", constant.MakeInt64(256)},
			"CERT_TRUST_INVALID_NAME_CONSTRAINTS":          {"untyped int", constant.MakeInt64(2048)},
			"CERT_TRUST_INVALID_POLICY_CONSTRAINTS":        {"untyped int", constant.MakeInt64(512)},
			"CERT_TRUST_IS_CYCLIC":                         {"untyped int", constant.MakeInt64(128)},
			"CERT_TRUST_IS_EXPLICIT_DISTRUST":              {"untyped int", constant.MakeInt64(67108864)},
			"CERT_TRUST_IS_NOT_SIGNATURE_VALID":            {"untyped int", constant.MakeInt64(8)},
			"CERT_TRUST_IS_NOT_TIME_VALID":                 {"untyped int", constant.MakeInt64(1)},
			"CERT_TRUST_IS_NOT_VALID_FOR_USAGE":            {"untyped int", constant.MakeInt64(16)},
			"CERT_TRUST_IS_OFFLINE_REVOCATION":             {"untyped int", constant.MakeInt64(16777216)},
			"CERT_TRUST_IS_REVOKED":                        {"untyped int", constant.MakeInt64(4)},
			"CERT_TRUST_IS_UNTRUSTED_ROOT":                 {"untyped int", constant.MakeInt64(32)},
			"CERT_TRUST_NO_ERROR":                          {"untyped int", constant.MakeInt64(0)},
			"CERT_TRUST_NO_ISSUANCE_CHAIN_POLICY":          {"untyped int", constant.MakeInt64(33554432)},
			"CERT_TRUST_REVOCATION_STATUS_UNKNOWN":         {"untyped int", constant.MakeInt64(64)},
			"CREATE_ALWAYS":                                {"untyped int", constant.MakeInt64(2)},
			"CREATE_NEW":                                   {"untyped int", constant.MakeInt64(1)},
			"CREATE_NEW_PROCESS_GROUP":                     {"untyped int", constant.MakeInt64(512)},
			"CREATE_UNICODE_ENVIRONMENT":                   {"untyped int", constant.MakeInt64(1024)},
			"CRYPT_DEFAULT_CONTAINER_OPTIONAL":             {"untyped int", constant.MakeInt64(128)},
			"CRYPT_DELETEKEYSET":                           {"untyped int", constant.MakeInt64(16)},
			"CRYPT_MACHINE_KEYSET":                         {"untyped int", constant.MakeInt64(32)},
			"CRYPT_NEWKEYSET":                              {"untyped int", constant.MakeInt64(8)},
			"CRYPT_SILENT":                                 {"untyped int", constant.MakeInt64(64)},
			"CRYPT_VERIFYCONTEXT":                          {"untyped int", constant.MakeInt64(4026531840)},
			"CTRL_BREAK_EVENT":                             {"untyped int", constant.MakeInt64(1)},
			"CTRL_CLOSE_EVENT":                             {"untyped int", constant.MakeInt64(2)},
			"CTRL_C_EVENT":                                 {"untyped int", constant.MakeInt64(0)},
			"CTRL_LOGOFF_EVENT":                            {"untyped int", constant.MakeInt64(5)},
			"CTRL_SHUTDOWN_EVENT":                          {"untyped int", constant.MakeInt64(6)},
			"DNS_INFO_NO_RECORDS":                          {"untyped int", constant.MakeInt64(9501)},
			"DNS_TYPE_A":                                   {"untyped int", constant.MakeInt64(1)},
			"DNS_TYPE_A6":                                  {"untyped int", constant.MakeInt64(38)},
			"DNS_TYPE_AAAA":                                {"untyped int", constant.MakeInt64(28)},
			"DNS_TYPE_ADDRS":                               {"untyped int", constant.MakeInt64(248)},
			"DNS_TYPE_AFSDB":                               {"untyped int", constant.MakeInt64(18)},
			"DNS_TYPE_ALL":                                 {"untyped int", constant.MakeInt64(255)},
			"DNS_TYPE_ANY":                                 {"untyped int", constant.MakeInt64(255)},
			"DNS_TYPE_ATMA":                                {"untyped int", constant.MakeInt64(34)},
			"DNS_TYPE_AXFR":                                {"untyped int", constant.MakeInt64(252)},
			"DNS_TYPE_CERT":                                {"untyped int", constant.MakeInt64(37)},
			"DNS_TYPE_CNAME":                               {"untyped int", constant.MakeInt64(5)},
			"DNS_TYPE_DHCID":                               {"untyped int", constant.MakeInt64(49)},
			"DNS_TYPE_DNAME":                               {"untyped int", constant.MakeInt64(39)},
			"DNS_TYPE_DNSKEY":                              {"untyped int", constant.MakeInt64(48)},
			"DNS_TYPE_DS":                                  {"untyped int", constant.MakeInt64(43)},
			"DNS_TYPE_EID":                                 {"untyped int", constant.MakeInt64(31)},
			"DNS_TYPE_GID":                                 {"untyped int", constant.MakeInt64(102)},
			"DNS_TYPE_GPOS":                                {"untyped int", constant.MakeInt64(27)},
			"DNS_TYPE_HINFO":                               {"untyped int", constant.MakeInt64(13)},
			"DNS_TYPE_ISDN":                                {"untyped int", constant.MakeInt64(20)},
			"DNS_TYPE_IXFR":                                {"untyped int", constant.MakeInt64(251)},
			"DNS_TYPE_KEY":                                 {"untyped int", constant.MakeInt64(25)},
			"DNS_TYPE_KX":                                  {"untyped int", constant.MakeInt64(36)},
			"DNS_TYPE_LOC":                                 {"untyped int", constant.MakeInt64(29)},
			"DNS_TYPE_MAILA":                               {"untyped int", constant.MakeInt64(254)},
			"DNS_TYPE_MAILB":                               {"untyped int", constant.MakeInt64(253)},
			"DNS_TYPE_MB":                                  {"untyped int", constant.MakeInt64(7)},
			"DNS_TYPE_MD":                                  {"untyped int", constant.MakeInt64(3)},
			"DNS_TYPE_MF":                                  {"untyped int", constant.MakeInt64(4)},
			"DNS_TYPE_MG":                                  {"untyped int", constant.MakeInt64(8)},
			"DNS_TYPE_MINFO":                               {"untyped int", constant.MakeInt64(14)},
			"DNS_TYPE_MR":                                  {"untyped int", constant.MakeInt64(9)},
			"DNS_TYPE_MX":                                  {"untyped int", constant.MakeInt64(15)},
			"DNS_TYPE_NAPTR":                               {"untyped int", constant.MakeInt64(35)},
			"DNS_TYPE_NBSTAT":                              {"untyped int", constant.MakeInt64(65281)},
			"DNS_TYPE_NIMLOC":                              {"untyped int", constant.MakeInt64(32)},
			"DNS_TYPE_NS":                                  {"untyped int", constant.MakeInt64(2)},
			"DNS_TYPE_NSAP":                                {"untyped int", constant.MakeInt64(22)},
			"DNS_TYPE_NSAPPTR":                             {"untyped int", constant.MakeInt64(23)},
			"DNS_TYPE_NSEC":                                {"untyped int", constant.MakeInt64(47)},
			"DNS_TYPE_NULL":                                {"untyped int", constant.MakeInt64(10)},
			"DNS_TYPE_NXT":                                 {"untyped int", constant.MakeInt64(30)},
			"DNS_TYPE_OPT":                                 {"untyped int", constant.MakeInt64(41)},
			"DNS_TYPE_PTR":                                 {"untyped int", constant.MakeInt64(12)},
			"DNS_TYPE_PX":                                  {"untyped int", constant.MakeInt64(26)},
			"DNS_TYPE_RP":                                  {"untyped int", constant.MakeInt64(17)},
			"DNS_TYPE_RRSIG":                               {"untyped int", constant.MakeInt64(46)},
			"DNS_TYPE_RT":                                  {"untyped int", constant.MakeInt64(21)},
			"DNS_TYPE_SIG":                                 {"untyped int", constant.MakeInt64(24)},
			"DNS_TYPE_SINK":                                {"untyped int", constant.MakeInt64(40)},
			"DNS_TYPE_SOA":                                 {"untyped int", constant.MakeInt64(6)},
			"DNS_TYPE_SRV":                                 {"untyped int", constant.MakeInt64(33)},
			"DNS_TYPE_TEXT":                                {"untyped int", constant.MakeInt64(16)},
			"DNS_TYPE_TKEY":                                {"untyped int", constant.MakeInt64(249)},
			"DNS_TYPE_TSIG":                                {"untyped int", constant.MakeInt64(250)},
			"DNS_TYPE_UID":                                 {"untyped int", constant.MakeInt64(101)},
			"DNS_TYPE_UINFO":                               {"untyped int", constant.MakeInt64(100)},
			"DNS_TYPE_UNSPEC":                              {"untyped int", constant.MakeInt64(103)},
			"DNS_TYPE_WINS":                                {"untyped int", constant.MakeInt64(65281)},
			"DNS_TYPE_WINSR":                               {"untyped int", constant.MakeInt64(65282)},
			"DNS_TYPE_WKS":                                 {"untyped int", constant.MakeInt64(11)},
			"DNS_TYPE_X25":                                 {"untyped int", constant.MakeInt64(19)},
			"DUPLICATE_CLOSE_SOURCE":                       {"untyped int", constant.MakeInt64(1)},
			"DUPLICATE_SAME_ACCESS":                        {"untyped int", constant.MakeInt64(2)},
			"DnsSectionAdditional":                         {"untyped int", constant.MakeInt64(3)},
			"DnsSectionAnswer":                             {"untyped int", constant.MakeInt64(1)},
			"DnsSectionAuthority":                          {"untyped int", constant.MakeInt64(2)},
			"DnsSectionQuestion":                           {"untyped int", constant.MakeInt64(0)},
			"FILE_ACTION_ADDED":                            {"untyped int", constant.MakeInt64(1)},
			"FILE_ACTION_MODIFIED":                         {"untyped int", constant.MakeInt64(3)},
			"FILE_ACTION_REMOVED":                          {"untyped int", constant.MakeInt64(2)},
			"FILE_ACTION_RENAMED_NEW_NAME":                 {"untyped int", constant.MakeInt64(5)},
			"FILE_ACTION_RENAMED_OLD_NAME":                 {"untyped int", constant.MakeInt64(4)},
			"FILE_APPEND_DATA":                             {"untyped int", constant.MakeInt64(4)},
			"FILE_ATTRIBUTE_ARCHIVE":                       {"untyped int", constant.MakeInt64(32)},
			"FILE_ATTRIBUTE_DIRECTORY":                     {"untyped int", constant.MakeInt64(16)},
			"FILE_ATTRIBUTE_HIDDEN":                        {"untyped int", constant.MakeInt64(2)},
			"FILE_ATTRIBUTE_NORMAL":                        {"untyped int", constant.MakeInt64(128)},
			"FILE_ATTRIBUTE_READONLY":                      {"untyped int", constant.MakeInt64(1)},
			"FILE_ATTRIBUTE_REPARSE_POINT":                 {"untyped int", constant.MakeInt64(1024)},
			"FILE_ATTRIBUTE_SYSTEM":                        {"untyped int", constant.MakeInt64(4)},
			"FILE_BEGIN":                                   {"untyped int", constant.MakeInt64(0)},
			"FILE_CURRENT":                                 {"untyped int", constant.MakeInt64(1)},
			"FILE_END":                                     {"untyped int", constant.MakeInt64(2)},
			"FILE_FLAG_BACKUP_SEMANTICS":                   {"untyped int", constant.MakeInt64(33554432)},
			"FILE_FLAG_OPEN_REPARSE_POINT":                 {"untyped int", constant.MakeInt64(2097152)},
			"FILE_FLAG_OVERLAPPED":                         {"untyped int", constant.MakeInt64(1073741824)},
			"FILE_LIST_DIRECTORY":                          {"untyped int", constant.MakeInt64(1)},
			"FILE_MAP_COPY":                                {"untyped int", constant.MakeInt64(1)},
			"FILE_MAP_EXECUTE":                             {"untyped int", constant.MakeInt64(32)},
			"FILE_MAP_READ":                                {"untyped int", constant.MakeInt64(4)},
			"FILE_MAP_WRITE":                               {"untyped int", constant.MakeInt64(2)},
			"FILE_NOTIFY_CHANGE_ATTRIBUTES":                {"untyped int", constant.MakeInt64(4)},
			"FILE_NOTIFY_CHANGE_CREATION":                  {"untyped int", constant.MakeInt64(64)},
			"FILE_NOTIFY_CHANGE_DIR_NAME":                  {"untyped int", constant.MakeInt64(2)},
			"FILE_NOTIFY_CHANGE_FILE_NAME":                 {"untyped int", constant.MakeInt64(1)},
			"FILE_NOTIFY_CHANGE_LAST_ACCESS":               {"untyped int", constant.MakeInt64(32)},
			"FILE_NOTIFY_CHANGE_LAST_WRITE":                {"untyped int", constant.MakeInt64(16)},
			"FILE_NOTIFY_CHANGE_SIZE":                      {"untyped int", constant.MakeInt64(8)},
			"FILE_SHARE_DELETE":                            {"untyped int", constant.MakeInt64(4)},
			"FILE_SHARE_READ":                              {"untyped int", constant.MakeInt64(1)},
			"FILE_SHARE_WRITE":                             {"untyped int", constant.MakeInt64(2)},
			"FILE_SKIP_COMPLETION_PORT_ON_SUCCESS":         {"untyped int", constant.MakeInt64(1)},
			"FILE_SKIP_SET_EVENT_ON_HANDLE":                {"untyped int", constant.MakeInt64(2)},
			"FILE_TYPE_CHAR":                               {"untyped int", constant.MakeInt64(2)},
			"FILE_TYPE_DISK":                               {"untyped int", constant.MakeInt64(1)},
			"FILE_TYPE_PIPE":                               {"untyped int", constant.MakeInt64(3)},
			"FILE_TYPE_REMOTE":                             {"untyped int", constant.MakeInt64(32768)},
			"FILE_TYPE_UNKNOWN":                            {"untyped int", constant.MakeInt64(0)},
			"FILE_WRITE_ATTRIBUTES":                        {"untyped int", constant.MakeInt64(256)},
			"FORMAT_MESSAGE_ALLOCATE_BUFFER":               {"untyped int", constant.MakeInt64(256)},
			"FORMAT_MESSAGE_ARGUMENT_ARRAY":                {"untyped int", constant.MakeInt64(8192)},
			"FORMAT_MESSAGE_FROM_HMODULE":                  {"untyped int", constant.MakeInt64(2048)},
			"FORMAT_MESSAGE_FROM_STRING":                   {"untyped int", constant.MakeInt64(1024)},
			"FORMAT_MESSAGE_FROM_SYSTEM":                   {"untyped int", constant.MakeInt64(4096)},
			"FORMAT_MESSAGE_IGNORE_INSERTS":                {"untyped int", constant.MakeInt64(512)},
			"FORMAT_MESSAGE_MAX_WIDTH_MASK":                {"untyped int", constant.MakeInt64(255)},
			"FSCTL_GET_REPARSE_POINT":                      {"untyped int", constant.MakeInt64(589992)},
			"GENERIC_ALL":                                  {"untyped int", constant.MakeInt64(268435456)},
			"GENERIC_EXECUTE":                              {"untyped int", constant.MakeInt64(536870912)},
			"GENERIC_READ":                                 {"untyped int", constant.MakeInt64(2147483648)},
			"GENERIC_WRITE":                                {"untyped int", constant.MakeInt64(1073741824)},
			"GetFileExInfoStandard":                        {"untyped int", constant.MakeInt64(0)},
			"GetFileExMaxInfoLevel":                        {"untyped int", constant.MakeInt64(1)},
			"HANDLE_FLAG_INHERIT":                          {"untyped int", constant.MakeInt64(1)},
			"HKEY_CLASSES_ROOT":                            {"untyped int", constant.MakeInt64(2147483648)},
			"HKEY_CURRENT_CONFIG":                          {"untyped int", constant.MakeInt64(2147483653)},
			"HKEY_CURRENT_USER":                            {"untyped int", constant.MakeInt64(2147483649)},
			"HKEY_DYN_DATA":                                {"untyped int", constant.MakeInt64(2147483654)},
			"HKEY_LOCAL_MACHINE":                           {"untyped int", constant.MakeInt64(2147483650)},
			"HKEY_PERFORMANCE_DATA":                        {"untyped int", constant.MakeInt64(2147483652)},
			"HKEY_USERS":                                   {"untyped int", constant.MakeInt64(2147483651)},
			"IFF_BROADCAST":                                {"untyped int", constant.MakeInt64(2)},
			"IFF_LOOPBACK":                                 {"untyped int", constant.MakeInt64(4)},
			"IFF_MULTICAST":                                {"untyped int", constant.MakeInt64(16)},
			"IFF_POINTTOPOINT":                             {"untyped int", constant.MakeInt64(8)},
			"IFF_UP":                                       {"untyped int", constant.MakeInt64(1)},
			"IGNORE":                                       {"untyped int", constant.MakeInt64(0)},
			"INFINITE":                                     {"untyped int", constant.MakeInt64(4294967295)},
			"INVALID_FILE_ATTRIBUTES":                      {"untyped int", constant.MakeInt64(4294967295)},
			"IOC_IN":                                       {"untyped int", constant.MakeInt64(2147483648)},
			"IOC_INOUT":                                    {"untyped int", constant.MakeInt64(3221225472)},
			"IOC_OUT":                                      {"untyped int", constant.MakeInt64(1073741824)},
			"IOC_VENDOR":                                   {"untyped int", constant.MakeInt64(402653184)},
			"IOC_WS2":                                      {"untyped int", constant.MakeInt64(134217728)},
			"IO_REPARSE_TAG_SYMLINK":                       {"untyped int", constant.MakeInt64(2684354572)},
			"IPPROTO_IP":                                   {"untyped int", constant.MakeInt64(0)},
			"IPPROTO_IPV6":                                 {"untyped int", constant.MakeInt64(41)},
			"IPPROTO_TCP":                                  {"untyped int", constant.MakeInt64(6)},
			"IPPROTO_UDP":                                  {"untyped int", constant.MakeInt64(17)},
			"IPV6_JOIN_GROUP":                              {"untyped int", constant.MakeInt64(12)},
			"IPV6_LEAVE_GROUP":                             {"untyped int", constant.MakeInt64(13)},
			"IPV6_MULTICAST_HOPS":                          {"untyped int", constant.MakeInt64(10)},
			"IPV6_MULTICAST_IF":                            {"untyped int", constant.MakeInt64(9)},
			"IPV6_MULTICAST_LOOP":                          {"untyped int", constant.MakeInt64(11)},
			"IPV6_UNICAST_HOPS":                            {"untyped int", constant.MakeInt64(4)},
			"IPV6_V6ONLY":                                  {"untyped int", constant.MakeInt64(27)},
			"IP_ADD_MEMBERSHIP":                            {"untyped int", constant.MakeInt64(12)},
			"IP_DROP_MEMBERSHIP":                           {"untyped int", constant.MakeInt64(13)},
			"IP_MULTICAST_IF":                              {"untyped int", constant.MakeInt64(9)},
			"IP_MULTICAST_LOOP":                            {"untyped int", constant.MakeInt64(11)},
			"IP_MULTICAST_TTL":                             {"untyped int", constant.MakeInt64(10)},
			"IP_TOS":                                       {"untyped int", constant.MakeInt64(3)},
			"IP_TTL":                                       {"untyped int", constant.MakeInt64(4)},
			"ImplementsGetwd":                              {"untyped bool", constant.MakeBool(true)},
			"KEY_ALL_ACCESS":                               {"untyped int", constant.MakeInt64(983103)},
			"KEY_CREATE_LINK":                              {"untyped int", constant.MakeInt64(32)},
			"KEY_CREATE_SUB_KEY":                           {"untyped int", constant.MakeInt64(4)},
			"KEY_ENUMERATE_SUB_KEYS":                       {"untyped int", constant.MakeInt64(8)},
			"KEY_EXECUTE":                                  {"untyped int", constant.MakeInt64(131097)},
			"KEY_NOTIFY":                                   {"untyped int", constant.MakeInt64(16)},
			"KEY_QUERY_VALUE":                              {"untyped int", constant.MakeInt64(1)},
			"KEY_READ":                                     {"untyped int", constant.MakeInt64(131097)},
			"KEY_SET_VALUE":                                {"untyped int", constant.MakeInt64(2)},
			"KEY_WOW64_32KEY":                              {"untyped int", constant.MakeInt64(512)},
			"KEY_WOW64_64KEY":                              {"untyped int", constant.MakeInt64(256)},
			"KEY_WRITE":                                    {"untyped int", constant.MakeInt64(131078)},
			"LANG_ENGLISH":                                 {"untyped int", constant.MakeInt64(9)},
			"LAYERED_PROTOCOL":                             {"untyped int", constant.MakeInt64(0)},
			"MAXIMUM_REPARSE_DATA_BUFFER_SIZE":             {"untyped int", constant.MakeInt64(16384)},
			"MAXLEN_IFDESCR":                               {"untyped int", constant.MakeInt64(256)},
			"MAXLEN_PHYSADDR":                              {"untyped int", constant.MakeInt64(8)},
			"MAX_ADAPTER_ADDRESS_LENGTH":                   {"untyped int", constant.MakeInt64(8)},
			"MAX_ADAPTER_DESCRIPTION_LENGTH":               {"untyped int", constant.MakeInt64(128)},
			"MAX_ADAPTER_NAME_LENGTH":                      {"untyped int", constant.MakeInt64(256)},
			"MAX_COMPUTERNAME_LENGTH":                      {"untyped int", constant.MakeInt64(15)},
			"MAX_INTERFACE_NAME_LEN":                       {"untyped int", constant.MakeInt64(256)},
			"MAX_LONG_PATH":                                {"untyped int", constant.MakeInt64(32768)},
			"MAX_PATH":                                     {"untyped int", constant.MakeInt64(260)},
			"MAX_PROTOCOL_CHAIN":                           {"untyped int", constant.MakeInt64(7)},
			"MaxTokenInfoClass":                            {"untyped int", constant.MakeInt64(29)},
			"NameCanonical":                                {"untyped int", constant.MakeInt64(7)},
			"NameCanonicalEx":                              {"untyped int", constant.MakeInt64(9)},
			"NameDisplay":                                  {"untyped int", constant.MakeInt64(3)},
			"NameDnsDomain":                                {"untyped int", constant.MakeInt64(12)},
			"NameFullyQualifiedDN":                         {"untyped int", constant.MakeInt64(1)},
			"NameSamCompatible":                            {"untyped int", constant.MakeInt64(2)},
			"NameServicePrincipal":                         {"untyped int", constant.MakeInt64(10)},
			"NameUniqueId":                                 {"untyped int", constant.MakeInt64(6)},
			"NameUnknown":                                  {"untyped int", constant.MakeInt64(0)},
			"NameUserPrincipal":                            {"untyped int", constant.MakeInt64(8)},
			"NetSetupDomainName":                           {"untyped int", constant.MakeInt64(3)},
			"NetSetupUnjoined":                             {"untyped int", constant.MakeInt64(1)},
			"NetSetupUnknownStatus":                        {"untyped int", constant.MakeInt64(0)},
			"NetSetupWorkgroupName":                        {"untyped int", constant.MakeInt64(2)},
			"OPEN_ALWAYS":                                  {"untyped int", constant.MakeInt64(4)},
			"OPEN_EXISTING":                                {"untyped int", constant.MakeInt64(3)},
			"O_APPEND":                                     {"untyped int", constant.MakeInt64(1024)},
			"O_ASYNC":                                      {"untyped int", constant.MakeInt64(8192)},
			"O_CLOEXEC":                                    {"untyped int", constant.MakeInt64(524288)},
			"O_CREAT":                                      {"untyped int", constant.MakeInt64(64)},
			"O_EXCL":                                       {"untyped int", constant.MakeInt64(128)},
			"O_NOCTTY":                                     {"untyped int", constant.MakeInt64(256)},
			"O_NONBLOCK":                                   {"untyped int", constant.MakeInt64(2048)},
			"O_RDONLY":                                     {"untyped int", constant.MakeInt64(0)},
			"O_RDWR":                                       {"untyped int", constant.MakeInt64(2)},
			"O_SYNC":                                       {"untyped int", constant.MakeInt64(4096)},
			"O_TRUNC":                                      {"untyped int", constant.MakeInt64(512)},
			"O_WRONLY":                                     {"untyped int", constant.MakeInt64(1)},
			"PAGE_EXECUTE_READ":                            {"untyped int", constant.MakeInt64(32)},
			"PAGE_EXECUTE_READWRITE":                       {"untyped int", constant.MakeInt64(64)},
			"PAGE_EXECUTE_WRITECOPY":                       {"untyped int", constant.MakeInt64(128)},
			"PAGE_READONLY":                                {"untyped int", constant.MakeInt64(2)},
			"PAGE_READWRITE":                               {"untyped int", constant.MakeInt64(4)},
			"PAGE_WRITECOPY":                               {"untyped int", constant.MakeInt64(8)},
			"PFL_HIDDEN":                                   {"untyped int", constant.MakeInt64(4)},
			"PFL_MATCHES_PROTOCOL_ZERO":                    {"untyped int", constant.MakeInt64(8)},
			"PFL_MULTIPLE_PROTO_ENTRIES":                   {"untyped int", constant.MakeInt64(1)},
			"PFL_NETWORKDIRECT_PROVIDER":                   {"untyped int", constant.MakeInt64(16)},
			"PFL_RECOMMENDED_PROTO_ENTRY":                  {"untyped int", constant.MakeInt64(2)},
			"PKCS_7_ASN_ENCODING":                          {"untyped int", constant.MakeInt64(65536)},
			"PROCESS_QUERY_INFORMATION":                    {"untyped int", constant.MakeInt64(1024)},
			"PROCESS_TERMINATE":                            {"untyped int", constant.MakeInt64(1)},
			"PROV_DH_SCHANNEL":                             {"untyped int", constant.MakeInt64(18)},
			"PROV_DSS":                                     {"untyped int", constant.MakeInt64(3)},
			"PROV_DSS_DH":                                  {"untyped int", constant.MakeInt64(13)},
			"PROV_EC_ECDSA_FULL":                           {"untyped int", constant.MakeInt64(16)},
			"PROV_EC_ECDSA_SIG":                            {"untyped int", constant.MakeInt64(14)},
			"PROV_EC_ECNRA_FULL":                           {"untyped int", constant.MakeInt64(17)},
			"PROV_EC_ECNRA_SIG":                            {"untyped int", constant.MakeInt64(15)},
			"PROV_FORTEZZA":                                {"untyped int", constant.MakeInt64(4)},
			"PROV_INTEL_SEC":                               {"untyped int", constant.MakeInt64(22)},
			"PROV_MS_EXCHANGE":                             {"untyped int", constant.MakeInt64(5)},
			"PROV_REPLACE_OWF":                             {"untyped int", constant.MakeInt64(23)},
			"PROV_RNG":                                     {"untyped int", constant.MakeInt64(21)},
			"PROV_RSA_AES":                                 {"untyped int", constant.MakeInt64(24)},
			"PROV_RSA_FULL":                                {"untyped int", constant.MakeInt64(1)},
			"PROV_RSA_SCHANNEL":                            {"untyped int", constant.MakeInt64(12)},
			"PROV_RSA_SIG":                                 {"untyped int", constant.MakeInt64(2)},
			"PROV_SPYRUS_LYNKS":                            {"untyped int", constant.MakeInt64(20)},
			"PROV_SSL":                                     {"untyped int", constant.MakeInt64(6)},
			"REG_BINARY":                                   {"untyped int", constant.MakeInt64(3)},
			"REG_DWORD":                                    {"untyped int", constant.MakeInt64(4)},
			"REG_DWORD_BIG_ENDIAN":                         {"untyped int", constant.MakeInt64(5)},
			"REG_DWORD_LITTLE_ENDIAN":                      {"untyped int", constant.MakeInt64(4)},
			"REG_EXPAND_SZ":                                {"untyped int", constant.MakeInt64(2)},
			"REG_FULL_RESOURCE_DESCRIPTOR":                 {"untyped int", constant.MakeInt64(9)},
			"REG_LINK":                                     {"untyped int", constant.MakeInt64(6)},
			"REG_MULTI_SZ":                                 {"untyped int", constant.MakeInt64(7)},
			"REG_NONE":                                     {"untyped int", constant.MakeInt64(0)},
			"REG_QWORD":                                    {"untyped int", constant.MakeInt64(11)},
			"REG_QWORD_LITTLE_ENDIAN":                      {"untyped int", constant.MakeInt64(11)},
			"REG_RESOURCE_LIST":                            {"untyped int", constant.MakeInt64(8)},
			"REG_RESOURCE_REQUIREMENTS_LIST":               {"untyped int", constant.MakeInt64(10)},
			"REG_SZ":                                       {"untyped int", constant.MakeInt64(1)},
			"SHUT_RD":                                      {"untyped int", constant.MakeInt64(0)},
			"SHUT_RDWR":                                    {"untyped int", constant.MakeInt64(2)},
			"SHUT_WR":                                      {"untyped int", constant.MakeInt64(1)},
			"SIO_GET_EXTENSION_FUNCTION_POINTER":           {"untyped int", constant.MakeInt64(3355443206)},
			"SIO_GET_INTERFACE_LIST":                       {"untyped int", constant.MakeInt64(1074033791)},
			"SIO_KEEPALIVE_VALS":                           {"untyped int", constant.MakeInt64(2550136836)},
			"SIO_UDP_CONNRESET":                            {"untyped int", constant.MakeInt64(2550136844)},
			"SOCK_DGRAM":                                   {"untyped int", constant.MakeInt64(2)},
			"SOCK_RAW":                                     {"untyped int", constant.MakeInt64(3)},
			"SOCK_SEQPACKET":                               {"untyped int", constant.MakeInt64(5)},
			"SOCK_STREAM":                                  {"untyped int", constant.MakeInt64(1)},
			"SOL_SOCKET":                                   {"untyped int", constant.MakeInt64(65535)},
			"SOMAXCONN":                                    {"untyped int", constant.MakeInt64(2147483647)},
			"SO_BROADCAST":                                 {"untyped int", constant.MakeInt64(32)},
			"SO_DONTROUTE":                                 {"untyped int", constant.MakeInt64(16)},
			"SO_KEEPALIVE":                                 {"untyped int", constant.MakeInt64(8)},
			"SO_LINGER":                                    {"untyped int", constant.MakeInt64(128)},
			"SO_RCVBUF":                                    {"untyped int", constant.MakeInt64(4098)},
			"SO_REUSEADDR":                                 {"untyped int", constant.MakeInt64(4)},
			"SO_SNDBUF":                                    {"untyped int", constant.MakeInt64(4097)},
			"SO_UPDATE_ACCEPT_CONTEXT":                     {"untyped int", constant.MakeInt64(28683)},
			"SO_UPDATE_CONNECT_CONTEXT":                    {"untyped int", constant.MakeInt64(28688)},
			"STANDARD_RIGHTS_ALL":                          {"untyped int", constant.MakeInt64(2031616)},
			"STANDARD_RIGHTS_EXECUTE":                      {"untyped int", constant.MakeInt64(131072)},
			"STANDARD_RIGHTS_READ":                         {"untyped int", constant.MakeInt64(131072)},
			"STANDARD_RIGHTS_REQUIRED":                     {"untyped int", constant.MakeInt64(983040)},
			"STANDARD_RIGHTS_WRITE":                        {"untyped int", constant.MakeInt64(131072)},
			"STARTF_USESHOWWINDOW":                         {"untyped int", constant.MakeInt64(1)},
			"STARTF_USESTDHANDLES":                         {"untyped int", constant.MakeInt64(256)},
			"STD_ERROR_HANDLE":                             {"untyped int", constant.MakeInt64(-12)},
			"STD_INPUT_HANDLE":                             {"untyped int", constant.MakeInt64(-10)},
			"STD_OUTPUT_HANDLE":                            {"untyped int", constant.MakeInt64(-11)},
			"SUBLANG_ENGLISH_US":                           {"untyped int", constant.MakeInt64(1)},
			"SW_FORCEMINIMIZE":                             {"untyped int", constant.MakeInt64(11)},
			"SW_HIDE":                                      {"untyped int", constant.MakeInt64(0)},
			"SW_MAXIMIZE":                                  {"untyped int", constant.MakeInt64(3)},
			"SW_MINIMIZE":                                  {"untyped int", constant.MakeInt64(6)},
			"SW_NORMAL":                                    {"untyped int", constant.MakeInt64(1)},
			"SW_RESTORE":                                   {"untyped int", constant.MakeInt64(9)},
			"SW_SHOW":                                      {"untyped int", constant.MakeInt64(5)},
			"SW_SHOWDEFAULT":                               {"untyped int", constant.MakeInt64(10)},
			"SW_SHOWMAXIMIZED":                             {"untyped int", constant.MakeInt64(3)},
			"SW_SHOWMINIMIZED":                             {"untyped int", constant.MakeInt64(2)},
			"SW_SHOWMINNOACTIVE":                           {"untyped int", constant.MakeInt64(7)},
			"SW_SHOWNA":                                    {"untyped int", constant.MakeInt64(8)},
			"SW_SHOWNOACTIVATE":                            {"untyped int", constant.MakeInt64(4)},
			"SW_SHOWNORMAL":                                {"untyped int", constant.MakeInt64(1)},
			"SYMBOLIC_LINK_FLAG_DIRECTORY":                 {"untyped int", constant.MakeInt64(1)},
			"SYNCHRONIZE":                                  {"untyped int", constant.MakeInt64(1048576)},
			"S_IFBLK":                                      {"untyped int", constant.MakeInt64(24576)},
			"S_IFCHR":                                      {"untyped int", constant.MakeInt64(8192)},
			"S_IFDIR":                                      {"untyped int", constant.MakeInt64(16384)},
			"S_IFIFO":                                      {"untyped int", constant.MakeInt64(4096)},
			"S_IFLNK":                                      {"untyped int", constant.MakeInt64(40960)},
			"S_IFMT":                                       {"untyped int", constant.MakeInt64(126976)},
			"S_IFREG":                                      {"untyped int", constant.MakeInt64(32768)},
			"S_IFSOCK":                                     {"untyped int", constant.MakeInt64(49152)},
			"S_IRUSR":                                      {"untyped int", constant.MakeInt64(256)},
			"S_ISGID":                                      {"untyped int", constant.MakeInt64(1024)},
			"S_ISUID":                                      {"untyped int", constant.MakeInt64(2048)},
			"S_ISVTX":                                      {"untyped int", constant.MakeInt64(512)},
			"S_IWRITE":                                     {"untyped int", constant.MakeInt64(128)},
			"S_IWUSR":                                      {"untyped int", constant.MakeInt64(128)},
			"S_IXUSR":                                      {"untyped int", constant.MakeInt64(64)},
			"SidTypeAlias":                                 {"untyped int", constant.MakeInt64(4)},
			"SidTypeComputer":                              {"untyped int", constant.MakeInt64(9)},
			"SidTypeDeletedAccount":                        {"untyped int", constant.MakeInt64(6)},
			"SidTypeDomain":                                {"untyped int", constant.MakeInt64(3)},
			"SidTypeGroup":                                 {"untyped int", constant.MakeInt64(2)},
			"SidTypeInvalid":                               {"untyped int", constant.MakeInt64(7)},
			"SidTypeLabel":                                 {"untyped int", constant.MakeInt64(10)},
			"SidTypeUnknown":                               {"untyped int", constant.MakeInt64(8)},
			"SidTypeUser":                                  {"untyped int", constant.MakeInt64(1)},
			"SidTypeWellKnownGroup":                        {"untyped int", constant.MakeInt64(5)},
			"TCP_NODELAY":                                  {"untyped int", constant.MakeInt64(1)},
			"TF_DISCONNECT":                                {"untyped int", constant.MakeInt64(1)},
			"TF_REUSE_SOCKET":                              {"untyped int", constant.MakeInt64(2)},
			"TF_USE_DEFAULT_WORKER":                        {"untyped int", constant.MakeInt64(0)},
			"TF_USE_KERNEL_APC":                            {"untyped int", constant.MakeInt64(32)},
			"TF_USE_SYSTEM_THREAD":                         {"untyped int", constant.MakeInt64(16)},
			"TF_WRITE_BEHIND":                              {"untyped int", constant.MakeInt64(4)},
			"TH32CS_INHERIT":                               {"untyped int", constant.MakeInt64(2147483648)},
			"TH32CS_SNAPALL":                               {"untyped int", constant.MakeInt64(15)},
			"TH32CS_SNAPHEAPLIST":                          {"untyped int", constant.MakeInt64(1)},
			"TH32CS_SNAPMODULE":                            {"untyped int", constant.MakeInt64(8)},
			"TH32CS_SNAPMODULE32":                          {"untyped int", constant.MakeInt64(16)},
			"TH32CS_SNAPPROCESS":                           {"untyped int", constant.MakeInt64(2)},
			"TH32CS_SNAPTHREAD":                            {"untyped int", constant.MakeInt64(4)},
			"TIME_ZONE_ID_DAYLIGHT":                        {"untyped int", constant.MakeInt64(2)},
			"TIME_ZONE_ID_STANDARD":                        {"untyped int", constant.MakeInt64(1)},
			"TIME_ZONE_ID_UNKNOWN":                         {"untyped int", constant.MakeInt64(0)},
			"TOKEN_ADJUST_DEFAULT":                         {"untyped int", constant.MakeInt64(128)},
			"TOKEN_ADJUST_GROUPS":                          {"untyped int", constant.MakeInt64(64)},
			"TOKEN_ADJUST_PRIVILEGES":                      {"untyped int", constant.MakeInt64(32)},
			"TOKEN_ADJUST_SESSIONID":                       {"untyped int", constant.MakeInt64(256)},
			"TOKEN_ALL_ACCESS":                             {"untyped int", constant.MakeInt64(983551)},
			"TOKEN_ASSIGN_PRIMARY":                         {"untyped int", constant.MakeInt64(1)},
			"TOKEN_DUPLICATE":                              {"untyped int", constant.MakeInt64(2)},
			"TOKEN_EXECUTE":                                {"untyped int", constant.MakeInt64(131072)},
			"TOKEN_IMPERSONATE":                            {"untyped int", constant.MakeInt64(4)},
			"TOKEN_QUERY":                                  {"untyped int", constant.MakeInt64(8)},
			"TOKEN_QUERY_SOURCE":                           {"untyped int", constant.MakeInt64(16)},
			"TOKEN_READ":                                   {"untyped int", constant.MakeInt64(131080)},
			"TOKEN_WRITE":                                  {"untyped int", constant.MakeInt64(131296)},
			"TRUNCATE_EXISTING":                            {"untyped int", constant.MakeInt64(5)},
			"TokenAccessInformation":                       {"untyped int", constant.MakeInt64(22)},
			"TokenAuditPolicy":                             {"untyped int", constant.MakeInt64(16)},
			"TokenDefaultDacl":                             {"untyped int", constant.MakeInt64(6)},
			"TokenElevation":                               {"untyped int", constant.MakeInt64(20)},
			"TokenElevationType":                           {"untyped int", constant.MakeInt64(18)},
			"TokenGroups":                                  {"untyped int", constant.MakeInt64(2)},
			"TokenGroupsAndPrivileges":                     {"untyped int", constant.MakeInt64(13)},
			"TokenHasRestrictions":                         {"untyped int", constant.MakeInt64(21)},
			"TokenImpersonationLevel":                      {"untyped int", constant.MakeInt64(9)},
			"TokenIntegrityLevel":                          {"untyped int", constant.MakeInt64(25)},
			"TokenLinkedToken":                             {"untyped int", constant.MakeInt64(19)},
			"TokenLogonSid":                                {"untyped int", constant.MakeInt64(28)},
			"TokenMandatoryPolicy":                         {"untyped int", constant.MakeInt64(27)},
			"TokenOrigin":                                  {"untyped int", constant.MakeInt64(17)},
			"TokenOwner":                                   {"untyped int", constant.MakeInt64(4)},
			"TokenPrimaryGroup":                            {"untyped int", constant.MakeInt64(5)},
			"TokenPrivileges":                              {"untyped int", constant.MakeInt64(3)},
			"TokenRestrictedSids":                          {"untyped int", constant.MakeInt64(11)},
			"TokenSandBoxInert":                            {"untyped int", constant.MakeInt64(15)},
			"TokenSessionId":                               {"untyped int", constant.MakeInt64(12)},
			"TokenSessionReference":                        {"untyped int", constant.MakeInt64(14)},
			"TokenSource":                                  {"untyped int", constant.MakeInt64(7)},
			"TokenStatistics":                              {"untyped int", constant.MakeInt64(10)},
			"TokenType":                                    {"untyped int", constant.MakeInt64(8)},
			"TokenUIAccess":                                {"untyped int", constant.MakeInt64(26)},
			"TokenUser":                                    {"untyped int", constant.MakeInt64(1)},
			"TokenVirtualizationAllowed":                   {"untyped int", constant.MakeInt64(23)},
			"TokenVirtualizationEnabled":                   {"untyped int", constant.MakeInt64(24)},
			"UNIX_PATH_MAX":                                {"untyped int", constant.MakeInt64(108)},
			"USAGE_MATCH_TYPE_AND":                         {"untyped int", constant.MakeInt64(0)},
			"USAGE_MATCH_TYPE_OR":                          {"untyped int", constant.MakeInt64(1)},
			"WAIT_ABANDONED":                               {"untyped int", constant.MakeInt64(128)},
			"WAIT_FAILED":                                  {"untyped int", constant.MakeInt64(4294967295)},
			"WAIT_OBJECT_0":                                {"untyped int", constant.MakeInt64(0)},
			"WAIT_TIMEOUT":                                 {"untyped int", constant.MakeInt64(258)},
			"WSADESCRIPTION_LEN":                           {"untyped int", constant.MakeInt64(256)},
			"WSAPROTOCOL_LEN":                              {"untyped int", constant.MakeInt64(255)},
			"WSASYS_STATUS_LEN":                            {"untyped int", constant.MakeInt64(128)},
			"X509_ASN_ENCODING":                            {"untyped int", constant.MakeInt64(1)},
			"XP1_CONNECTIONLESS":                           {"untyped int", constant.MakeInt64(1)},
			"XP1_CONNECT_DATA":                             {"untyped int", constant.MakeInt64(128)},
			"XP1_DISCONNECT_DATA":                          {"untyped int", constant.MakeInt64(256)},
			"XP1_EXPEDITED_DATA":                           {"untyped int", constant.MakeInt64(64)},
			"XP1_GRACEFUL_CLOSE":                           {"untyped int", constant.MakeInt64(32)},
			"XP1_GUARANTEED_DELIVERY":                      {"untyped int", constant.MakeInt64(2)},
			"XP1_GUARANTEED_ORDER":                         {"untyped int", constant.MakeInt64(4)},
			"XP1_IFS_HANDLES":                              {"untyped int", constant.MakeInt64(131072)},
			"XP1_MESSAGE_ORIENTED":                         {"untyped int", constant.MakeInt64(8)},
			"XP1_MULTIPOINT_CONTROL_PLANE":                 {"untyped int", constant.MakeInt64(2048)},
			"XP1_MULTIPOINT_DATA_PLANE":                    {"untyped int", constant.MakeInt64(4096)},
			"XP1_PARTIAL_MESSAGE":                          {"untyped int", constant.MakeInt64(262144)},
			"XP1_PSEUDO_STREAM":                            {"untyped int", constant.MakeInt64(16)},
			"XP1_QOS_SUPPORTED":                            {"untyped int", constant.MakeInt64(8192)},
			"XP1_SAN_SUPPORT_SDP":                          {"untyped int", constant.MakeInt64(524288)},
			"XP1_SUPPORT_BROADCAST":                        {"untyped int", constant.MakeInt64(512)},
			"XP1_SUPPORT_MULTIPOINT":                       {"untyped int", constant.MakeInt64(1024)},
			"XP1_UNI_RECV":                                 {"untyped int", constant.MakeInt64(65536)},
			"XP1_UNI_SEND":                                 {"untyped int", constant.MakeInt64(32768)},
		},
	})
}
