// export by github.com/goplus/interp/cmd/qexp

package syscall

import (
	"syscall"

	"github.com/goplus/interp"
)

func init() {
	interp.RegisterPackage("syscall", extMap_windows_amd64, typList_windows_amd64)
}

var extMap_windows_amd64 = map[string]interface{}{
	"(*syscall.DLL).FindProc":                        (*syscall.DLL).FindProc,
	"(*syscall.DLL).MustFindProc":                    (*syscall.DLL).MustFindProc,
	"(*syscall.DLL).Release":                         (*syscall.DLL).Release,
	"(*syscall.DLLError).Error":                      (*syscall.DLLError).Error,
	"(*syscall.Filetime).Nanoseconds":                (*syscall.Filetime).Nanoseconds,
	"(*syscall.LazyDLL).Handle":                      (*syscall.LazyDLL).Handle,
	"(*syscall.LazyDLL).Load":                        (*syscall.LazyDLL).Load,
	"(*syscall.LazyDLL).NewProc":                     (*syscall.LazyDLL).NewProc,
	"(*syscall.LazyProc).Addr":                       (*syscall.LazyProc).Addr,
	"(*syscall.LazyProc).Call":                       (*syscall.LazyProc).Call,
	"(*syscall.LazyProc).Find":                       (*syscall.LazyProc).Find,
	"(*syscall.Proc).Addr":                           (*syscall.Proc).Addr,
	"(*syscall.Proc).Call":                           (*syscall.Proc).Call,
	"(*syscall.RawSockaddrAny).Sockaddr":             (*syscall.RawSockaddrAny).Sockaddr,
	"(*syscall.SID).Copy":                            (*syscall.SID).Copy,
	"(*syscall.SID).Len":                             (*syscall.SID).Len,
	"(*syscall.SID).LookupAccount":                   (*syscall.SID).LookupAccount,
	"(*syscall.SID).String":                          (*syscall.SID).String,
	"(*syscall.Timeval).Nanoseconds":                 (*syscall.Timeval).Nanoseconds,
	"(syscall.Token).Close":                          (syscall.Token).Close,
	"(syscall.Token).GetTokenPrimaryGroup":           (syscall.Token).GetTokenPrimaryGroup,
	"(syscall.Token).GetTokenUser":                   (syscall.Token).GetTokenUser,
	"(syscall.Token).GetUserProfileDirectory":        (syscall.Token).GetUserProfileDirectory,
	"syscall.AcceptEx":                               syscall.AcceptEx,
	"syscall.CancelIo":                               syscall.CancelIo,
	"syscall.CancelIoEx":                             syscall.CancelIoEx,
	"syscall.CertAddCertificateContextToStore":       syscall.CertAddCertificateContextToStore,
	"syscall.CertCloseStore":                         syscall.CertCloseStore,
	"syscall.CertCreateCertificateContext":           syscall.CertCreateCertificateContext,
	"syscall.CertEnumCertificatesInStore":            syscall.CertEnumCertificatesInStore,
	"syscall.CertFreeCertificateChain":               syscall.CertFreeCertificateChain,
	"syscall.CertFreeCertificateContext":             syscall.CertFreeCertificateContext,
	"syscall.CertGetCertificateChain":                syscall.CertGetCertificateChain,
	"syscall.CertOpenStore":                          syscall.CertOpenStore,
	"syscall.CertOpenSystemStore":                    syscall.CertOpenSystemStore,
	"syscall.CertVerifyCertificateChainPolicy":       syscall.CertVerifyCertificateChainPolicy,
	"syscall.CloseHandle":                            syscall.CloseHandle,
	"syscall.Closesocket":                            syscall.Closesocket,
	"syscall.CommandLineToArgv":                      syscall.CommandLineToArgv,
	"syscall.ComputerName":                           syscall.ComputerName,
	"syscall.ConnectEx":                              syscall.ConnectEx,
	"syscall.ConvertSidToStringSid":                  syscall.ConvertSidToStringSid,
	"syscall.ConvertStringSidToSid":                  syscall.ConvertStringSidToSid,
	"syscall.CopySid":                                syscall.CopySid,
	"syscall.CreateDirectory":                        syscall.CreateDirectory,
	"syscall.CreateFile":                             syscall.CreateFile,
	"syscall.CreateFileMapping":                      syscall.CreateFileMapping,
	"syscall.CreateHardLink":                         syscall.CreateHardLink,
	"syscall.CreateIoCompletionPort":                 syscall.CreateIoCompletionPort,
	"syscall.CreatePipe":                             syscall.CreatePipe,
	"syscall.CreateProcess":                          syscall.CreateProcess,
	"syscall.CreateProcessAsUser":                    syscall.CreateProcessAsUser,
	"syscall.CreateSymbolicLink":                     syscall.CreateSymbolicLink,
	"syscall.CreateToolhelp32Snapshot":               syscall.CreateToolhelp32Snapshot,
	"syscall.CryptAcquireContext":                    syscall.CryptAcquireContext,
	"syscall.CryptGenRandom":                         syscall.CryptGenRandom,
	"syscall.CryptReleaseContext":                    syscall.CryptReleaseContext,
	"syscall.DeleteFile":                             syscall.DeleteFile,
	"syscall.DeviceIoControl":                        syscall.DeviceIoControl,
	"syscall.DnsNameCompare":                         syscall.DnsNameCompare,
	"syscall.DnsQuery":                               syscall.DnsQuery,
	"syscall.DnsRecordListFree":                      syscall.DnsRecordListFree,
	"syscall.DuplicateHandle":                        syscall.DuplicateHandle,
	"syscall.EscapeArg":                              syscall.EscapeArg,
	"syscall.ExitProcess":                            syscall.ExitProcess,
	"syscall.FindClose":                              syscall.FindClose,
	"syscall.FindFirstFile":                          syscall.FindFirstFile,
	"syscall.FindNextFile":                           syscall.FindNextFile,
	"syscall.FlushFileBuffers":                       syscall.FlushFileBuffers,
	"syscall.FlushViewOfFile":                        syscall.FlushViewOfFile,
	"syscall.FormatMessage":                          syscall.FormatMessage,
	"syscall.FreeAddrInfoW":                          syscall.FreeAddrInfoW,
	"syscall.FreeEnvironmentStrings":                 syscall.FreeEnvironmentStrings,
	"syscall.FreeLibrary":                            syscall.FreeLibrary,
	"syscall.FullPath":                               syscall.FullPath,
	"syscall.GetAcceptExSockaddrs":                   syscall.GetAcceptExSockaddrs,
	"syscall.GetAdaptersInfo":                        syscall.GetAdaptersInfo,
	"syscall.GetAddrInfoW":                           syscall.GetAddrInfoW,
	"syscall.GetCommandLine":                         syscall.GetCommandLine,
	"syscall.GetComputerName":                        syscall.GetComputerName,
	"syscall.GetConsoleMode":                         syscall.GetConsoleMode,
	"syscall.GetCurrentDirectory":                    syscall.GetCurrentDirectory,
	"syscall.GetCurrentProcess":                      syscall.GetCurrentProcess,
	"syscall.GetEnvironmentStrings":                  syscall.GetEnvironmentStrings,
	"syscall.GetEnvironmentVariable":                 syscall.GetEnvironmentVariable,
	"syscall.GetExitCodeProcess":                     syscall.GetExitCodeProcess,
	"syscall.GetFileAttributes":                      syscall.GetFileAttributes,
	"syscall.GetFileAttributesEx":                    syscall.GetFileAttributesEx,
	"syscall.GetFileInformationByHandle":             syscall.GetFileInformationByHandle,
	"syscall.GetFileType":                            syscall.GetFileType,
	"syscall.GetFullPathName":                        syscall.GetFullPathName,
	"syscall.GetHostByName":                          syscall.GetHostByName,
	"syscall.GetIfEntry":                             syscall.GetIfEntry,
	"syscall.GetLastError":                           syscall.GetLastError,
	"syscall.GetLengthSid":                           syscall.GetLengthSid,
	"syscall.GetLongPathName":                        syscall.GetLongPathName,
	"syscall.GetProcAddress":                         syscall.GetProcAddress,
	"syscall.GetProcessTimes":                        syscall.GetProcessTimes,
	"syscall.GetProtoByName":                         syscall.GetProtoByName,
	"syscall.GetQueuedCompletionStatus":              syscall.GetQueuedCompletionStatus,
	"syscall.GetServByName":                          syscall.GetServByName,
	"syscall.GetShortPathName":                       syscall.GetShortPathName,
	"syscall.GetStartupInfo":                         syscall.GetStartupInfo,
	"syscall.GetStdHandle":                           syscall.GetStdHandle,
	"syscall.GetSystemTimeAsFileTime":                syscall.GetSystemTimeAsFileTime,
	"syscall.GetTempPath":                            syscall.GetTempPath,
	"syscall.GetTimeZoneInformation":                 syscall.GetTimeZoneInformation,
	"syscall.GetTokenInformation":                    syscall.GetTokenInformation,
	"syscall.GetUserNameEx":                          syscall.GetUserNameEx,
	"syscall.GetUserProfileDirectory":                syscall.GetUserProfileDirectory,
	"syscall.GetVersion":                             syscall.GetVersion,
	"syscall.Getsockopt":                             syscall.Getsockopt,
	"syscall.LoadCancelIoEx":                         syscall.LoadCancelIoEx,
	"syscall.LoadConnectEx":                          syscall.LoadConnectEx,
	"syscall.LoadCreateSymbolicLink":                 syscall.LoadCreateSymbolicLink,
	"syscall.LoadDLL":                                syscall.LoadDLL,
	"syscall.LoadGetAddrInfo":                        syscall.LoadGetAddrInfo,
	"syscall.LoadLibrary":                            syscall.LoadLibrary,
	"syscall.LoadSetFileCompletionNotificationModes": syscall.LoadSetFileCompletionNotificationModes,
	"syscall.LocalFree":                              syscall.LocalFree,
	"syscall.LookupAccountName":                      syscall.LookupAccountName,
	"syscall.LookupAccountSid":                       syscall.LookupAccountSid,
	"syscall.LookupSID":                              syscall.LookupSID,
	"syscall.MapViewOfFile":                          syscall.MapViewOfFile,
	"syscall.MoveFile":                               syscall.MoveFile,
	"syscall.MustLoadDLL":                            syscall.MustLoadDLL,
	"syscall.NetApiBufferFree":                       syscall.NetApiBufferFree,
	"syscall.NetGetJoinInformation":                  syscall.NetGetJoinInformation,
	"syscall.NetUserGetInfo":                         syscall.NetUserGetInfo,
	"syscall.NewCallback":                            syscall.NewCallback,
	"syscall.NewCallbackCDecl":                       syscall.NewCallbackCDecl,
	"syscall.NewLazyDLL":                             syscall.NewLazyDLL,
	"syscall.NsecToFiletime":                         syscall.NsecToFiletime,
	"syscall.Ntohs":                                  syscall.Ntohs,
	"syscall.OID_PKIX_KP_SERVER_AUTH":                &syscall.OID_PKIX_KP_SERVER_AUTH,
	"syscall.OID_SERVER_GATED_CRYPTO":                &syscall.OID_SERVER_GATED_CRYPTO,
	"syscall.OID_SGC_NETSCAPE":                       &syscall.OID_SGC_NETSCAPE,
	"syscall.OpenCurrentProcessToken":                syscall.OpenCurrentProcessToken,
	"syscall.OpenProcess":                            syscall.OpenProcess,
	"syscall.OpenProcessToken":                       syscall.OpenProcessToken,
	"syscall.PostQueuedCompletionStatus":             syscall.PostQueuedCompletionStatus,
	"syscall.Process32First":                         syscall.Process32First,
	"syscall.Process32Next":                          syscall.Process32Next,
	"syscall.ReadConsole":                            syscall.ReadConsole,
	"syscall.ReadDirectoryChanges":                   syscall.ReadDirectoryChanges,
	"syscall.ReadFile":                               syscall.ReadFile,
	"syscall.RegCloseKey":                            syscall.RegCloseKey,
	"syscall.RegEnumKeyEx":                           syscall.RegEnumKeyEx,
	"syscall.RegOpenKeyEx":                           syscall.RegOpenKeyEx,
	"syscall.RegQueryInfoKey":                        syscall.RegQueryInfoKey,
	"syscall.RegQueryValueEx":                        syscall.RegQueryValueEx,
	"syscall.RemoveDirectory":                        syscall.RemoveDirectory,
	"syscall.SetCurrentDirectory":                    syscall.SetCurrentDirectory,
	"syscall.SetEndOfFile":                           syscall.SetEndOfFile,
	"syscall.SetEnvironmentVariable":                 syscall.SetEnvironmentVariable,
	"syscall.SetFileAttributes":                      syscall.SetFileAttributes,
	"syscall.SetFileCompletionNotificationModes":     syscall.SetFileCompletionNotificationModes,
	"syscall.SetFilePointer":                         syscall.SetFilePointer,
	"syscall.SetFileTime":                            syscall.SetFileTime,
	"syscall.SetHandleInformation":                   syscall.SetHandleInformation,
	"syscall.Setsockopt":                             syscall.Setsockopt,
	"syscall.StringToSid":                            syscall.StringToSid,
	"syscall.StringToUTF16":                          syscall.StringToUTF16,
	"syscall.StringToUTF16Ptr":                       syscall.StringToUTF16Ptr,
	"syscall.Syscall12":                              syscall.Syscall12,
	"syscall.Syscall15":                              syscall.Syscall15,
	"syscall.Syscall18":                              syscall.Syscall18,
	"syscall.TerminateProcess":                       syscall.TerminateProcess,
	"syscall.TranslateAccountName":                   syscall.TranslateAccountName,
	"syscall.TranslateName":                          syscall.TranslateName,
	"syscall.TransmitFile":                           syscall.TransmitFile,
	"syscall.UTF16FromString":                        syscall.UTF16FromString,
	"syscall.UTF16PtrFromString":                     syscall.UTF16PtrFromString,
	"syscall.UTF16ToString":                          syscall.UTF16ToString,
	"syscall.UnmapViewOfFile":                        syscall.UnmapViewOfFile,
	"syscall.VirtualLock":                            syscall.VirtualLock,
	"syscall.VirtualUnlock":                          syscall.VirtualUnlock,
	"syscall.WSACleanup":                             syscall.WSACleanup,
	"syscall.WSAEnumProtocols":                       syscall.WSAEnumProtocols,
	"syscall.WSAID_CONNECTEX":                        &syscall.WSAID_CONNECTEX,
	"syscall.WSAIoctl":                               syscall.WSAIoctl,
	"syscall.WSARecv":                                syscall.WSARecv,
	"syscall.WSARecvFrom":                            syscall.WSARecvFrom,
	"syscall.WSASend":                                syscall.WSASend,
	"syscall.WSASendTo":                              syscall.WSASendTo,
	"syscall.WSASendto":                              syscall.WSASendto,
	"syscall.WSAStartup":                             syscall.WSAStartup,
	"syscall.WaitForSingleObject":                    syscall.WaitForSingleObject,
	"syscall.WriteConsole":                           syscall.WriteConsole,
	"syscall.WriteFile":                              syscall.WriteFile,
}

var typList_windows_amd64 = []interface{}{
	(*syscall.AddrinfoW)(nil),
	(*syscall.ByHandleFileInformation)(nil),
	(*syscall.CertChainContext)(nil),
	(*syscall.CertChainElement)(nil),
	(*syscall.CertChainPara)(nil),
	(*syscall.CertChainPolicyPara)(nil),
	(*syscall.CertChainPolicyStatus)(nil),
	(*syscall.CertContext)(nil),
	(*syscall.CertEnhKeyUsage)(nil),
	(*syscall.CertInfo)(nil),
	(*syscall.CertRevocationCrlInfo)(nil),
	(*syscall.CertRevocationInfo)(nil),
	(*syscall.CertSimpleChain)(nil),
	(*syscall.CertTrustListInfo)(nil),
	(*syscall.CertTrustStatus)(nil),
	(*syscall.CertUsageMatch)(nil),
	(*syscall.DLL)(nil),
	(*syscall.DLLError)(nil),
	(*syscall.DNSMXData)(nil),
	(*syscall.DNSPTRData)(nil),
	(*syscall.DNSRecord)(nil),
	(*syscall.DNSSRVData)(nil),
	(*syscall.DNSTXTData)(nil),
	(*syscall.FileNotifyInformation)(nil),
	(*syscall.Filetime)(nil),
	(*syscall.GUID)(nil),
	(*syscall.Handle)(nil),
	(*syscall.Hostent)(nil),
	(*syscall.InterfaceInfo)(nil),
	(*syscall.IpAdapterInfo)(nil),
	(*syscall.IpAddrString)(nil),
	(*syscall.IpAddressString)(nil),
	(*syscall.IpMaskString)(nil),
	(*syscall.LazyDLL)(nil),
	(*syscall.LazyProc)(nil),
	(*syscall.MibIfRow)(nil),
	(*syscall.Overlapped)(nil),
	(*syscall.Pointer)(nil),
	(*syscall.Proc)(nil),
	(*syscall.ProcessEntry32)(nil),
	(*syscall.ProcessInformation)(nil),
	(*syscall.Protoent)(nil),
	(*syscall.SID)(nil),
	(*syscall.SIDAndAttributes)(nil),
	(*syscall.SSLExtraCertChainPolicyPara)(nil),
	(*syscall.SecurityAttributes)(nil),
	(*syscall.Servent)(nil),
	(*syscall.SockaddrGen)(nil),
	(*syscall.StartupInfo)(nil),
	(*syscall.Systemtime)(nil),
	(*syscall.TCPKeepalive)(nil),
	(*syscall.Timezoneinformation)(nil),
	(*syscall.Token)(nil),
	(*syscall.Tokenprimarygroup)(nil),
	(*syscall.Tokenuser)(nil),
	(*syscall.TransmitFileBuffers)(nil),
	(*syscall.UserInfo10)(nil),
	(*syscall.WSABuf)(nil),
	(*syscall.WSAData)(nil),
	(*syscall.WSAProtocolChain)(nil),
	(*syscall.WSAProtocolInfo)(nil),
	(*syscall.Win32FileAttributeData)(nil),
	(*syscall.Win32finddata)(nil),
}
