// export by github.com/goplus/gossa/cmd/qexp

package syscall

import (
	"syscall"

	"github.com/goplus/gossa"
)

func init() {
	gossa.RegisterPackage("syscall", extMap_linux, typList_linux)
}

var extMap_linux = map[string]interface{}{
	"(*syscall.PtraceRegs).PC":      (*syscall.PtraceRegs).PC,
	"(*syscall.PtraceRegs).SetPC":   (*syscall.PtraceRegs).SetPC,
	"syscall.Acct":                  syscall.Acct,
	"syscall.Adjtimex":              syscall.Adjtimex,
	"syscall.AttachLsf":             syscall.AttachLsf,
	"syscall.BindToDevice":          syscall.BindToDevice,
	"syscall.Creat":                 syscall.Creat,
	"syscall.DetachLsf":             syscall.DetachLsf,
	"syscall.Dup3":                  syscall.Dup3,
	"syscall.EpollCreate":           syscall.EpollCreate,
	"syscall.EpollCreate1":          syscall.EpollCreate1,
	"syscall.EpollCtl":              syscall.EpollCtl,
	"syscall.EpollWait":             syscall.EpollWait,
	"syscall.Faccessat":             syscall.Faccessat,
	"syscall.Fallocate":             syscall.Fallocate,
	"syscall.Fchmodat":              syscall.Fchmodat,
	"syscall.Fchownat":              syscall.Fchownat,
	"syscall.Fdatasync":             syscall.Fdatasync,
	"syscall.Futimesat":             syscall.Futimesat,
	"syscall.Getcwd":                syscall.Getcwd,
	"syscall.Getdents":              syscall.Getdents,
	"syscall.GetsockoptUcred":       syscall.GetsockoptUcred,
	"syscall.Gettid":                syscall.Gettid,
	"syscall.Getxattr":              syscall.Getxattr,
	"syscall.InotifyAddWatch":       syscall.InotifyAddWatch,
	"syscall.InotifyInit":           syscall.InotifyInit,
	"syscall.InotifyInit1":          syscall.InotifyInit1,
	"syscall.InotifyRmWatch":        syscall.InotifyRmWatch,
	"syscall.Ioperm":                syscall.Ioperm,
	"syscall.Iopl":                  syscall.Iopl,
	"syscall.Klogctl":               syscall.Klogctl,
	"syscall.Listxattr":             syscall.Listxattr,
	"syscall.LsfJump":               syscall.LsfJump,
	"syscall.LsfSocket":             syscall.LsfSocket,
	"syscall.LsfStmt":               syscall.LsfStmt,
	"syscall.Madvise":               syscall.Madvise,
	"syscall.Mkdirat":               syscall.Mkdirat,
	"syscall.Mknodat":               syscall.Mknodat,
	"syscall.Mount":                 syscall.Mount,
	"syscall.NetlinkRIB":            syscall.NetlinkRIB,
	"syscall.Openat":                syscall.Openat,
	"syscall.ParseNetlinkMessage":   syscall.ParseNetlinkMessage,
	"syscall.ParseNetlinkRouteAttr": syscall.ParseNetlinkRouteAttr,
	"syscall.ParseUnixCredentials":  syscall.ParseUnixCredentials,
	"syscall.Pause":                 syscall.Pause,
	"syscall.PivotRoot":             syscall.PivotRoot,
	"syscall.PtraceCont":            syscall.PtraceCont,
	"syscall.PtraceGetEventMsg":     syscall.PtraceGetEventMsg,
	"syscall.PtraceGetRegs":         syscall.PtraceGetRegs,
	"syscall.PtracePeekData":        syscall.PtracePeekData,
	"syscall.PtracePeekText":        syscall.PtracePeekText,
	"syscall.PtracePokeData":        syscall.PtracePokeData,
	"syscall.PtracePokeText":        syscall.PtracePokeText,
	"syscall.PtraceSetOptions":      syscall.PtraceSetOptions,
	"syscall.PtraceSetRegs":         syscall.PtraceSetRegs,
	"syscall.PtraceSingleStep":      syscall.PtraceSingleStep,
	"syscall.PtraceSyscall":         syscall.PtraceSyscall,
	"syscall.Reboot":                syscall.Reboot,
	"syscall.Removexattr":           syscall.Removexattr,
	"syscall.Renameat":              syscall.Renameat,
	"syscall.SetLsfPromisc":         syscall.SetLsfPromisc,
	"syscall.Setdomainname":         syscall.Setdomainname,
	"syscall.Setfsgid":              syscall.Setfsgid,
	"syscall.Setfsuid":              syscall.Setfsuid,
	"syscall.Sethostname":           syscall.Sethostname,
	"syscall.Setresgid":             syscall.Setresgid,
	"syscall.Setresuid":             syscall.Setresuid,
	"syscall.Setxattr":              syscall.Setxattr,
	"syscall.Splice":                syscall.Splice,
	"syscall.SyncFileRange":         syscall.SyncFileRange,
	"syscall.Sysinfo":               syscall.Sysinfo,
	"syscall.Tee":                   syscall.Tee,
	"syscall.Tgkill":                syscall.Tgkill,
	"syscall.Time":                  syscall.Time,
	"syscall.Times":                 syscall.Times,
	"syscall.Uname":                 syscall.Uname,
	"syscall.UnixCredentials":       syscall.UnixCredentials,
	"syscall.Unlinkat":              syscall.Unlinkat,
	"syscall.Unshare":               syscall.Unshare,
	"syscall.Ustat":                 syscall.Ustat,
	"syscall.Utime":                 syscall.Utime,
}

var typList_linux = []interface{}{
	(*syscall.EpollEvent)(nil),
	(*syscall.IfAddrmsg)(nil),
	(*syscall.IfInfomsg)(nil),
	(*syscall.InotifyEvent)(nil),
	(*syscall.NetlinkMessage)(nil),
	(*syscall.NetlinkRouteAttr)(nil),
	(*syscall.NetlinkRouteRequest)(nil),
	(*syscall.NlAttr)(nil),
	(*syscall.NlMsgerr)(nil),
	(*syscall.NlMsghdr)(nil),
	(*syscall.PtraceRegs)(nil),
	(*syscall.RawSockaddrLinklayer)(nil),
	(*syscall.RawSockaddrNetlink)(nil),
	(*syscall.RtAttr)(nil),
	(*syscall.RtGenmsg)(nil),
	(*syscall.RtMsg)(nil),
	(*syscall.RtNexthop)(nil),
	(*syscall.SockFilter)(nil),
	(*syscall.SockFprog)(nil),
	(*syscall.SockaddrLinklayer)(nil),
	(*syscall.SockaddrNetlink)(nil),
	(*syscall.SysProcIDMap)(nil),
	(*syscall.Sysinfo_t)(nil),
	(*syscall.TCPInfo)(nil),
	(*syscall.Time_t)(nil),
	(*syscall.Timex)(nil),
	(*syscall.Tms)(nil),
	(*syscall.Ucred)(nil),
	(*syscall.Ustat_t)(nil),
	(*syscall.Utimbuf)(nil),
	(*syscall.Utsname)(nil),
}
