// export by github.com/goplus/gossa/cmd/qexp

package net

import (
	"net"

	"github.com/goplus/gossa"
)

func init() {
	gossa.RegisterPackage("net", extMap, typList)
}

var extMap = map[string]interface{}{
	"(*net.AddrError).Error":               (*net.AddrError).Error,
	"(*net.AddrError).Temporary":           (*net.AddrError).Temporary,
	"(*net.AddrError).Timeout":             (*net.AddrError).Timeout,
	"(*net.Buffers).Read":                  (*net.Buffers).Read,
	"(*net.Buffers).WriteTo":               (*net.Buffers).WriteTo,
	"(*net.DNSConfigError).Error":          (*net.DNSConfigError).Error,
	"(*net.DNSConfigError).Temporary":      (*net.DNSConfigError).Temporary,
	"(*net.DNSConfigError).Timeout":        (*net.DNSConfigError).Timeout,
	"(*net.DNSConfigError).Unwrap":         (*net.DNSConfigError).Unwrap,
	"(*net.DNSError).Error":                (*net.DNSError).Error,
	"(*net.DNSError).Temporary":            (*net.DNSError).Temporary,
	"(*net.DNSError).Timeout":              (*net.DNSError).Timeout,
	"(*net.Dialer).Dial":                   (*net.Dialer).Dial,
	"(*net.Dialer).DialContext":            (*net.Dialer).DialContext,
	"(*net.IP).UnmarshalText":              (*net.IP).UnmarshalText,
	"(*net.IPAddr).Network":                (*net.IPAddr).Network,
	"(*net.IPAddr).String":                 (*net.IPAddr).String,
	"(*net.IPConn).Close":                  (*net.IPConn).Close,
	"(*net.IPConn).File":                   (*net.IPConn).File,
	"(*net.IPConn).LocalAddr":              (*net.IPConn).LocalAddr,
	"(*net.IPConn).Read":                   (*net.IPConn).Read,
	"(*net.IPConn).ReadFrom":               (*net.IPConn).ReadFrom,
	"(*net.IPConn).ReadFromIP":             (*net.IPConn).ReadFromIP,
	"(*net.IPConn).ReadMsgIP":              (*net.IPConn).ReadMsgIP,
	"(*net.IPConn).RemoteAddr":             (*net.IPConn).RemoteAddr,
	"(*net.IPConn).SetDeadline":            (*net.IPConn).SetDeadline,
	"(*net.IPConn).SetReadBuffer":          (*net.IPConn).SetReadBuffer,
	"(*net.IPConn).SetReadDeadline":        (*net.IPConn).SetReadDeadline,
	"(*net.IPConn).SetWriteBuffer":         (*net.IPConn).SetWriteBuffer,
	"(*net.IPConn).SetWriteDeadline":       (*net.IPConn).SetWriteDeadline,
	"(*net.IPConn).SyscallConn":            (*net.IPConn).SyscallConn,
	"(*net.IPConn).Write":                  (*net.IPConn).Write,
	"(*net.IPConn).WriteMsgIP":             (*net.IPConn).WriteMsgIP,
	"(*net.IPConn).WriteTo":                (*net.IPConn).WriteTo,
	"(*net.IPConn).WriteToIP":              (*net.IPConn).WriteToIP,
	"(*net.IPNet).Contains":                (*net.IPNet).Contains,
	"(*net.IPNet).Network":                 (*net.IPNet).Network,
	"(*net.IPNet).String":                  (*net.IPNet).String,
	"(*net.Interface).Addrs":               (*net.Interface).Addrs,
	"(*net.Interface).MulticastAddrs":      (*net.Interface).MulticastAddrs,
	"(*net.ListenConfig).Listen":           (*net.ListenConfig).Listen,
	"(*net.ListenConfig).ListenPacket":     (*net.ListenConfig).ListenPacket,
	"(*net.OpError).Error":                 (*net.OpError).Error,
	"(*net.OpError).Temporary":             (*net.OpError).Temporary,
	"(*net.OpError).Timeout":               (*net.OpError).Timeout,
	"(*net.OpError).Unwrap":                (*net.OpError).Unwrap,
	"(*net.ParseError).Error":              (*net.ParseError).Error,
	"(*net.Resolver).LookupAddr":           (*net.Resolver).LookupAddr,
	"(*net.Resolver).LookupCNAME":          (*net.Resolver).LookupCNAME,
	"(*net.Resolver).LookupHost":           (*net.Resolver).LookupHost,
	"(*net.Resolver).LookupIPAddr":         (*net.Resolver).LookupIPAddr,
	"(*net.Resolver).LookupMX":             (*net.Resolver).LookupMX,
	"(*net.Resolver).LookupNS":             (*net.Resolver).LookupNS,
	"(*net.Resolver).LookupPort":           (*net.Resolver).LookupPort,
	"(*net.Resolver).LookupSRV":            (*net.Resolver).LookupSRV,
	"(*net.Resolver).LookupTXT":            (*net.Resolver).LookupTXT,
	"(*net.TCPAddr).Network":               (*net.TCPAddr).Network,
	"(*net.TCPAddr).String":                (*net.TCPAddr).String,
	"(*net.TCPConn).Close":                 (*net.TCPConn).Close,
	"(*net.TCPConn).CloseRead":             (*net.TCPConn).CloseRead,
	"(*net.TCPConn).CloseWrite":            (*net.TCPConn).CloseWrite,
	"(*net.TCPConn).File":                  (*net.TCPConn).File,
	"(*net.TCPConn).LocalAddr":             (*net.TCPConn).LocalAddr,
	"(*net.TCPConn).Read":                  (*net.TCPConn).Read,
	"(*net.TCPConn).ReadFrom":              (*net.TCPConn).ReadFrom,
	"(*net.TCPConn).RemoteAddr":            (*net.TCPConn).RemoteAddr,
	"(*net.TCPConn).SetDeadline":           (*net.TCPConn).SetDeadline,
	"(*net.TCPConn).SetKeepAlive":          (*net.TCPConn).SetKeepAlive,
	"(*net.TCPConn).SetKeepAlivePeriod":    (*net.TCPConn).SetKeepAlivePeriod,
	"(*net.TCPConn).SetLinger":             (*net.TCPConn).SetLinger,
	"(*net.TCPConn).SetNoDelay":            (*net.TCPConn).SetNoDelay,
	"(*net.TCPConn).SetReadBuffer":         (*net.TCPConn).SetReadBuffer,
	"(*net.TCPConn).SetReadDeadline":       (*net.TCPConn).SetReadDeadline,
	"(*net.TCPConn).SetWriteBuffer":        (*net.TCPConn).SetWriteBuffer,
	"(*net.TCPConn).SetWriteDeadline":      (*net.TCPConn).SetWriteDeadline,
	"(*net.TCPConn).SyscallConn":           (*net.TCPConn).SyscallConn,
	"(*net.TCPConn).Write":                 (*net.TCPConn).Write,
	"(*net.TCPListener).Accept":            (*net.TCPListener).Accept,
	"(*net.TCPListener).AcceptTCP":         (*net.TCPListener).AcceptTCP,
	"(*net.TCPListener).Addr":              (*net.TCPListener).Addr,
	"(*net.TCPListener).Close":             (*net.TCPListener).Close,
	"(*net.TCPListener).File":              (*net.TCPListener).File,
	"(*net.TCPListener).SetDeadline":       (*net.TCPListener).SetDeadline,
	"(*net.TCPListener).SyscallConn":       (*net.TCPListener).SyscallConn,
	"(*net.UDPAddr).Network":               (*net.UDPAddr).Network,
	"(*net.UDPAddr).String":                (*net.UDPAddr).String,
	"(*net.UDPConn).Close":                 (*net.UDPConn).Close,
	"(*net.UDPConn).File":                  (*net.UDPConn).File,
	"(*net.UDPConn).LocalAddr":             (*net.UDPConn).LocalAddr,
	"(*net.UDPConn).Read":                  (*net.UDPConn).Read,
	"(*net.UDPConn).ReadFrom":              (*net.UDPConn).ReadFrom,
	"(*net.UDPConn).ReadFromUDP":           (*net.UDPConn).ReadFromUDP,
	"(*net.UDPConn).ReadMsgUDP":            (*net.UDPConn).ReadMsgUDP,
	"(*net.UDPConn).RemoteAddr":            (*net.UDPConn).RemoteAddr,
	"(*net.UDPConn).SetDeadline":           (*net.UDPConn).SetDeadline,
	"(*net.UDPConn).SetReadBuffer":         (*net.UDPConn).SetReadBuffer,
	"(*net.UDPConn).SetReadDeadline":       (*net.UDPConn).SetReadDeadline,
	"(*net.UDPConn).SetWriteBuffer":        (*net.UDPConn).SetWriteBuffer,
	"(*net.UDPConn).SetWriteDeadline":      (*net.UDPConn).SetWriteDeadline,
	"(*net.UDPConn).SyscallConn":           (*net.UDPConn).SyscallConn,
	"(*net.UDPConn).Write":                 (*net.UDPConn).Write,
	"(*net.UDPConn).WriteMsgUDP":           (*net.UDPConn).WriteMsgUDP,
	"(*net.UDPConn).WriteTo":               (*net.UDPConn).WriteTo,
	"(*net.UDPConn).WriteToUDP":            (*net.UDPConn).WriteToUDP,
	"(*net.UnixAddr).Network":              (*net.UnixAddr).Network,
	"(*net.UnixAddr).String":               (*net.UnixAddr).String,
	"(*net.UnixConn).Close":                (*net.UnixConn).Close,
	"(*net.UnixConn).CloseRead":            (*net.UnixConn).CloseRead,
	"(*net.UnixConn).CloseWrite":           (*net.UnixConn).CloseWrite,
	"(*net.UnixConn).File":                 (*net.UnixConn).File,
	"(*net.UnixConn).LocalAddr":            (*net.UnixConn).LocalAddr,
	"(*net.UnixConn).Read":                 (*net.UnixConn).Read,
	"(*net.UnixConn).ReadFrom":             (*net.UnixConn).ReadFrom,
	"(*net.UnixConn).ReadFromUnix":         (*net.UnixConn).ReadFromUnix,
	"(*net.UnixConn).ReadMsgUnix":          (*net.UnixConn).ReadMsgUnix,
	"(*net.UnixConn).RemoteAddr":           (*net.UnixConn).RemoteAddr,
	"(*net.UnixConn).SetDeadline":          (*net.UnixConn).SetDeadline,
	"(*net.UnixConn).SetReadBuffer":        (*net.UnixConn).SetReadBuffer,
	"(*net.UnixConn).SetReadDeadline":      (*net.UnixConn).SetReadDeadline,
	"(*net.UnixConn).SetWriteBuffer":       (*net.UnixConn).SetWriteBuffer,
	"(*net.UnixConn).SetWriteDeadline":     (*net.UnixConn).SetWriteDeadline,
	"(*net.UnixConn).SyscallConn":          (*net.UnixConn).SyscallConn,
	"(*net.UnixConn).Write":                (*net.UnixConn).Write,
	"(*net.UnixConn).WriteMsgUnix":         (*net.UnixConn).WriteMsgUnix,
	"(*net.UnixConn).WriteTo":              (*net.UnixConn).WriteTo,
	"(*net.UnixConn).WriteToUnix":          (*net.UnixConn).WriteToUnix,
	"(*net.UnixListener).Accept":           (*net.UnixListener).Accept,
	"(*net.UnixListener).AcceptUnix":       (*net.UnixListener).AcceptUnix,
	"(*net.UnixListener).Addr":             (*net.UnixListener).Addr,
	"(*net.UnixListener).Close":            (*net.UnixListener).Close,
	"(*net.UnixListener).File":             (*net.UnixListener).File,
	"(*net.UnixListener).SetDeadline":      (*net.UnixListener).SetDeadline,
	"(*net.UnixListener).SetUnlinkOnClose": (*net.UnixListener).SetUnlinkOnClose,
	"(*net.UnixListener).SyscallConn":      (*net.UnixListener).SyscallConn,
	"(net.Addr).Network":                   (net.Addr).Network,
	"(net.Addr).String":                    (net.Addr).String,
	"(net.Conn).Close":                     (net.Conn).Close,
	"(net.Conn).LocalAddr":                 (net.Conn).LocalAddr,
	"(net.Conn).Read":                      (net.Conn).Read,
	"(net.Conn).RemoteAddr":                (net.Conn).RemoteAddr,
	"(net.Conn).SetDeadline":               (net.Conn).SetDeadline,
	"(net.Conn).SetReadDeadline":           (net.Conn).SetReadDeadline,
	"(net.Conn).SetWriteDeadline":          (net.Conn).SetWriteDeadline,
	"(net.Conn).Write":                     (net.Conn).Write,
	"(net.Error).Error":                    (net.Error).Error,
	"(net.Error).Temporary":                (net.Error).Temporary,
	"(net.Error).Timeout":                  (net.Error).Timeout,
	"(net.Flags).String":                   (net.Flags).String,
	"(net.HardwareAddr).String":            (net.HardwareAddr).String,
	"(net.IP).DefaultMask":                 (net.IP).DefaultMask,
	"(net.IP).Equal":                       (net.IP).Equal,
	"(net.IP).IsGlobalUnicast":             (net.IP).IsGlobalUnicast,
	"(net.IP).IsInterfaceLocalMulticast":   (net.IP).IsInterfaceLocalMulticast,
	"(net.IP).IsLinkLocalMulticast":        (net.IP).IsLinkLocalMulticast,
	"(net.IP).IsLinkLocalUnicast":          (net.IP).IsLinkLocalUnicast,
	"(net.IP).IsLoopback":                  (net.IP).IsLoopback,
	"(net.IP).IsMulticast":                 (net.IP).IsMulticast,
	"(net.IP).IsUnspecified":               (net.IP).IsUnspecified,
	"(net.IP).MarshalText":                 (net.IP).MarshalText,
	"(net.IP).Mask":                        (net.IP).Mask,
	"(net.IP).String":                      (net.IP).String,
	"(net.IP).To16":                        (net.IP).To16,
	"(net.IP).To4":                         (net.IP).To4,
	"(net.IPMask).Size":                    (net.IPMask).Size,
	"(net.IPMask).String":                  (net.IPMask).String,
	"(net.InvalidAddrError).Error":         (net.InvalidAddrError).Error,
	"(net.InvalidAddrError).Temporary":     (net.InvalidAddrError).Temporary,
	"(net.InvalidAddrError).Timeout":       (net.InvalidAddrError).Timeout,
	"(net.Listener).Accept":                (net.Listener).Accept,
	"(net.Listener).Addr":                  (net.Listener).Addr,
	"(net.Listener).Close":                 (net.Listener).Close,
	"(net.PacketConn).Close":               (net.PacketConn).Close,
	"(net.PacketConn).LocalAddr":           (net.PacketConn).LocalAddr,
	"(net.PacketConn).ReadFrom":            (net.PacketConn).ReadFrom,
	"(net.PacketConn).SetDeadline":         (net.PacketConn).SetDeadline,
	"(net.PacketConn).SetReadDeadline":     (net.PacketConn).SetReadDeadline,
	"(net.PacketConn).SetWriteDeadline":    (net.PacketConn).SetWriteDeadline,
	"(net.PacketConn).WriteTo":             (net.PacketConn).WriteTo,
	"(net.UnknownNetworkError).Error":      (net.UnknownNetworkError).Error,
	"(net.UnknownNetworkError).Temporary":  (net.UnknownNetworkError).Temporary,
	"(net.UnknownNetworkError).Timeout":    (net.UnknownNetworkError).Timeout,
	"net.CIDRMask":                         net.CIDRMask,
	"net.DefaultResolver":                  &net.DefaultResolver,
	"net.Dial":                             net.Dial,
	"net.DialIP":                           net.DialIP,
	"net.DialTCP":                          net.DialTCP,
	"net.DialTimeout":                      net.DialTimeout,
	"net.DialUDP":                          net.DialUDP,
	"net.DialUnix":                         net.DialUnix,
	"net.ErrWriteToConnected":              &net.ErrWriteToConnected,
	"net.FileConn":                         net.FileConn,
	"net.FileListener":                     net.FileListener,
	"net.FilePacketConn":                   net.FilePacketConn,
	"net.IPv4":                             net.IPv4,
	"net.IPv4Mask":                         net.IPv4Mask,
	"net.IPv4allrouter":                    &net.IPv4allrouter,
	"net.IPv4allsys":                       &net.IPv4allsys,
	"net.IPv4bcast":                        &net.IPv4bcast,
	"net.IPv4zero":                         &net.IPv4zero,
	"net.IPv6interfacelocalallnodes":       &net.IPv6interfacelocalallnodes,
	"net.IPv6linklocalallnodes":            &net.IPv6linklocalallnodes,
	"net.IPv6linklocalallrouters":          &net.IPv6linklocalallrouters,
	"net.IPv6loopback":                     &net.IPv6loopback,
	"net.IPv6unspecified":                  &net.IPv6unspecified,
	"net.IPv6zero":                         &net.IPv6zero,
	"net.InterfaceAddrs":                   net.InterfaceAddrs,
	"net.InterfaceByIndex":                 net.InterfaceByIndex,
	"net.InterfaceByName":                  net.InterfaceByName,
	"net.Interfaces":                       net.Interfaces,
	"net.JoinHostPort":                     net.JoinHostPort,
	"net.Listen":                           net.Listen,
	"net.ListenIP":                         net.ListenIP,
	"net.ListenMulticastUDP":               net.ListenMulticastUDP,
	"net.ListenPacket":                     net.ListenPacket,
	"net.ListenTCP":                        net.ListenTCP,
	"net.ListenUDP":                        net.ListenUDP,
	"net.ListenUnix":                       net.ListenUnix,
	"net.ListenUnixgram":                   net.ListenUnixgram,
	"net.LookupAddr":                       net.LookupAddr,
	"net.LookupCNAME":                      net.LookupCNAME,
	"net.LookupHost":                       net.LookupHost,
	"net.LookupIP":                         net.LookupIP,
	"net.LookupMX":                         net.LookupMX,
	"net.LookupNS":                         net.LookupNS,
	"net.LookupPort":                       net.LookupPort,
	"net.LookupSRV":                        net.LookupSRV,
	"net.LookupTXT":                        net.LookupTXT,
	"net.ParseCIDR":                        net.ParseCIDR,
	"net.ParseIP":                          net.ParseIP,
	"net.ParseMAC":                         net.ParseMAC,
	"net.Pipe":                             net.Pipe,
	"net.ResolveIPAddr":                    net.ResolveIPAddr,
	"net.ResolveTCPAddr":                   net.ResolveTCPAddr,
	"net.ResolveUDPAddr":                   net.ResolveUDPAddr,
	"net.ResolveUnixAddr":                  net.ResolveUnixAddr,
	"net.SplitHostPort":                    net.SplitHostPort,
}

var typList = []interface{}{
	(*net.Addr)(nil),
	(*net.AddrError)(nil),
	(*net.Buffers)(nil),
	(*net.Conn)(nil),
	(*net.DNSConfigError)(nil),
	(*net.DNSError)(nil),
	(*net.Dialer)(nil),
	(*net.Error)(nil),
	(*net.Flags)(nil),
	(*net.HardwareAddr)(nil),
	(*net.IP)(nil),
	(*net.IPAddr)(nil),
	(*net.IPConn)(nil),
	(*net.IPMask)(nil),
	(*net.IPNet)(nil),
	(*net.Interface)(nil),
	(*net.InvalidAddrError)(nil),
	(*net.ListenConfig)(nil),
	(*net.Listener)(nil),
	(*net.MX)(nil),
	(*net.NS)(nil),
	(*net.OpError)(nil),
	(*net.PacketConn)(nil),
	(*net.ParseError)(nil),
	(*net.Resolver)(nil),
	(*net.SRV)(nil),
	(*net.TCPAddr)(nil),
	(*net.TCPConn)(nil),
	(*net.TCPListener)(nil),
	(*net.UDPAddr)(nil),
	(*net.UDPConn)(nil),
	(*net.UnixAddr)(nil),
	(*net.UnixConn)(nil),
	(*net.UnixListener)(nil),
	(*net.UnknownNetworkError)(nil),
}
