// export by github.com/goplus/gossa/cmd/qexp

package sql

import (
	"database/sql"

	"github.com/goplus/gossa"
)

func init() {
	gossa.RegisterPackage("database/sql", extMap, typList)
}

var extMap = map[string]interface{}{
	"(*database/sql.ColumnType).DatabaseTypeName": (*sql.ColumnType).DatabaseTypeName,
	"(*database/sql.ColumnType).DecimalSize":      (*sql.ColumnType).DecimalSize,
	"(*database/sql.ColumnType).Length":           (*sql.ColumnType).Length,
	"(*database/sql.ColumnType).Name":             (*sql.ColumnType).Name,
	"(*database/sql.ColumnType).Nullable":         (*sql.ColumnType).Nullable,
	"(*database/sql.ColumnType).ScanType":         (*sql.ColumnType).ScanType,
	"(*database/sql.Conn).BeginTx":                (*sql.Conn).BeginTx,
	"(*database/sql.Conn).Close":                  (*sql.Conn).Close,
	"(*database/sql.Conn).ExecContext":            (*sql.Conn).ExecContext,
	"(*database/sql.Conn).PingContext":            (*sql.Conn).PingContext,
	"(*database/sql.Conn).PrepareContext":         (*sql.Conn).PrepareContext,
	"(*database/sql.Conn).QueryContext":           (*sql.Conn).QueryContext,
	"(*database/sql.Conn).QueryRowContext":        (*sql.Conn).QueryRowContext,
	"(*database/sql.Conn).Raw":                    (*sql.Conn).Raw,
	"(*database/sql.DB).Begin":                    (*sql.DB).Begin,
	"(*database/sql.DB).BeginTx":                  (*sql.DB).BeginTx,
	"(*database/sql.DB).Close":                    (*sql.DB).Close,
	"(*database/sql.DB).Conn":                     (*sql.DB).Conn,
	"(*database/sql.DB).Driver":                   (*sql.DB).Driver,
	"(*database/sql.DB).Exec":                     (*sql.DB).Exec,
	"(*database/sql.DB).ExecContext":              (*sql.DB).ExecContext,
	"(*database/sql.DB).Ping":                     (*sql.DB).Ping,
	"(*database/sql.DB).PingContext":              (*sql.DB).PingContext,
	"(*database/sql.DB).Prepare":                  (*sql.DB).Prepare,
	"(*database/sql.DB).PrepareContext":           (*sql.DB).PrepareContext,
	"(*database/sql.DB).Query":                    (*sql.DB).Query,
	"(*database/sql.DB).QueryContext":             (*sql.DB).QueryContext,
	"(*database/sql.DB).QueryRow":                 (*sql.DB).QueryRow,
	"(*database/sql.DB).QueryRowContext":          (*sql.DB).QueryRowContext,
	"(*database/sql.DB).SetConnMaxLifetime":       (*sql.DB).SetConnMaxLifetime,
	"(*database/sql.DB).SetMaxIdleConns":          (*sql.DB).SetMaxIdleConns,
	"(*database/sql.DB).SetMaxOpenConns":          (*sql.DB).SetMaxOpenConns,
	"(*database/sql.DB).Stats":                    (*sql.DB).Stats,
	"(*database/sql.NullBool).Scan":               (*sql.NullBool).Scan,
	"(*database/sql.NullFloat64).Scan":            (*sql.NullFloat64).Scan,
	"(*database/sql.NullInt32).Scan":              (*sql.NullInt32).Scan,
	"(*database/sql.NullInt64).Scan":              (*sql.NullInt64).Scan,
	"(*database/sql.NullString).Scan":             (*sql.NullString).Scan,
	"(*database/sql.NullTime).Scan":               (*sql.NullTime).Scan,
	"(*database/sql.Row).Scan":                    (*sql.Row).Scan,
	"(*database/sql.Rows).Close":                  (*sql.Rows).Close,
	"(*database/sql.Rows).ColumnTypes":            (*sql.Rows).ColumnTypes,
	"(*database/sql.Rows).Columns":                (*sql.Rows).Columns,
	"(*database/sql.Rows).Err":                    (*sql.Rows).Err,
	"(*database/sql.Rows).Next":                   (*sql.Rows).Next,
	"(*database/sql.Rows).NextResultSet":          (*sql.Rows).NextResultSet,
	"(*database/sql.Rows).Scan":                   (*sql.Rows).Scan,
	"(*database/sql.Stmt).Close":                  (*sql.Stmt).Close,
	"(*database/sql.Stmt).Exec":                   (*sql.Stmt).Exec,
	"(*database/sql.Stmt).ExecContext":            (*sql.Stmt).ExecContext,
	"(*database/sql.Stmt).Query":                  (*sql.Stmt).Query,
	"(*database/sql.Stmt).QueryContext":           (*sql.Stmt).QueryContext,
	"(*database/sql.Stmt).QueryRow":               (*sql.Stmt).QueryRow,
	"(*database/sql.Stmt).QueryRowContext":        (*sql.Stmt).QueryRowContext,
	"(*database/sql.Tx).Commit":                   (*sql.Tx).Commit,
	"(*database/sql.Tx).Exec":                     (*sql.Tx).Exec,
	"(*database/sql.Tx).ExecContext":              (*sql.Tx).ExecContext,
	"(*database/sql.Tx).Prepare":                  (*sql.Tx).Prepare,
	"(*database/sql.Tx).PrepareContext":           (*sql.Tx).PrepareContext,
	"(*database/sql.Tx).Query":                    (*sql.Tx).Query,
	"(*database/sql.Tx).QueryContext":             (*sql.Tx).QueryContext,
	"(*database/sql.Tx).QueryRow":                 (*sql.Tx).QueryRow,
	"(*database/sql.Tx).QueryRowContext":          (*sql.Tx).QueryRowContext,
	"(*database/sql.Tx).Rollback":                 (*sql.Tx).Rollback,
	"(*database/sql.Tx).Stmt":                     (*sql.Tx).Stmt,
	"(*database/sql.Tx).StmtContext":              (*sql.Tx).StmtContext,
	"(database/sql.IsolationLevel).String":        (sql.IsolationLevel).String,
	"(database/sql.NullBool).Value":               (sql.NullBool).Value,
	"(database/sql.NullFloat64).Value":            (sql.NullFloat64).Value,
	"(database/sql.NullInt32).Value":              (sql.NullInt32).Value,
	"(database/sql.NullInt64).Value":              (sql.NullInt64).Value,
	"(database/sql.NullString).Value":             (sql.NullString).Value,
	"(database/sql.NullTime).Value":               (sql.NullTime).Value,
	"(database/sql.Result).LastInsertId":          (sql.Result).LastInsertId,
	"(database/sql.Result).RowsAffected":          (sql.Result).RowsAffected,
	"(database/sql.Scanner).Scan":                 (sql.Scanner).Scan,
	"database/sql.Drivers":                        sql.Drivers,
	"database/sql.ErrConnDone":                    &sql.ErrConnDone,
	"database/sql.ErrNoRows":                      &sql.ErrNoRows,
	"database/sql.ErrTxDone":                      &sql.ErrTxDone,
	"database/sql.Named":                          sql.Named,
	"database/sql.Open":                           sql.Open,
	"database/sql.OpenDB":                         sql.OpenDB,
	"database/sql.Register":                       sql.Register,
}

var typList = []interface{}{
	(*sql.ColumnType)(nil),
	(*sql.Conn)(nil),
	(*sql.DB)(nil),
	(*sql.DBStats)(nil),
	(*sql.IsolationLevel)(nil),
	(*sql.NamedArg)(nil),
	(*sql.NullBool)(nil),
	(*sql.NullFloat64)(nil),
	(*sql.NullInt32)(nil),
	(*sql.NullInt64)(nil),
	(*sql.NullString)(nil),
	(*sql.NullTime)(nil),
	(*sql.Out)(nil),
	(*sql.RawBytes)(nil),
	(*sql.Result)(nil),
	(*sql.Row)(nil),
	(*sql.Rows)(nil),
	(*sql.Scanner)(nil),
	(*sql.Stmt)(nil),
	(*sql.Tx)(nil),
	(*sql.TxOptions)(nil),
}
