// export by github.com/goplus/gossa/cmd/qexp

package x509

import (
	q "crypto/x509"

	"go/constant"
	"reflect"

	"github.com/goplus/gossa"
)

func init() {
	gossa.RegisterPackage(&gossa.Package{
		Name: "x509",
		Path: "crypto/x509",
		Deps: map[string]string{
			"bytes":                                 "bytes",
			"crypto":                                "crypto",
			"crypto/aes":                            "aes",
			"crypto/cipher":                         "cipher",
			"crypto/des":                            "des",
			"crypto/dsa":                            "dsa",
			"crypto/ecdsa":                          "ecdsa",
			"crypto/ed25519":                        "ed25519",
			"crypto/elliptic":                       "elliptic",
			"crypto/md5":                            "md5",
			"crypto/rsa":                            "rsa",
			"crypto/sha1":                           "sha1",
			"crypto/sha256":                         "sha256",
			"crypto/sha512":                         "sha512",
			"crypto/x509/internal/macos":            "macOS",
			"crypto/x509/pkix":                      "pkix",
			"encoding/asn1":                         "asn1",
			"encoding/hex":                          "hex",
			"encoding/pem":                          "pem",
			"errors":                                "errors",
			"fmt":                                   "fmt",
			"io":                                    "io",
			"math/big":                              "big",
			"net":                                   "net",
			"net/url":                               "url",
			"os":                                    "os",
			"reflect":                               "reflect",
			"runtime":                               "runtime",
			"strconv":                               "strconv",
			"strings":                               "strings",
			"sync":                                  "sync",
			"time":                                  "time",
			"unicode":                               "unicode",
			"unicode/utf8":                          "utf8",
			"vendor/golang.org/x/crypto/cryptobyte": "cryptobyte",
			"vendor/golang.org/x/crypto/cryptobyte/asn1": "asn1",
		},
		Interfaces: map[string]reflect.Type{},
		NamedTypes: map[string]gossa.NamedType{
			"CertPool":                   {reflect.TypeOf((*q.CertPool)(nil)).Elem(), "", "AddCert,AppendCertsFromPEM,Subjects,addCertFunc,cert,contains,copy,findPotentialParents,len"},
			"Certificate":                {reflect.TypeOf((*q.Certificate)(nil)).Elem(), "", "CheckCRLSignature,CheckSignature,CheckSignatureFrom,CreateCRL,Equal,Verify,VerifyHostname,buildChains,checkNameConstraints,commonNameAsHostname,getSANExtension,hasNameConstraints,hasSANExtension,isValid,systemVerify"},
			"CertificateInvalidError":    {reflect.TypeOf((*q.CertificateInvalidError)(nil)).Elem(), "Error", ""},
			"CertificateRequest":         {reflect.TypeOf((*q.CertificateRequest)(nil)).Elem(), "", "CheckSignature"},
			"ConstraintViolationError":   {reflect.TypeOf((*q.ConstraintViolationError)(nil)).Elem(), "Error", ""},
			"ExtKeyUsage":                {reflect.TypeOf((*q.ExtKeyUsage)(nil)).Elem(), "", ""},
			"HostnameError":              {reflect.TypeOf((*q.HostnameError)(nil)).Elem(), "Error", ""},
			"InsecureAlgorithmError":     {reflect.TypeOf((*q.InsecureAlgorithmError)(nil)).Elem(), "Error", ""},
			"InvalidReason":              {reflect.TypeOf((*q.InvalidReason)(nil)).Elem(), "", ""},
			"KeyUsage":                   {reflect.TypeOf((*q.KeyUsage)(nil)).Elem(), "", ""},
			"PEMCipher":                  {reflect.TypeOf((*q.PEMCipher)(nil)).Elem(), "", ""},
			"PublicKeyAlgorithm":         {reflect.TypeOf((*q.PublicKeyAlgorithm)(nil)).Elem(), "String", ""},
			"RevocationList":             {reflect.TypeOf((*q.RevocationList)(nil)).Elem(), "", ""},
			"SignatureAlgorithm":         {reflect.TypeOf((*q.SignatureAlgorithm)(nil)).Elem(), "String,isRSAPSS", ""},
			"SystemRootsError":           {reflect.TypeOf((*q.SystemRootsError)(nil)).Elem(), "Error,Unwrap", ""},
			"UnhandledCriticalExtension": {reflect.TypeOf((*q.UnhandledCriticalExtension)(nil)).Elem(), "Error", ""},
			"UnknownAuthorityError":      {reflect.TypeOf((*q.UnknownAuthorityError)(nil)).Elem(), "Error", ""},
			"VerifyOptions":              {reflect.TypeOf((*q.VerifyOptions)(nil)).Elem(), "", ""},
		},
		AliasTypes: map[string]reflect.Type{},
		Vars: map[string]reflect.Value{
			"ErrUnsupportedAlgorithm": reflect.ValueOf(&q.ErrUnsupportedAlgorithm),
			"IncorrectPasswordError":  reflect.ValueOf(&q.IncorrectPasswordError),
		},
		Funcs: map[string]reflect.Value{
			"CreateCertificate":        reflect.ValueOf(q.CreateCertificate),
			"CreateCertificateRequest": reflect.ValueOf(q.CreateCertificateRequest),
			"CreateRevocationList":     reflect.ValueOf(q.CreateRevocationList),
			"DecryptPEMBlock":          reflect.ValueOf(q.DecryptPEMBlock),
			"EncryptPEMBlock":          reflect.ValueOf(q.EncryptPEMBlock),
			"IsEncryptedPEMBlock":      reflect.ValueOf(q.IsEncryptedPEMBlock),
			"MarshalECPrivateKey":      reflect.ValueOf(q.MarshalECPrivateKey),
			"MarshalPKCS1PrivateKey":   reflect.ValueOf(q.MarshalPKCS1PrivateKey),
			"MarshalPKCS1PublicKey":    reflect.ValueOf(q.MarshalPKCS1PublicKey),
			"MarshalPKCS8PrivateKey":   reflect.ValueOf(q.MarshalPKCS8PrivateKey),
			"MarshalPKIXPublicKey":     reflect.ValueOf(q.MarshalPKIXPublicKey),
			"NewCertPool":              reflect.ValueOf(q.NewCertPool),
			"ParseCRL":                 reflect.ValueOf(q.ParseCRL),
			"ParseCertificate":         reflect.ValueOf(q.ParseCertificate),
			"ParseCertificateRequest":  reflect.ValueOf(q.ParseCertificateRequest),
			"ParseCertificates":        reflect.ValueOf(q.ParseCertificates),
			"ParseDERCRL":              reflect.ValueOf(q.ParseDERCRL),
			"ParseECPrivateKey":        reflect.ValueOf(q.ParseECPrivateKey),
			"ParsePKCS1PrivateKey":     reflect.ValueOf(q.ParsePKCS1PrivateKey),
			"ParsePKCS1PublicKey":      reflect.ValueOf(q.ParsePKCS1PublicKey),
			"ParsePKCS8PrivateKey":     reflect.ValueOf(q.ParsePKCS8PrivateKey),
			"ParsePKIXPublicKey":       reflect.ValueOf(q.ParsePKIXPublicKey),
			"SystemCertPool":           reflect.ValueOf(q.SystemCertPool),
		},
		TypedConsts: map[string]gossa.TypedConst{
			"CANotAuthorizedForExtKeyUsage": {reflect.TypeOf(q.CANotAuthorizedForExtKeyUsage), constant.MakeInt64(9)},
			"CANotAuthorizedForThisName":    {reflect.TypeOf(q.CANotAuthorizedForThisName), constant.MakeInt64(2)},
			"DSA":                           {reflect.TypeOf(q.DSA), constant.MakeInt64(2)},
			"DSAWithSHA1":                   {reflect.TypeOf(q.DSAWithSHA1), constant.MakeInt64(7)},
			"DSAWithSHA256":                 {reflect.TypeOf(q.DSAWithSHA256), constant.MakeInt64(8)},
			"ECDSA":                         {reflect.TypeOf(q.ECDSA), constant.MakeInt64(3)},
			"ECDSAWithSHA1":                 {reflect.TypeOf(q.ECDSAWithSHA1), constant.MakeInt64(9)},
			"ECDSAWithSHA256":               {reflect.TypeOf(q.ECDSAWithSHA256), constant.MakeInt64(10)},
			"ECDSAWithSHA384":               {reflect.TypeOf(q.ECDSAWithSHA384), constant.MakeInt64(11)},
			"ECDSAWithSHA512":               {reflect.TypeOf(q.ECDSAWithSHA512), constant.MakeInt64(12)},
			"Ed25519":                       {reflect.TypeOf(q.Ed25519), constant.MakeInt64(4)},
			"Expired":                       {reflect.TypeOf(q.Expired), constant.MakeInt64(1)},
			"ExtKeyUsageAny":                {reflect.TypeOf(q.ExtKeyUsageAny), constant.MakeInt64(0)},
			"ExtKeyUsageClientAuth":         {reflect.TypeOf(q.ExtKeyUsageClientAuth), constant.MakeInt64(2)},
			"ExtKeyUsageCodeSigning":        {reflect.TypeOf(q.ExtKeyUsageCodeSigning), constant.MakeInt64(3)},
			"ExtKeyUsageEmailProtection":    {reflect.TypeOf(q.ExtKeyUsageEmailProtection), constant.MakeInt64(4)},
			"ExtKeyUsageIPSECEndSystem":     {reflect.TypeOf(q.ExtKeyUsageIPSECEndSystem), constant.MakeInt64(5)},
			"ExtKeyUsageIPSECTunnel":        {reflect.TypeOf(q.ExtKeyUsageIPSECTunnel), constant.MakeInt64(6)},
			"ExtKeyUsageIPSECUser":          {reflect.TypeOf(q.ExtKeyUsageIPSECUser), constant.MakeInt64(7)},
			"ExtKeyUsageMicrosoftCommercialCodeSigning": {reflect.TypeOf(q.ExtKeyUsageMicrosoftCommercialCodeSigning), constant.MakeInt64(12)},
			"ExtKeyUsageMicrosoftKernelCodeSigning":     {reflect.TypeOf(q.ExtKeyUsageMicrosoftKernelCodeSigning), constant.MakeInt64(13)},
			"ExtKeyUsageMicrosoftServerGatedCrypto":     {reflect.TypeOf(q.ExtKeyUsageMicrosoftServerGatedCrypto), constant.MakeInt64(10)},
			"ExtKeyUsageNetscapeServerGatedCrypto":      {reflect.TypeOf(q.ExtKeyUsageNetscapeServerGatedCrypto), constant.MakeInt64(11)},
			"ExtKeyUsageOCSPSigning":                    {reflect.TypeOf(q.ExtKeyUsageOCSPSigning), constant.MakeInt64(9)},
			"ExtKeyUsageServerAuth":                     {reflect.TypeOf(q.ExtKeyUsageServerAuth), constant.MakeInt64(1)},
			"ExtKeyUsageTimeStamping":                   {reflect.TypeOf(q.ExtKeyUsageTimeStamping), constant.MakeInt64(8)},
			"IncompatibleUsage":                         {reflect.TypeOf(q.IncompatibleUsage), constant.MakeInt64(4)},
			"KeyUsageCRLSign":                           {reflect.TypeOf(q.KeyUsageCRLSign), constant.MakeInt64(64)},
			"KeyUsageCertSign":                          {reflect.TypeOf(q.KeyUsageCertSign), constant.MakeInt64(32)},
			"KeyUsageContentCommitment":                 {reflect.TypeOf(q.KeyUsageContentCommitment), constant.MakeInt64(2)},
			"KeyUsageDataEncipherment":                  {reflect.TypeOf(q.KeyUsageDataEncipherment), constant.MakeInt64(8)},
			"KeyUsageDecipherOnly":                      {reflect.TypeOf(q.KeyUsageDecipherOnly), constant.MakeInt64(256)},
			"KeyUsageDigitalSignature":                  {reflect.TypeOf(q.KeyUsageDigitalSignature), constant.MakeInt64(1)},
			"KeyUsageEncipherOnly":                      {reflect.TypeOf(q.KeyUsageEncipherOnly), constant.MakeInt64(128)},
			"KeyUsageKeyAgreement":                      {reflect.TypeOf(q.KeyUsageKeyAgreement), constant.MakeInt64(16)},
			"KeyUsageKeyEncipherment":                   {reflect.TypeOf(q.KeyUsageKeyEncipherment), constant.MakeInt64(4)},
			"MD2WithRSA":                                {reflect.TypeOf(q.MD2WithRSA), constant.MakeInt64(1)},
			"MD5WithRSA":                                {reflect.TypeOf(q.MD5WithRSA), constant.MakeInt64(2)},
			"NameConstraintsWithoutSANs":                {reflect.TypeOf(q.NameConstraintsWithoutSANs), constant.MakeInt64(6)},
			"NameMismatch":                              {reflect.TypeOf(q.NameMismatch), constant.MakeInt64(5)},
			"NotAuthorizedToSign":                       {reflect.TypeOf(q.NotAuthorizedToSign), constant.MakeInt64(0)},
			"PEMCipher3DES":                             {reflect.TypeOf(q.PEMCipher3DES), constant.MakeInt64(2)},
			"PEMCipherAES128":                           {reflect.TypeOf(q.PEMCipherAES128), constant.MakeInt64(3)},
			"PEMCipherAES192":                           {reflect.TypeOf(q.PEMCipherAES192), constant.MakeInt64(4)},
			"PEMCipherAES256":                           {reflect.TypeOf(q.PEMCipherAES256), constant.MakeInt64(5)},
			"PEMCipherDES":                              {reflect.TypeOf(q.PEMCipherDES), constant.MakeInt64(1)},
			"PureEd25519":                               {reflect.TypeOf(q.PureEd25519), constant.MakeInt64(16)},
			"RSA":                                       {reflect.TypeOf(q.RSA), constant.MakeInt64(1)},
			"SHA1WithRSA":                               {reflect.TypeOf(q.SHA1WithRSA), constant.MakeInt64(3)},
			"SHA256WithRSA":                             {reflect.TypeOf(q.SHA256WithRSA), constant.MakeInt64(4)},
			"SHA256WithRSAPSS":                          {reflect.TypeOf(q.SHA256WithRSAPSS), constant.MakeInt64(13)},
			"SHA384WithRSA":                             {reflect.TypeOf(q.SHA384WithRSA), constant.MakeInt64(5)},
			"SHA384WithRSAPSS":                          {reflect.TypeOf(q.SHA384WithRSAPSS), constant.MakeInt64(14)},
			"SHA512WithRSA":                             {reflect.TypeOf(q.SHA512WithRSA), constant.MakeInt64(6)},
			"SHA512WithRSAPSS":                          {reflect.TypeOf(q.SHA512WithRSAPSS), constant.MakeInt64(15)},
			"TooManyConstraints":                        {reflect.TypeOf(q.TooManyConstraints), constant.MakeInt64(8)},
			"TooManyIntermediates":                      {reflect.TypeOf(q.TooManyIntermediates), constant.MakeInt64(3)},
			"UnconstrainedName":                         {reflect.TypeOf(q.UnconstrainedName), constant.MakeInt64(7)},
			"UnknownPublicKeyAlgorithm":                 {reflect.TypeOf(q.UnknownPublicKeyAlgorithm), constant.MakeInt64(0)},
			"UnknownSignatureAlgorithm":                 {reflect.TypeOf(q.UnknownSignatureAlgorithm), constant.MakeInt64(0)},
		},
		UntypedConsts: map[string]gossa.UntypedConst{},
	})
}
