// export by github.com/goplus/gossa/cmd/qexp

package pe

import (
	q "debug/pe"

	"go/constant"
	"reflect"

	"github.com/goplus/gossa"
)

func init() {
	gossa.RegisterPackage(&gossa.Package{
		Name: "pe",
		Path: "debug/pe",
		Deps: map[string]string{
			"bytes":           "bytes",
			"compress/zlib":   "zlib",
			"debug/dwarf":     "dwarf",
			"encoding/binary": "binary",
			"fmt":             "fmt",
			"io":              "io",
			"os":              "os",
			"strconv":         "strconv",
			"strings":         "strings",
		},
		Interfaces: map[string]reflect.Type{},
		NamedTypes: map[string]gossa.NamedType{
			"COFFSymbol":       {reflect.TypeOf((*q.COFFSymbol)(nil)).Elem(), "", "FullName"},
			"DataDirectory":    {reflect.TypeOf((*q.DataDirectory)(nil)).Elem(), "", ""},
			"File":             {reflect.TypeOf((*q.File)(nil)).Elem(), "", "Close,DWARF,ImportedLibraries,ImportedSymbols,Section"},
			"FileHeader":       {reflect.TypeOf((*q.FileHeader)(nil)).Elem(), "", ""},
			"FormatError":      {reflect.TypeOf((*q.FormatError)(nil)).Elem(), "", "Error"},
			"ImportDirectory":  {reflect.TypeOf((*q.ImportDirectory)(nil)).Elem(), "", ""},
			"OptionalHeader32": {reflect.TypeOf((*q.OptionalHeader32)(nil)).Elem(), "", ""},
			"OptionalHeader64": {reflect.TypeOf((*q.OptionalHeader64)(nil)).Elem(), "", ""},
			"Reloc":            {reflect.TypeOf((*q.Reloc)(nil)).Elem(), "", ""},
			"Section":          {reflect.TypeOf((*q.Section)(nil)).Elem(), "", "Data,Open"},
			"SectionHeader":    {reflect.TypeOf((*q.SectionHeader)(nil)).Elem(), "", ""},
			"SectionHeader32":  {reflect.TypeOf((*q.SectionHeader32)(nil)).Elem(), "", "fullName"},
			"StringTable":      {reflect.TypeOf((*q.StringTable)(nil)).Elem(), "String", ""},
			"Symbol":           {reflect.TypeOf((*q.Symbol)(nil)).Elem(), "", ""},
		},
		AliasTypes: map[string]reflect.Type{},
		Vars:       map[string]reflect.Value{},
		Funcs: map[string]reflect.Value{
			"NewFile": reflect.ValueOf(q.NewFile),
			"Open":    reflect.ValueOf(q.Open),
		},
		TypedConsts: map[string]gossa.TypedConst{},
		UntypedConsts: map[string]gossa.UntypedConst{
			"COFFSymbolSize":                                 {"untyped int", constant.MakeInt64(18)},
			"IMAGE_DIRECTORY_ENTRY_ARCHITECTURE":             {"untyped int", constant.MakeInt64(7)},
			"IMAGE_DIRECTORY_ENTRY_BASERELOC":                {"untyped int", constant.MakeInt64(5)},
			"IMAGE_DIRECTORY_ENTRY_BOUND_IMPORT":             {"untyped int", constant.MakeInt64(11)},
			"IMAGE_DIRECTORY_ENTRY_COM_DESCRIPTOR":           {"untyped int", constant.MakeInt64(14)},
			"IMAGE_DIRECTORY_ENTRY_DEBUG":                    {"untyped int", constant.MakeInt64(6)},
			"IMAGE_DIRECTORY_ENTRY_DELAY_IMPORT":             {"untyped int", constant.MakeInt64(13)},
			"IMAGE_DIRECTORY_ENTRY_EXCEPTION":                {"untyped int", constant.MakeInt64(3)},
			"IMAGE_DIRECTORY_ENTRY_EXPORT":                   {"untyped int", constant.MakeInt64(0)},
			"IMAGE_DIRECTORY_ENTRY_GLOBALPTR":                {"untyped int", constant.MakeInt64(8)},
			"IMAGE_DIRECTORY_ENTRY_IAT":                      {"untyped int", constant.MakeInt64(12)},
			"IMAGE_DIRECTORY_ENTRY_IMPORT":                   {"untyped int", constant.MakeInt64(1)},
			"IMAGE_DIRECTORY_ENTRY_LOAD_CONFIG":              {"untyped int", constant.MakeInt64(10)},
			"IMAGE_DIRECTORY_ENTRY_RESOURCE":                 {"untyped int", constant.MakeInt64(2)},
			"IMAGE_DIRECTORY_ENTRY_SECURITY":                 {"untyped int", constant.MakeInt64(4)},
			"IMAGE_DIRECTORY_ENTRY_TLS":                      {"untyped int", constant.MakeInt64(9)},
			"IMAGE_DLLCHARACTERISTICS_APPCONTAINER":          {"untyped int", constant.MakeInt64(4096)},
			"IMAGE_DLLCHARACTERISTICS_DYNAMIC_BASE":          {"untyped int", constant.MakeInt64(64)},
			"IMAGE_DLLCHARACTERISTICS_FORCE_INTEGRITY":       {"untyped int", constant.MakeInt64(128)},
			"IMAGE_DLLCHARACTERISTICS_GUARD_CF":              {"untyped int", constant.MakeInt64(16384)},
			"IMAGE_DLLCHARACTERISTICS_HIGH_ENTROPY_VA":       {"untyped int", constant.MakeInt64(32)},
			"IMAGE_DLLCHARACTERISTICS_NO_BIND":               {"untyped int", constant.MakeInt64(2048)},
			"IMAGE_DLLCHARACTERISTICS_NO_ISOLATION":          {"untyped int", constant.MakeInt64(512)},
			"IMAGE_DLLCHARACTERISTICS_NO_SEH":                {"untyped int", constant.MakeInt64(1024)},
			"IMAGE_DLLCHARACTERISTICS_NX_COMPAT":             {"untyped int", constant.MakeInt64(256)},
			"IMAGE_DLLCHARACTERISTICS_TERMINAL_SERVER_AWARE": {"untyped int", constant.MakeInt64(32768)},
			"IMAGE_DLLCHARACTERISTICS_WDM_DRIVER":            {"untyped int", constant.MakeInt64(8192)},
			"IMAGE_FILE_32BIT_MACHINE":                       {"untyped int", constant.MakeInt64(256)},
			"IMAGE_FILE_AGGRESIVE_WS_TRIM":                   {"untyped int", constant.MakeInt64(16)},
			"IMAGE_FILE_BYTES_REVERSED_HI":                   {"untyped int", constant.MakeInt64(32768)},
			"IMAGE_FILE_BYTES_REVERSED_LO":                   {"untyped int", constant.MakeInt64(128)},
			"IMAGE_FILE_DEBUG_STRIPPED":                      {"untyped int", constant.MakeInt64(512)},
			"IMAGE_FILE_DLL":                                 {"untyped int", constant.MakeInt64(8192)},
			"IMAGE_FILE_EXECUTABLE_IMAGE":                    {"untyped int", constant.MakeInt64(2)},
			"IMAGE_FILE_LARGE_ADDRESS_AWARE":                 {"untyped int", constant.MakeInt64(32)},
			"IMAGE_FILE_LINE_NUMS_STRIPPED":                  {"untyped int", constant.MakeInt64(4)},
			"IMAGE_FILE_LOCAL_SYMS_STRIPPED":                 {"untyped int", constant.MakeInt64(8)},
			"IMAGE_FILE_MACHINE_AM33":                        {"untyped int", constant.MakeInt64(467)},
			"IMAGE_FILE_MACHINE_AMD64":                       {"untyped int", constant.MakeInt64(34404)},
			"IMAGE_FILE_MACHINE_ARM":                         {"untyped int", constant.MakeInt64(448)},
			"IMAGE_FILE_MACHINE_ARM64":                       {"untyped int", constant.MakeInt64(43620)},
			"IMAGE_FILE_MACHINE_ARMNT":                       {"untyped int", constant.MakeInt64(452)},
			"IMAGE_FILE_MACHINE_EBC":                         {"untyped int", constant.MakeInt64(3772)},
			"IMAGE_FILE_MACHINE_I386":                        {"untyped int", constant.MakeInt64(332)},
			"IMAGE_FILE_MACHINE_IA64":                        {"untyped int", constant.MakeInt64(512)},
			"IMAGE_FILE_MACHINE_M32R":                        {"untyped int", constant.MakeInt64(36929)},
			"IMAGE_FILE_MACHINE_MIPS16":                      {"untyped int", constant.MakeInt64(614)},
			"IMAGE_FILE_MACHINE_MIPSFPU":                     {"untyped int", constant.MakeInt64(870)},
			"IMAGE_FILE_MACHINE_MIPSFPU16":                   {"untyped int", constant.MakeInt64(1126)},
			"IMAGE_FILE_MACHINE_POWERPC":                     {"untyped int", constant.MakeInt64(496)},
			"IMAGE_FILE_MACHINE_POWERPCFP":                   {"untyped int", constant.MakeInt64(497)},
			"IMAGE_FILE_MACHINE_R4000":                       {"untyped int", constant.MakeInt64(358)},
			"IMAGE_FILE_MACHINE_SH3":                         {"untyped int", constant.MakeInt64(418)},
			"IMAGE_FILE_MACHINE_SH3DSP":                      {"untyped int", constant.MakeInt64(419)},
			"IMAGE_FILE_MACHINE_SH4":                         {"untyped int", constant.MakeInt64(422)},
			"IMAGE_FILE_MACHINE_SH5":                         {"untyped int", constant.MakeInt64(424)},
			"IMAGE_FILE_MACHINE_THUMB":                       {"untyped int", constant.MakeInt64(450)},
			"IMAGE_FILE_MACHINE_UNKNOWN":                     {"untyped int", constant.MakeInt64(0)},
			"IMAGE_FILE_MACHINE_WCEMIPSV2":                   {"untyped int", constant.MakeInt64(361)},
			"IMAGE_FILE_NET_RUN_FROM_SWAP":                   {"untyped int", constant.MakeInt64(2048)},
			"IMAGE_FILE_RELOCS_STRIPPED":                     {"untyped int", constant.MakeInt64(1)},
			"IMAGE_FILE_REMOVABLE_RUN_FROM_SWAP":             {"untyped int", constant.MakeInt64(1024)},
			"IMAGE_FILE_SYSTEM":                              {"untyped int", constant.MakeInt64(4096)},
			"IMAGE_FILE_UP_SYSTEM_ONLY":                      {"untyped int", constant.MakeInt64(16384)},
			"IMAGE_SUBSYSTEM_EFI_APPLICATION":                {"untyped int", constant.MakeInt64(10)},
			"IMAGE_SUBSYSTEM_EFI_BOOT_SERVICE_DRIVER":        {"untyped int", constant.MakeInt64(11)},
			"IMAGE_SUBSYSTEM_EFI_ROM":                        {"untyped int", constant.MakeInt64(13)},
			"IMAGE_SUBSYSTEM_EFI_RUNTIME_DRIVER":             {"untyped int", constant.MakeInt64(12)},
			"IMAGE_SUBSYSTEM_NATIVE":                         {"untyped int", constant.MakeInt64(1)},
			"IMAGE_SUBSYSTEM_NATIVE_WINDOWS":                 {"untyped int", constant.MakeInt64(8)},
			"IMAGE_SUBSYSTEM_OS2_CUI":                        {"untyped int", constant.MakeInt64(5)},
			"IMAGE_SUBSYSTEM_POSIX_CUI":                      {"untyped int", constant.MakeInt64(7)},
			"IMAGE_SUBSYSTEM_UNKNOWN":                        {"untyped int", constant.MakeInt64(0)},
			"IMAGE_SUBSYSTEM_WINDOWS_BOOT_APPLICATION":       {"untyped int", constant.MakeInt64(16)},
			"IMAGE_SUBSYSTEM_WINDOWS_CE_GUI":                 {"untyped int", constant.MakeInt64(9)},
			"IMAGE_SUBSYSTEM_WINDOWS_CUI":                    {"untyped int", constant.MakeInt64(3)},
			"IMAGE_SUBSYSTEM_WINDOWS_GUI":                    {"untyped int", constant.MakeInt64(2)},
			"IMAGE_SUBSYSTEM_XBOX":                           {"untyped int", constant.MakeInt64(14)},
		},
	})
}
