// export by github.com/goplus/gossa/cmd/qexp

package io

import (
	"io"

	"github.com/goplus/gossa"
)

func init() {
	gossa.RegisterPackage("io", extMap, typList)
}

var extMap = map[string]interface{}{
	"(*io.LimitedReader).Read":        (*io.LimitedReader).Read,
	"(*io.PipeReader).Close":          (*io.PipeReader).Close,
	"(*io.PipeReader).CloseWithError": (*io.PipeReader).CloseWithError,
	"(*io.PipeReader).Read":           (*io.PipeReader).Read,
	"(*io.PipeWriter).Close":          (*io.PipeWriter).Close,
	"(*io.PipeWriter).CloseWithError": (*io.PipeWriter).CloseWithError,
	"(*io.PipeWriter).Write":          (*io.PipeWriter).Write,
	"(*io.SectionReader).Read":        (*io.SectionReader).Read,
	"(*io.SectionReader).ReadAt":      (*io.SectionReader).ReadAt,
	"(*io.SectionReader).Seek":        (*io.SectionReader).Seek,
	"(*io.SectionReader).Size":        (*io.SectionReader).Size,
	"(io.ByteReader).ReadByte":        (io.ByteReader).ReadByte,
	"(io.ByteScanner).ReadByte":       (io.ByteScanner).ReadByte,
	"(io.ByteScanner).UnreadByte":     (io.ByteScanner).UnreadByte,
	"(io.ByteWriter).WriteByte":       (io.ByteWriter).WriteByte,
	"(io.Closer).Close":               (io.Closer).Close,
	"(io.ReadCloser).Close":           (io.ReadCloser).Close,
	"(io.ReadCloser).Read":            (io.ReadCloser).Read,
	"(io.ReadSeeker).Read":            (io.ReadSeeker).Read,
	"(io.ReadSeeker).Seek":            (io.ReadSeeker).Seek,
	"(io.ReadWriteCloser).Close":      (io.ReadWriteCloser).Close,
	"(io.ReadWriteCloser).Read":       (io.ReadWriteCloser).Read,
	"(io.ReadWriteCloser).Write":      (io.ReadWriteCloser).Write,
	"(io.ReadWriteSeeker).Read":       (io.ReadWriteSeeker).Read,
	"(io.ReadWriteSeeker).Seek":       (io.ReadWriteSeeker).Seek,
	"(io.ReadWriteSeeker).Write":      (io.ReadWriteSeeker).Write,
	"(io.ReadWriter).Read":            (io.ReadWriter).Read,
	"(io.ReadWriter).Write":           (io.ReadWriter).Write,
	"(io.Reader).Read":                (io.Reader).Read,
	"(io.ReaderAt).ReadAt":            (io.ReaderAt).ReadAt,
	"(io.ReaderFrom).ReadFrom":        (io.ReaderFrom).ReadFrom,
	"(io.RuneReader).ReadRune":        (io.RuneReader).ReadRune,
	"(io.RuneScanner).ReadRune":       (io.RuneScanner).ReadRune,
	"(io.RuneScanner).UnreadRune":     (io.RuneScanner).UnreadRune,
	"(io.Seeker).Seek":                (io.Seeker).Seek,
	"(io.StringWriter).WriteString":   (io.StringWriter).WriteString,
	"(io.WriteCloser).Close":          (io.WriteCloser).Close,
	"(io.WriteCloser).Write":          (io.WriteCloser).Write,
	"(io.WriteSeeker).Seek":           (io.WriteSeeker).Seek,
	"(io.WriteSeeker).Write":          (io.WriteSeeker).Write,
	"(io.Writer).Write":               (io.Writer).Write,
	"(io.WriterAt).WriteAt":           (io.WriterAt).WriteAt,
	"(io.WriterTo).WriteTo":           (io.WriterTo).WriteTo,
	"io.Copy":                         io.Copy,
	"io.CopyBuffer":                   io.CopyBuffer,
	"io.CopyN":                        io.CopyN,
	"io.EOF":                          &io.EOF,
	"io.ErrClosedPipe":                &io.ErrClosedPipe,
	"io.ErrNoProgress":                &io.ErrNoProgress,
	"io.ErrShortBuffer":               &io.ErrShortBuffer,
	"io.ErrShortWrite":                &io.ErrShortWrite,
	"io.ErrUnexpectedEOF":             &io.ErrUnexpectedEOF,
	"io.LimitReader":                  io.LimitReader,
	"io.MultiReader":                  io.MultiReader,
	"io.MultiWriter":                  io.MultiWriter,
	"io.NewSectionReader":             io.NewSectionReader,
	"io.Pipe":                         io.Pipe,
	"io.ReadAtLeast":                  io.ReadAtLeast,
	"io.ReadFull":                     io.ReadFull,
	"io.TeeReader":                    io.TeeReader,
	"io.WriteString":                  io.WriteString,
}

var typList = []interface{}{
	(*io.ByteReader)(nil),
	(*io.ByteScanner)(nil),
	(*io.ByteWriter)(nil),
	(*io.Closer)(nil),
	(*io.LimitedReader)(nil),
	(*io.PipeReader)(nil),
	(*io.PipeWriter)(nil),
	(*io.ReadCloser)(nil),
	(*io.ReadSeeker)(nil),
	(*io.ReadWriteCloser)(nil),
	(*io.ReadWriteSeeker)(nil),
	(*io.ReadWriter)(nil),
	(*io.Reader)(nil),
	(*io.ReaderAt)(nil),
	(*io.ReaderFrom)(nil),
	(*io.RuneReader)(nil),
	(*io.RuneScanner)(nil),
	(*io.SectionReader)(nil),
	(*io.Seeker)(nil),
	(*io.StringWriter)(nil),
	(*io.WriteCloser)(nil),
	(*io.WriteSeeker)(nil),
	(*io.Writer)(nil),
	(*io.WriterAt)(nil),
	(*io.WriterTo)(nil),
}
