// export by github.com/goplus/interp/cmd/qexp

package dwarf

import (
	"debug/dwarf"

	"github.com/goplus/interp"
)

func init() {
	interp.RegisterPackage("debug/dwarf", extMap, typList)
}

var extMap = map[string]interface{}{
	"(*debug/dwarf.AddrType).Basic":         (*dwarf.AddrType).Basic,
	"(*debug/dwarf.AddrType).Common":        (*dwarf.AddrType).Common,
	"(*debug/dwarf.AddrType).Size":          (*dwarf.AddrType).Size,
	"(*debug/dwarf.AddrType).String":        (*dwarf.AddrType).String,
	"(*debug/dwarf.ArrayType).Common":       (*dwarf.ArrayType).Common,
	"(*debug/dwarf.ArrayType).Size":         (*dwarf.ArrayType).Size,
	"(*debug/dwarf.ArrayType).String":       (*dwarf.ArrayType).String,
	"(*debug/dwarf.BasicType).Basic":        (*dwarf.BasicType).Basic,
	"(*debug/dwarf.BasicType).Common":       (*dwarf.BasicType).Common,
	"(*debug/dwarf.BasicType).Size":         (*dwarf.BasicType).Size,
	"(*debug/dwarf.BasicType).String":       (*dwarf.BasicType).String,
	"(*debug/dwarf.BoolType).Basic":         (*dwarf.BoolType).Basic,
	"(*debug/dwarf.BoolType).Common":        (*dwarf.BoolType).Common,
	"(*debug/dwarf.BoolType).Size":          (*dwarf.BoolType).Size,
	"(*debug/dwarf.BoolType).String":        (*dwarf.BoolType).String,
	"(*debug/dwarf.CharType).Basic":         (*dwarf.CharType).Basic,
	"(*debug/dwarf.CharType).Common":        (*dwarf.CharType).Common,
	"(*debug/dwarf.CharType).Size":          (*dwarf.CharType).Size,
	"(*debug/dwarf.CharType).String":        (*dwarf.CharType).String,
	"(*debug/dwarf.CommonType).Common":      (*dwarf.CommonType).Common,
	"(*debug/dwarf.CommonType).Size":        (*dwarf.CommonType).Size,
	"(*debug/dwarf.ComplexType).Basic":      (*dwarf.ComplexType).Basic,
	"(*debug/dwarf.ComplexType).Common":     (*dwarf.ComplexType).Common,
	"(*debug/dwarf.ComplexType).Size":       (*dwarf.ComplexType).Size,
	"(*debug/dwarf.ComplexType).String":     (*dwarf.ComplexType).String,
	"(*debug/dwarf.Data).AddSection":        (*dwarf.Data).AddSection,
	"(*debug/dwarf.Data).AddTypes":          (*dwarf.Data).AddTypes,
	"(*debug/dwarf.Data).LineReader":        (*dwarf.Data).LineReader,
	"(*debug/dwarf.Data).Ranges":            (*dwarf.Data).Ranges,
	"(*debug/dwarf.Data).Reader":            (*dwarf.Data).Reader,
	"(*debug/dwarf.Data).Type":              (*dwarf.Data).Type,
	"(*debug/dwarf.DotDotDotType).Common":   (*dwarf.DotDotDotType).Common,
	"(*debug/dwarf.DotDotDotType).Size":     (*dwarf.DotDotDotType).Size,
	"(*debug/dwarf.DotDotDotType).String":   (*dwarf.DotDotDotType).String,
	"(*debug/dwarf.Entry).AttrField":        (*dwarf.Entry).AttrField,
	"(*debug/dwarf.Entry).Val":              (*dwarf.Entry).Val,
	"(*debug/dwarf.EnumType).Common":        (*dwarf.EnumType).Common,
	"(*debug/dwarf.EnumType).Size":          (*dwarf.EnumType).Size,
	"(*debug/dwarf.EnumType).String":        (*dwarf.EnumType).String,
	"(*debug/dwarf.FloatType).Basic":        (*dwarf.FloatType).Basic,
	"(*debug/dwarf.FloatType).Common":       (*dwarf.FloatType).Common,
	"(*debug/dwarf.FloatType).Size":         (*dwarf.FloatType).Size,
	"(*debug/dwarf.FloatType).String":       (*dwarf.FloatType).String,
	"(*debug/dwarf.FuncType).Common":        (*dwarf.FuncType).Common,
	"(*debug/dwarf.FuncType).Size":          (*dwarf.FuncType).Size,
	"(*debug/dwarf.FuncType).String":        (*dwarf.FuncType).String,
	"(*debug/dwarf.IntType).Basic":          (*dwarf.IntType).Basic,
	"(*debug/dwarf.IntType).Common":         (*dwarf.IntType).Common,
	"(*debug/dwarf.IntType).Size":           (*dwarf.IntType).Size,
	"(*debug/dwarf.IntType).String":         (*dwarf.IntType).String,
	"(*debug/dwarf.LineReader).Files":       (*dwarf.LineReader).Files,
	"(*debug/dwarf.LineReader).Next":        (*dwarf.LineReader).Next,
	"(*debug/dwarf.LineReader).Reset":       (*dwarf.LineReader).Reset,
	"(*debug/dwarf.LineReader).Seek":        (*dwarf.LineReader).Seek,
	"(*debug/dwarf.LineReader).SeekPC":      (*dwarf.LineReader).SeekPC,
	"(*debug/dwarf.LineReader).Tell":        (*dwarf.LineReader).Tell,
	"(*debug/dwarf.PtrType).Common":         (*dwarf.PtrType).Common,
	"(*debug/dwarf.PtrType).Size":           (*dwarf.PtrType).Size,
	"(*debug/dwarf.PtrType).String":         (*dwarf.PtrType).String,
	"(*debug/dwarf.QualType).Common":        (*dwarf.QualType).Common,
	"(*debug/dwarf.QualType).Size":          (*dwarf.QualType).Size,
	"(*debug/dwarf.QualType).String":        (*dwarf.QualType).String,
	"(*debug/dwarf.Reader).AddressSize":     (*dwarf.Reader).AddressSize,
	"(*debug/dwarf.Reader).ByteOrder":       (*dwarf.Reader).ByteOrder,
	"(*debug/dwarf.Reader).Next":            (*dwarf.Reader).Next,
	"(*debug/dwarf.Reader).Seek":            (*dwarf.Reader).Seek,
	"(*debug/dwarf.Reader).SeekPC":          (*dwarf.Reader).SeekPC,
	"(*debug/dwarf.Reader).SkipChildren":    (*dwarf.Reader).SkipChildren,
	"(*debug/dwarf.StructType).Common":      (*dwarf.StructType).Common,
	"(*debug/dwarf.StructType).Defn":        (*dwarf.StructType).Defn,
	"(*debug/dwarf.StructType).Size":        (*dwarf.StructType).Size,
	"(*debug/dwarf.StructType).String":      (*dwarf.StructType).String,
	"(*debug/dwarf.TypedefType).Common":     (*dwarf.TypedefType).Common,
	"(*debug/dwarf.TypedefType).Size":       (*dwarf.TypedefType).Size,
	"(*debug/dwarf.TypedefType).String":     (*dwarf.TypedefType).String,
	"(*debug/dwarf.UcharType).Basic":        (*dwarf.UcharType).Basic,
	"(*debug/dwarf.UcharType).Common":       (*dwarf.UcharType).Common,
	"(*debug/dwarf.UcharType).Size":         (*dwarf.UcharType).Size,
	"(*debug/dwarf.UcharType).String":       (*dwarf.UcharType).String,
	"(*debug/dwarf.UintType).Basic":         (*dwarf.UintType).Basic,
	"(*debug/dwarf.UintType).Common":        (*dwarf.UintType).Common,
	"(*debug/dwarf.UintType).Size":          (*dwarf.UintType).Size,
	"(*debug/dwarf.UintType).String":        (*dwarf.UintType).String,
	"(*debug/dwarf.UnspecifiedType).Basic":  (*dwarf.UnspecifiedType).Basic,
	"(*debug/dwarf.UnspecifiedType).Common": (*dwarf.UnspecifiedType).Common,
	"(*debug/dwarf.UnspecifiedType).Size":   (*dwarf.UnspecifiedType).Size,
	"(*debug/dwarf.UnspecifiedType).String": (*dwarf.UnspecifiedType).String,
	"(*debug/dwarf.UnsupportedType).Common": (*dwarf.UnsupportedType).Common,
	"(*debug/dwarf.UnsupportedType).Size":   (*dwarf.UnsupportedType).Size,
	"(*debug/dwarf.UnsupportedType).String": (*dwarf.UnsupportedType).String,
	"(*debug/dwarf.VoidType).Common":        (*dwarf.VoidType).Common,
	"(*debug/dwarf.VoidType).Size":          (*dwarf.VoidType).Size,
	"(*debug/dwarf.VoidType).String":        (*dwarf.VoidType).String,
	"(debug/dwarf.Attr).GoString":           (dwarf.Attr).GoString,
	"(debug/dwarf.Attr).String":             (dwarf.Attr).String,
	"(debug/dwarf.Class).GoString":          (dwarf.Class).GoString,
	"(debug/dwarf.Class).String":            (dwarf.Class).String,
	"(debug/dwarf.DecodeError).Error":       (dwarf.DecodeError).Error,
	"(debug/dwarf.Tag).GoString":            (dwarf.Tag).GoString,
	"(debug/dwarf.Tag).String":              (dwarf.Tag).String,
	"(debug/dwarf.Type).Common":             (dwarf.Type).Common,
	"(debug/dwarf.Type).Size":               (dwarf.Type).Size,
	"(debug/dwarf.Type).String":             (dwarf.Type).String,
	"debug/dwarf.ErrUnknownPC":              &dwarf.ErrUnknownPC,
	"debug/dwarf.New":                       dwarf.New,
}

var typList = []interface{}{
	(*dwarf.AddrType)(nil),
	(*dwarf.ArrayType)(nil),
	(*dwarf.Attr)(nil),
	(*dwarf.BasicType)(nil),
	(*dwarf.BoolType)(nil),
	(*dwarf.CharType)(nil),
	(*dwarf.Class)(nil),
	(*dwarf.CommonType)(nil),
	(*dwarf.ComplexType)(nil),
	(*dwarf.Data)(nil),
	(*dwarf.DecodeError)(nil),
	(*dwarf.DotDotDotType)(nil),
	(*dwarf.Entry)(nil),
	(*dwarf.EnumType)(nil),
	(*dwarf.EnumValue)(nil),
	(*dwarf.Field)(nil),
	(*dwarf.FloatType)(nil),
	(*dwarf.FuncType)(nil),
	(*dwarf.IntType)(nil),
	(*dwarf.LineEntry)(nil),
	(*dwarf.LineFile)(nil),
	(*dwarf.LineReader)(nil),
	(*dwarf.LineReaderPos)(nil),
	(*dwarf.Offset)(nil),
	(*dwarf.PtrType)(nil),
	(*dwarf.QualType)(nil),
	(*dwarf.Reader)(nil),
	(*dwarf.StructField)(nil),
	(*dwarf.StructType)(nil),
	(*dwarf.Tag)(nil),
	(*dwarf.Type)(nil),
	(*dwarf.TypedefType)(nil),
	(*dwarf.UcharType)(nil),
	(*dwarf.UintType)(nil),
	(*dwarf.UnspecifiedType)(nil),
	(*dwarf.UnsupportedType)(nil),
	(*dwarf.VoidType)(nil),
}
