// export by github.com/goplus/gossa/cmd/qexp

package dwarf

import (
	q "debug/dwarf"

	"go/constant"
	"reflect"

	"github.com/goplus/gossa"
)

func init() {
	gossa.RegisterPackage(&gossa.Package{
		Name: "dwarf",
		Path: "debug/dwarf",
		Deps: map[string]string{
			"bytes":           "bytes",
			"encoding/binary": "binary",
			"errors":          "errors",
			"fmt":             "fmt",
			"io":              "io",
			"path":            "path",
			"sort":            "sort",
			"strconv":         "strconv",
			"strings":         "strings",
		},
		Interfaces: map[string]reflect.Type{
			"Type": reflect.TypeOf((*q.Type)(nil)).Elem(),
		},
		NamedTypes: map[string]gossa.NamedType{
			"AddrType":        {reflect.TypeOf((*q.AddrType)(nil)).Elem(), "", ""},
			"ArrayType":       {reflect.TypeOf((*q.ArrayType)(nil)).Elem(), "", "Size,String"},
			"Attr":            {reflect.TypeOf((*q.Attr)(nil)).Elem(), "GoString,String", ""},
			"BasicType":       {reflect.TypeOf((*q.BasicType)(nil)).Elem(), "", "Basic,String"},
			"BoolType":        {reflect.TypeOf((*q.BoolType)(nil)).Elem(), "", ""},
			"CharType":        {reflect.TypeOf((*q.CharType)(nil)).Elem(), "", ""},
			"Class":           {reflect.TypeOf((*q.Class)(nil)).Elem(), "GoString,String", ""},
			"CommonType":      {reflect.TypeOf((*q.CommonType)(nil)).Elem(), "", "Common,Size"},
			"ComplexType":     {reflect.TypeOf((*q.ComplexType)(nil)).Elem(), "", ""},
			"Data":            {reflect.TypeOf((*q.Data)(nil)).Elem(), "", "AddSection,AddTypes,LineReader,Ranges,Reader,Type,baseAddressForEntry,debugAddr,dwarf2Ranges,dwarf5Ranges,offsetToUnit,parseAbbrev,parseTypes,parseUnits,readType,sigToType"},
			"DecodeError":     {reflect.TypeOf((*q.DecodeError)(nil)).Elem(), "Error", ""},
			"DotDotDotType":   {reflect.TypeOf((*q.DotDotDotType)(nil)).Elem(), "", "String"},
			"Entry":           {reflect.TypeOf((*q.Entry)(nil)).Elem(), "", "AttrField,Val"},
			"EnumType":        {reflect.TypeOf((*q.EnumType)(nil)).Elem(), "", "String"},
			"EnumValue":       {reflect.TypeOf((*q.EnumValue)(nil)).Elem(), "", ""},
			"Field":           {reflect.TypeOf((*q.Field)(nil)).Elem(), "", ""},
			"FloatType":       {reflect.TypeOf((*q.FloatType)(nil)).Elem(), "", ""},
			"FuncType":        {reflect.TypeOf((*q.FuncType)(nil)).Elem(), "", "String"},
			"IntType":         {reflect.TypeOf((*q.IntType)(nil)).Elem(), "", ""},
			"LineEntry":       {reflect.TypeOf((*q.LineEntry)(nil)).Elem(), "", ""},
			"LineFile":        {reflect.TypeOf((*q.LineFile)(nil)).Elem(), "", ""},
			"LineReader":      {reflect.TypeOf((*q.LineReader)(nil)).Elem(), "", "Files,Next,Reset,Seek,SeekPC,Tell,advancePC,readFileEntry,readHeader,readLNCT,readLNCTFormat,resetState,step,updateFile"},
			"LineReaderPos":   {reflect.TypeOf((*q.LineReaderPos)(nil)).Elem(), "", ""},
			"Offset":          {reflect.TypeOf((*q.Offset)(nil)).Elem(), "", ""},
			"PtrType":         {reflect.TypeOf((*q.PtrType)(nil)).Elem(), "", "String"},
			"QualType":        {reflect.TypeOf((*q.QualType)(nil)).Elem(), "", "Size,String"},
			"Reader":          {reflect.TypeOf((*q.Reader)(nil)).Elem(), "", "AddressSize,ByteOrder,Next,Seek,SeekPC,SkipChildren,clone,maybeNextUnit,nextUnit,offset"},
			"StructField":     {reflect.TypeOf((*q.StructField)(nil)).Elem(), "", ""},
			"StructType":      {reflect.TypeOf((*q.StructType)(nil)).Elem(), "", "Defn,String"},
			"Tag":             {reflect.TypeOf((*q.Tag)(nil)).Elem(), "GoString,String", ""},
			"TypedefType":     {reflect.TypeOf((*q.TypedefType)(nil)).Elem(), "", "Size,String"},
			"UcharType":       {reflect.TypeOf((*q.UcharType)(nil)).Elem(), "", ""},
			"UintType":        {reflect.TypeOf((*q.UintType)(nil)).Elem(), "", ""},
			"UnspecifiedType": {reflect.TypeOf((*q.UnspecifiedType)(nil)).Elem(), "", ""},
			"UnsupportedType": {reflect.TypeOf((*q.UnsupportedType)(nil)).Elem(), "", "String"},
			"VoidType":        {reflect.TypeOf((*q.VoidType)(nil)).Elem(), "", "String"},
		},
		AliasTypes: map[string]reflect.Type{},
		Vars: map[string]reflect.Value{
			"ErrUnknownPC": reflect.ValueOf(&q.ErrUnknownPC),
		},
		Funcs: map[string]reflect.Value{
			"New": reflect.ValueOf(q.New),
		},
		TypedConsts: map[string]gossa.TypedConst{
			"AttrAbstractOrigin":        {reflect.TypeOf(q.AttrAbstractOrigin), constant.MakeInt64(49)},
			"AttrAccessibility":         {reflect.TypeOf(q.AttrAccessibility), constant.MakeInt64(50)},
			"AttrAddrBase":              {reflect.TypeOf(q.AttrAddrBase), constant.MakeInt64(115)},
			"AttrAddrClass":             {reflect.TypeOf(q.AttrAddrClass), constant.MakeInt64(51)},
			"AttrAlignment":             {reflect.TypeOf(q.AttrAlignment), constant.MakeInt64(136)},
			"AttrAllocated":             {reflect.TypeOf(q.AttrAllocated), constant.MakeInt64(78)},
			"AttrArtificial":            {reflect.TypeOf(q.AttrArtificial), constant.MakeInt64(52)},
			"AttrAssociated":            {reflect.TypeOf(q.AttrAssociated), constant.MakeInt64(79)},
			"AttrBaseTypes":             {reflect.TypeOf(q.AttrBaseTypes), constant.MakeInt64(53)},
			"AttrBinaryScale":           {reflect.TypeOf(q.AttrBinaryScale), constant.MakeInt64(91)},
			"AttrBitOffset":             {reflect.TypeOf(q.AttrBitOffset), constant.MakeInt64(12)},
			"AttrBitSize":               {reflect.TypeOf(q.AttrBitSize), constant.MakeInt64(13)},
			"AttrByteSize":              {reflect.TypeOf(q.AttrByteSize), constant.MakeInt64(11)},
			"AttrCallAllCalls":          {reflect.TypeOf(q.AttrCallAllCalls), constant.MakeInt64(122)},
			"AttrCallAllSourceCalls":    {reflect.TypeOf(q.AttrCallAllSourceCalls), constant.MakeInt64(123)},
			"AttrCallAllTailCalls":      {reflect.TypeOf(q.AttrCallAllTailCalls), constant.MakeInt64(124)},
			"AttrCallColumn":            {reflect.TypeOf(q.AttrCallColumn), constant.MakeInt64(87)},
			"AttrCallDataLocation":      {reflect.TypeOf(q.AttrCallDataLocation), constant.MakeInt64(133)},
			"AttrCallDataValue":         {reflect.TypeOf(q.AttrCallDataValue), constant.MakeInt64(134)},
			"AttrCallFile":              {reflect.TypeOf(q.AttrCallFile), constant.MakeInt64(88)},
			"AttrCallLine":              {reflect.TypeOf(q.AttrCallLine), constant.MakeInt64(89)},
			"AttrCallOrigin":            {reflect.TypeOf(q.AttrCallOrigin), constant.MakeInt64(127)},
			"AttrCallPC":                {reflect.TypeOf(q.AttrCallPC), constant.MakeInt64(129)},
			"AttrCallParameter":         {reflect.TypeOf(q.AttrCallParameter), constant.MakeInt64(128)},
			"AttrCallReturnPC":          {reflect.TypeOf(q.AttrCallReturnPC), constant.MakeInt64(125)},
			"AttrCallTailCall":          {reflect.TypeOf(q.AttrCallTailCall), constant.MakeInt64(130)},
			"AttrCallTarget":            {reflect.TypeOf(q.AttrCallTarget), constant.MakeInt64(131)},
			"AttrCallTargetClobbered":   {reflect.TypeOf(q.AttrCallTargetClobbered), constant.MakeInt64(132)},
			"AttrCallValue":             {reflect.TypeOf(q.AttrCallValue), constant.MakeInt64(126)},
			"AttrCalling":               {reflect.TypeOf(q.AttrCalling), constant.MakeInt64(54)},
			"AttrCommonRef":             {reflect.TypeOf(q.AttrCommonRef), constant.MakeInt64(26)},
			"AttrCompDir":               {reflect.TypeOf(q.AttrCompDir), constant.MakeInt64(27)},
			"AttrConstExpr":             {reflect.TypeOf(q.AttrConstExpr), constant.MakeInt64(108)},
			"AttrConstValue":            {reflect.TypeOf(q.AttrConstValue), constant.MakeInt64(28)},
			"AttrContainingType":        {reflect.TypeOf(q.AttrContainingType), constant.MakeInt64(29)},
			"AttrCount":                 {reflect.TypeOf(q.AttrCount), constant.MakeInt64(55)},
			"AttrDataBitOffset":         {reflect.TypeOf(q.AttrDataBitOffset), constant.MakeInt64(107)},
			"AttrDataLocation":          {reflect.TypeOf(q.AttrDataLocation), constant.MakeInt64(80)},
			"AttrDataMemberLoc":         {reflect.TypeOf(q.AttrDataMemberLoc), constant.MakeInt64(56)},
			"AttrDecimalScale":          {reflect.TypeOf(q.AttrDecimalScale), constant.MakeInt64(92)},
			"AttrDecimalSign":           {reflect.TypeOf(q.AttrDecimalSign), constant.MakeInt64(94)},
			"AttrDeclColumn":            {reflect.TypeOf(q.AttrDeclColumn), constant.MakeInt64(57)},
			"AttrDeclFile":              {reflect.TypeOf(q.AttrDeclFile), constant.MakeInt64(58)},
			"AttrDeclLine":              {reflect.TypeOf(q.AttrDeclLine), constant.MakeInt64(59)},
			"AttrDeclaration":           {reflect.TypeOf(q.AttrDeclaration), constant.MakeInt64(60)},
			"AttrDefaultValue":          {reflect.TypeOf(q.AttrDefaultValue), constant.MakeInt64(30)},
			"AttrDefaulted":             {reflect.TypeOf(q.AttrDefaulted), constant.MakeInt64(139)},
			"AttrDeleted":               {reflect.TypeOf(q.AttrDeleted), constant.MakeInt64(138)},
			"AttrDescription":           {reflect.TypeOf(q.AttrDescription), constant.MakeInt64(90)},
			"AttrDigitCount":            {reflect.TypeOf(q.AttrDigitCount), constant.MakeInt64(95)},
			"AttrDiscr":                 {reflect.TypeOf(q.AttrDiscr), constant.MakeInt64(21)},
			"AttrDiscrList":             {reflect.TypeOf(q.AttrDiscrList), constant.MakeInt64(61)},
			"AttrDiscrValue":            {reflect.TypeOf(q.AttrDiscrValue), constant.MakeInt64(22)},
			"AttrDwoName":               {reflect.TypeOf(q.AttrDwoName), constant.MakeInt64(118)},
			"AttrElemental":             {reflect.TypeOf(q.AttrElemental), constant.MakeInt64(102)},
			"AttrEncoding":              {reflect.TypeOf(q.AttrEncoding), constant.MakeInt64(62)},
			"AttrEndianity":             {reflect.TypeOf(q.AttrEndianity), constant.MakeInt64(101)},
			"AttrEntrypc":               {reflect.TypeOf(q.AttrEntrypc), constant.MakeInt64(82)},
			"AttrEnumClass":             {reflect.TypeOf(q.AttrEnumClass), constant.MakeInt64(109)},
			"AttrExplicit":              {reflect.TypeOf(q.AttrExplicit), constant.MakeInt64(99)},
			"AttrExportSymbols":         {reflect.TypeOf(q.AttrExportSymbols), constant.MakeInt64(137)},
			"AttrExtension":             {reflect.TypeOf(q.AttrExtension), constant.MakeInt64(84)},
			"AttrExternal":              {reflect.TypeOf(q.AttrExternal), constant.MakeInt64(63)},
			"AttrFrameBase":             {reflect.TypeOf(q.AttrFrameBase), constant.MakeInt64(64)},
			"AttrFriend":                {reflect.TypeOf(q.AttrFriend), constant.MakeInt64(65)},
			"AttrHighpc":                {reflect.TypeOf(q.AttrHighpc), constant.MakeInt64(18)},
			"AttrIdentifierCase":        {reflect.TypeOf(q.AttrIdentifierCase), constant.MakeInt64(66)},
			"AttrImport":                {reflect.TypeOf(q.AttrImport), constant.MakeInt64(24)},
			"AttrInline":                {reflect.TypeOf(q.AttrInline), constant.MakeInt64(32)},
			"AttrIsOptional":            {reflect.TypeOf(q.AttrIsOptional), constant.MakeInt64(33)},
			"AttrLanguage":              {reflect.TypeOf(q.AttrLanguage), constant.MakeInt64(19)},
			"AttrLinkageName":           {reflect.TypeOf(q.AttrLinkageName), constant.MakeInt64(110)},
			"AttrLocation":              {reflect.TypeOf(q.AttrLocation), constant.MakeInt64(2)},
			"AttrLoclistsBase":          {reflect.TypeOf(q.AttrLoclistsBase), constant.MakeInt64(140)},
			"AttrLowerBound":            {reflect.TypeOf(q.AttrLowerBound), constant.MakeInt64(34)},
			"AttrLowpc":                 {reflect.TypeOf(q.AttrLowpc), constant.MakeInt64(17)},
			"AttrMacroInfo":             {reflect.TypeOf(q.AttrMacroInfo), constant.MakeInt64(67)},
			"AttrMacros":                {reflect.TypeOf(q.AttrMacros), constant.MakeInt64(121)},
			"AttrMainSubprogram":        {reflect.TypeOf(q.AttrMainSubprogram), constant.MakeInt64(106)},
			"AttrMutable":               {reflect.TypeOf(q.AttrMutable), constant.MakeInt64(97)},
			"AttrName":                  {reflect.TypeOf(q.AttrName), constant.MakeInt64(3)},
			"AttrNamelistItem":          {reflect.TypeOf(q.AttrNamelistItem), constant.MakeInt64(68)},
			"AttrNoreturn":              {reflect.TypeOf(q.AttrNoreturn), constant.MakeInt64(135)},
			"AttrObjectPointer":         {reflect.TypeOf(q.AttrObjectPointer), constant.MakeInt64(100)},
			"AttrOrdering":              {reflect.TypeOf(q.AttrOrdering), constant.MakeInt64(9)},
			"AttrPictureString":         {reflect.TypeOf(q.AttrPictureString), constant.MakeInt64(96)},
			"AttrPriority":              {reflect.TypeOf(q.AttrPriority), constant.MakeInt64(69)},
			"AttrProducer":              {reflect.TypeOf(q.AttrProducer), constant.MakeInt64(37)},
			"AttrPrototyped":            {reflect.TypeOf(q.AttrPrototyped), constant.MakeInt64(39)},
			"AttrPure":                  {reflect.TypeOf(q.AttrPure), constant.MakeInt64(103)},
			"AttrRanges":                {reflect.TypeOf(q.AttrRanges), constant.MakeInt64(85)},
			"AttrRank":                  {reflect.TypeOf(q.AttrRank), constant.MakeInt64(113)},
			"AttrRecursive":             {reflect.TypeOf(q.AttrRecursive), constant.MakeInt64(104)},
			"AttrReference":             {reflect.TypeOf(q.AttrReference), constant.MakeInt64(119)},
			"AttrReturnAddr":            {reflect.TypeOf(q.AttrReturnAddr), constant.MakeInt64(42)},
			"AttrRnglistsBase":          {reflect.TypeOf(q.AttrRnglistsBase), constant.MakeInt64(116)},
			"AttrRvalueReference":       {reflect.TypeOf(q.AttrRvalueReference), constant.MakeInt64(120)},
			"AttrSegment":               {reflect.TypeOf(q.AttrSegment), constant.MakeInt64(70)},
			"AttrSibling":               {reflect.TypeOf(q.AttrSibling), constant.MakeInt64(1)},
			"AttrSignature":             {reflect.TypeOf(q.AttrSignature), constant.MakeInt64(105)},
			"AttrSmall":                 {reflect.TypeOf(q.AttrSmall), constant.MakeInt64(93)},
			"AttrSpecification":         {reflect.TypeOf(q.AttrSpecification), constant.MakeInt64(71)},
			"AttrStartScope":            {reflect.TypeOf(q.AttrStartScope), constant.MakeInt64(44)},
			"AttrStaticLink":            {reflect.TypeOf(q.AttrStaticLink), constant.MakeInt64(72)},
			"AttrStmtList":              {reflect.TypeOf(q.AttrStmtList), constant.MakeInt64(16)},
			"AttrStrOffsetsBase":        {reflect.TypeOf(q.AttrStrOffsetsBase), constant.MakeInt64(114)},
			"AttrStride":                {reflect.TypeOf(q.AttrStride), constant.MakeInt64(81)},
			"AttrStrideSize":            {reflect.TypeOf(q.AttrStrideSize), constant.MakeInt64(46)},
			"AttrStringLength":          {reflect.TypeOf(q.AttrStringLength), constant.MakeInt64(25)},
			"AttrStringLengthBitSize":   {reflect.TypeOf(q.AttrStringLengthBitSize), constant.MakeInt64(111)},
			"AttrStringLengthByteSize":  {reflect.TypeOf(q.AttrStringLengthByteSize), constant.MakeInt64(112)},
			"AttrThreadsScaled":         {reflect.TypeOf(q.AttrThreadsScaled), constant.MakeInt64(98)},
			"AttrTrampoline":            {reflect.TypeOf(q.AttrTrampoline), constant.MakeInt64(86)},
			"AttrType":                  {reflect.TypeOf(q.AttrType), constant.MakeInt64(73)},
			"AttrUpperBound":            {reflect.TypeOf(q.AttrUpperBound), constant.MakeInt64(47)},
			"AttrUseLocation":           {reflect.TypeOf(q.AttrUseLocation), constant.MakeInt64(74)},
			"AttrUseUTF8":               {reflect.TypeOf(q.AttrUseUTF8), constant.MakeInt64(83)},
			"AttrVarParam":              {reflect.TypeOf(q.AttrVarParam), constant.MakeInt64(75)},
			"AttrVirtuality":            {reflect.TypeOf(q.AttrVirtuality), constant.MakeInt64(76)},
			"AttrVisibility":            {reflect.TypeOf(q.AttrVisibility), constant.MakeInt64(23)},
			"AttrVtableElemLoc":         {reflect.TypeOf(q.AttrVtableElemLoc), constant.MakeInt64(77)},
			"ClassAddrPtr":              {reflect.TypeOf(q.ClassAddrPtr), constant.MakeInt64(15)},
			"ClassAddress":              {reflect.TypeOf(q.ClassAddress), constant.MakeInt64(1)},
			"ClassBlock":                {reflect.TypeOf(q.ClassBlock), constant.MakeInt64(2)},
			"ClassConstant":             {reflect.TypeOf(q.ClassConstant), constant.MakeInt64(3)},
			"ClassExprLoc":              {reflect.TypeOf(q.ClassExprLoc), constant.MakeInt64(4)},
			"ClassFlag":                 {reflect.TypeOf(q.ClassFlag), constant.MakeInt64(5)},
			"ClassLinePtr":              {reflect.TypeOf(q.ClassLinePtr), constant.MakeInt64(6)},
			"ClassLocList":              {reflect.TypeOf(q.ClassLocList), constant.MakeInt64(16)},
			"ClassLocListPtr":           {reflect.TypeOf(q.ClassLocListPtr), constant.MakeInt64(7)},
			"ClassMacPtr":               {reflect.TypeOf(q.ClassMacPtr), constant.MakeInt64(8)},
			"ClassRangeListPtr":         {reflect.TypeOf(q.ClassRangeListPtr), constant.MakeInt64(9)},
			"ClassReference":            {reflect.TypeOf(q.ClassReference), constant.MakeInt64(10)},
			"ClassReferenceAlt":         {reflect.TypeOf(q.ClassReferenceAlt), constant.MakeInt64(13)},
			"ClassReferenceSig":         {reflect.TypeOf(q.ClassReferenceSig), constant.MakeInt64(11)},
			"ClassRngList":              {reflect.TypeOf(q.ClassRngList), constant.MakeInt64(17)},
			"ClassRngListsPtr":          {reflect.TypeOf(q.ClassRngListsPtr), constant.MakeInt64(18)},
			"ClassStrOffsetsPtr":        {reflect.TypeOf(q.ClassStrOffsetsPtr), constant.MakeInt64(19)},
			"ClassString":               {reflect.TypeOf(q.ClassString), constant.MakeInt64(12)},
			"ClassStringAlt":            {reflect.TypeOf(q.ClassStringAlt), constant.MakeInt64(14)},
			"ClassUnknown":              {reflect.TypeOf(q.ClassUnknown), constant.MakeInt64(0)},
			"TagAccessDeclaration":      {reflect.TypeOf(q.TagAccessDeclaration), constant.MakeInt64(35)},
			"TagArrayType":              {reflect.TypeOf(q.TagArrayType), constant.MakeInt64(1)},
			"TagAtomicType":             {reflect.TypeOf(q.TagAtomicType), constant.MakeInt64(71)},
			"TagBaseType":               {reflect.TypeOf(q.TagBaseType), constant.MakeInt64(36)},
			"TagCallSite":               {reflect.TypeOf(q.TagCallSite), constant.MakeInt64(72)},
			"TagCallSiteParameter":      {reflect.TypeOf(q.TagCallSiteParameter), constant.MakeInt64(73)},
			"TagCatchDwarfBlock":        {reflect.TypeOf(q.TagCatchDwarfBlock), constant.MakeInt64(37)},
			"TagClassType":              {reflect.TypeOf(q.TagClassType), constant.MakeInt64(2)},
			"TagCoarrayType":            {reflect.TypeOf(q.TagCoarrayType), constant.MakeInt64(68)},
			"TagCommonDwarfBlock":       {reflect.TypeOf(q.TagCommonDwarfBlock), constant.MakeInt64(26)},
			"TagCommonInclusion":        {reflect.TypeOf(q.TagCommonInclusion), constant.MakeInt64(27)},
			"TagCompileUnit":            {reflect.TypeOf(q.TagCompileUnit), constant.MakeInt64(17)},
			"TagCondition":              {reflect.TypeOf(q.TagCondition), constant.MakeInt64(63)},
			"TagConstType":              {reflect.TypeOf(q.TagConstType), constant.MakeInt64(38)},
			"TagConstant":               {reflect.TypeOf(q.TagConstant), constant.MakeInt64(39)},
			"TagDwarfProcedure":         {reflect.TypeOf(q.TagDwarfProcedure), constant.MakeInt64(54)},
			"TagDynamicType":            {reflect.TypeOf(q.TagDynamicType), constant.MakeInt64(70)},
			"TagEntryPoint":             {reflect.TypeOf(q.TagEntryPoint), constant.MakeInt64(3)},
			"TagEnumerationType":        {reflect.TypeOf(q.TagEnumerationType), constant.MakeInt64(4)},
			"TagEnumerator":             {reflect.TypeOf(q.TagEnumerator), constant.MakeInt64(40)},
			"TagFileType":               {reflect.TypeOf(q.TagFileType), constant.MakeInt64(41)},
			"TagFormalParameter":        {reflect.TypeOf(q.TagFormalParameter), constant.MakeInt64(5)},
			"TagFriend":                 {reflect.TypeOf(q.TagFriend), constant.MakeInt64(42)},
			"TagGenericSubrange":        {reflect.TypeOf(q.TagGenericSubrange), constant.MakeInt64(69)},
			"TagImmutableType":          {reflect.TypeOf(q.TagImmutableType), constant.MakeInt64(75)},
			"TagImportedDeclaration":    {reflect.TypeOf(q.TagImportedDeclaration), constant.MakeInt64(8)},
			"TagImportedModule":         {reflect.TypeOf(q.TagImportedModule), constant.MakeInt64(58)},
			"TagImportedUnit":           {reflect.TypeOf(q.TagImportedUnit), constant.MakeInt64(61)},
			"TagInheritance":            {reflect.TypeOf(q.TagInheritance), constant.MakeInt64(28)},
			"TagInlinedSubroutine":      {reflect.TypeOf(q.TagInlinedSubroutine), constant.MakeInt64(29)},
			"TagInterfaceType":          {reflect.TypeOf(q.TagInterfaceType), constant.MakeInt64(56)},
			"TagLabel":                  {reflect.TypeOf(q.TagLabel), constant.MakeInt64(10)},
			"TagLexDwarfBlock":          {reflect.TypeOf(q.TagLexDwarfBlock), constant.MakeInt64(11)},
			"TagMember":                 {reflect.TypeOf(q.TagMember), constant.MakeInt64(13)},
			"TagModule":                 {reflect.TypeOf(q.TagModule), constant.MakeInt64(30)},
			"TagMutableType":            {reflect.TypeOf(q.TagMutableType), constant.MakeInt64(62)},
			"TagNamelist":               {reflect.TypeOf(q.TagNamelist), constant.MakeInt64(43)},
			"TagNamelistItem":           {reflect.TypeOf(q.TagNamelistItem), constant.MakeInt64(44)},
			"TagNamespace":              {reflect.TypeOf(q.TagNamespace), constant.MakeInt64(57)},
			"TagPackedType":             {reflect.TypeOf(q.TagPackedType), constant.MakeInt64(45)},
			"TagPartialUnit":            {reflect.TypeOf(q.TagPartialUnit), constant.MakeInt64(60)},
			"TagPointerType":            {reflect.TypeOf(q.TagPointerType), constant.MakeInt64(15)},
			"TagPtrToMemberType":        {reflect.TypeOf(q.TagPtrToMemberType), constant.MakeInt64(31)},
			"TagReferenceType":          {reflect.TypeOf(q.TagReferenceType), constant.MakeInt64(16)},
			"TagRestrictType":           {reflect.TypeOf(q.TagRestrictType), constant.MakeInt64(55)},
			"TagRvalueReferenceType":    {reflect.TypeOf(q.TagRvalueReferenceType), constant.MakeInt64(66)},
			"TagSetType":                {reflect.TypeOf(q.TagSetType), constant.MakeInt64(32)},
			"TagSharedType":             {reflect.TypeOf(q.TagSharedType), constant.MakeInt64(64)},
			"TagSkeletonUnit":           {reflect.TypeOf(q.TagSkeletonUnit), constant.MakeInt64(74)},
			"TagStringType":             {reflect.TypeOf(q.TagStringType), constant.MakeInt64(18)},
			"TagStructType":             {reflect.TypeOf(q.TagStructType), constant.MakeInt64(19)},
			"TagSubprogram":             {reflect.TypeOf(q.TagSubprogram), constant.MakeInt64(46)},
			"TagSubrangeType":           {reflect.TypeOf(q.TagSubrangeType), constant.MakeInt64(33)},
			"TagSubroutineType":         {reflect.TypeOf(q.TagSubroutineType), constant.MakeInt64(21)},
			"TagTemplateAlias":          {reflect.TypeOf(q.TagTemplateAlias), constant.MakeInt64(67)},
			"TagTemplateTypeParameter":  {reflect.TypeOf(q.TagTemplateTypeParameter), constant.MakeInt64(47)},
			"TagTemplateValueParameter": {reflect.TypeOf(q.TagTemplateValueParameter), constant.MakeInt64(48)},
			"TagThrownType":             {reflect.TypeOf(q.TagThrownType), constant.MakeInt64(49)},
			"TagTryDwarfBlock":          {reflect.TypeOf(q.TagTryDwarfBlock), constant.MakeInt64(50)},
			"TagTypeUnit":               {reflect.TypeOf(q.TagTypeUnit), constant.MakeInt64(65)},
			"TagTypedef":                {reflect.TypeOf(q.TagTypedef), constant.MakeInt64(22)},
			"TagUnionType":              {reflect.TypeOf(q.TagUnionType), constant.MakeInt64(23)},
			"TagUnspecifiedParameters":  {reflect.TypeOf(q.TagUnspecifiedParameters), constant.MakeInt64(24)},
			"TagUnspecifiedType":        {reflect.TypeOf(q.TagUnspecifiedType), constant.MakeInt64(59)},
			"TagVariable":               {reflect.TypeOf(q.TagVariable), constant.MakeInt64(52)},
			"TagVariant":                {reflect.TypeOf(q.TagVariant), constant.MakeInt64(25)},
			"TagVariantPart":            {reflect.TypeOf(q.TagVariantPart), constant.MakeInt64(51)},
			"TagVolatileType":           {reflect.TypeOf(q.TagVolatileType), constant.MakeInt64(53)},
			"TagWithStmt":               {reflect.TypeOf(q.TagWithStmt), constant.MakeInt64(34)},
		},
		UntypedConsts: map[string]gossa.UntypedConst{},
	})
}
